//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AuthConfigDefaultLocale.
const (
	AuthConfigDefaultLocaleDe AuthConfigDefaultLocale = "de"
	AuthConfigDefaultLocaleEn AuthConfigDefaultLocale = "en"
)

// Valid indicates whether the value is a known member of the AuthConfigDefaultLocale enum.
func (e AuthConfigDefaultLocale) Valid() bool {
	switch e {
	case AuthConfigDefaultLocaleDe:
		return true
	case AuthConfigDefaultLocaleEn:
		return true
	default:
		return false
	}
}

// Defines values for NutzerCreateSprache.
const (
	NutzerCreateSpracheDe NutzerCreateSprache = "de"
	NutzerCreateSpracheEn NutzerCreateSprache = "en"
)

// Valid indicates whether the value is a known member of the NutzerCreateSprache enum.
func (e NutzerCreateSprache) Valid() bool {
	switch e {
	case NutzerCreateSpracheDe:
		return true
	case NutzerCreateSpracheEn:
		return true
	default:
		return false
	}
}

// Defines values for ProfilPatchSprache.
const (
	ProfilPatchSpracheDe ProfilPatchSprache = "de"
	ProfilPatchSpracheEn ProfilPatchSprache = "en"
)

// Valid indicates whether the value is a known member of the ProfilPatchSprache enum.
func (e ProfilPatchSprache) Valid() bool {
	switch e {
	case ProfilPatchSpracheDe:
		return true
	case ProfilPatchSpracheEn:
		return true
	default:
		return false
	}
}

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	DefaultLocale     AuthConfigDefaultLocale `json:"default_locale"`
	Header            bool                    `json:"header"`
	HeaderLogoutUrl   *string                 `json:"header_logout_url,omitempty"`
	Oidc              bool                    `json:"oidc"`
	OidcAutoRedirect  *bool                   `json:"oidc_auto_redirect,omitempty"`
	OidcButtonLabel   *string                 `json:"oidc_button_label,omitempty"`
	Passwort          bool                    `json:"passwort"`
	SetupErforderlich bool                    `json:"setup_erforderlich"`
}

// AuthConfigDefaultLocale defines model for AuthConfig.DefaultLocale.
type AuthConfigDefaultLocale string

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string `json:"code"`
	Pointer string `json:"pointer"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Benutzername string `json:"benutzername"`
	Passwort     string `json:"passwort"`
}

// Nutzer defines model for Nutzer.
type Nutzer struct {
	Aktiv          bool    `json:"aktiv"`
	Anzeigename    string  `json:"anzeigename"`
	Benutzername   string  `json:"benutzername"`
	Email          *string `json:"email,omitempty"`
	Id             string  `json:"id"`
	IstAdmin       bool    `json:"ist_admin"`
	KiErlaubt      bool    `json:"ki_erlaubt"`
	Personalnummer *string `json:"personalnummer,omitempty"`
	Sprache        string  `json:"sprache"`
	Version        int64   `json:"version"`
}

// NutzerAdminPatch defines model for NutzerAdminPatch.
type NutzerAdminPatch struct {
	Aktiv         *bool   `json:"aktiv,omitempty"`
	IstAdminLokal *bool   `json:"ist_admin_lokal,omitempty"`
	Passwort      *string `json:"passwort,omitempty"`
}

// NutzerCreate defines model for NutzerCreate.
type NutzerCreate struct {
	Anzeigename  string               `json:"anzeigename"`
	Benutzername string               `json:"benutzername"`
	Email        *string              `json:"email,omitempty"`
	IstAdmin     *bool                `json:"ist_admin,omitempty"`
	Passwort     string               `json:"passwort"`
	Sprache      *NutzerCreateSprache `json:"sprache,omitempty"`
}

// NutzerCreateSprache defines model for NutzerCreate.Sprache.
type NutzerCreateSprache string

// NutzerListe defines model for NutzerListe.
type NutzerListe struct {
	Items      []Nutzer `json:"items"`
	NextCursor *string  `json:"next_cursor,omitempty"`
}

// PasswortRequest defines model for PasswortRequest.
type PasswortRequest struct {
	AktuellesPasswort *string `json:"aktuelles_passwort,omitempty"`
	NeuesPasswort     string  `json:"neues_passwort"`
}

// Problem defines model for Problem.
type Problem struct {
	Code   string        `json:"code"`
	Detail *string       `json:"detail,omitempty"`
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`
	Title  string        `json:"title"`
	Type   string        `json:"type"`
}

// ProfilPatch defines model for ProfilPatch.
type ProfilPatch struct {
	Anzeigename    *string             `json:"anzeigename,omitempty"`
	KiErlaubt      *bool               `json:"ki_erlaubt,omitempty"`
	Personalnummer *string             `json:"personalnummer,omitempty"`
	Sprache        *ProfilPatchSprache `json:"sprache,omitempty"`
}

// ProfilPatchSprache defines model for ProfilPatch.Sprache.
type ProfilPatchSprache string

// Session defines model for Session.
type Session struct {
	Aktuell       bool      `json:"aktuell"`
	Id            string    `json:"id"`
	Ip            *string   `json:"ip,omitempty"`
	LetzteNutzung time.Time `json:"letzte_nutzung"`
	UserAgent     *string   `json:"user_agent,omitempty"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	Anzeigename  string  `json:"anzeigename"`
	Benutzername string  `json:"benutzername"`
	Email        *string `json:"email,omitempty"`
	Passwort     string  `json:"passwort"`
	Token        string  `json:"token"`
}

// IfMatch defines model for IfMatch.
type IfMatch = string

// GetAdminNutzerParams defines parameters for GetAdminNutzer.
type GetAdminNutzerParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PatchAdminNutzerParams defines parameters for PatchAdminNutzer.
type PatchAdminNutzerParams struct {
	IfMatch *IfMatch `json:"If-Match,omitempty"`
}

// GetAuthOidcCallbackParams defines parameters for GetAuthOidcCallback.
type GetAuthOidcCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// PutAuthPasswortParams defines parameters for PutAuthPasswort.
type PutAuthPasswortParams struct {
	IfMatch *IfMatch `json:"If-Match,omitempty"`
}

// PatchMeParams defines parameters for PatchMe.
type PatchMeParams struct {
	IfMatch *IfMatch `json:"If-Match,omitempty"`
}

// PostAdminNutzerJSONRequestBody defines body for PostAdminNutzer for application/json ContentType.
type PostAdminNutzerJSONRequestBody = NutzerCreate

// PatchAdminNutzerJSONRequestBody defines body for PatchAdminNutzer for application/json ContentType.
type PatchAdminNutzerJSONRequestBody = NutzerAdminPatch

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PutAuthPasswortJSONRequestBody defines body for PutAuthPasswort for application/json ContentType.
type PutAuthPasswortJSONRequestBody = PasswortRequest

// PostAuthSetupJSONRequestBody defines body for PostAuthSetup for application/json ContentType.
type PostAuthSetupJSONRequestBody = SetupRequest

// PatchMeJSONRequestBody defines body for PatchMe for application/json ContentType.
type PatchMeJSONRequestBody = ProfilPatch

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAdminNutzer List Nutzer
	// (GET /api/v1/admin/nutzer)
	GetAdminNutzer(w http.ResponseWriter, r *http.Request, params GetAdminNutzerParams)
	// PostAdminNutzer Create a Nutzer
	// (POST /api/v1/admin/nutzer)
	PostAdminNutzer(w http.ResponseWriter, r *http.Request)
	// PatchAdminNutzer Update a Nutzer
	// (PATCH /api/v1/admin/nutzer/{id})
	PatchAdminNutzer(w http.ResponseWriter, r *http.Request, id string, params PatchAdminNutzerParams)
	// GetAuthConfig Active login methods
	// (GET /api/v1/auth/config)
	GetAuthConfig(w http.ResponseWriter, r *http.Request)
	// PostAuthLogin Password login
	// (POST /api/v1/auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// PostAuthLogout End the current session
	// (POST /api/v1/auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// GetAuthMe Current Nutzer
	// (GET /api/v1/auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// GetAuthOidcCallback OIDC redirect URI
	// (GET /api/v1/auth/oidc/callback)
	GetAuthOidcCallback(w http.ResponseWriter, r *http.Request, params GetAuthOidcCallbackParams)
	// GetAuthOidcStart Start the OIDC authorization code flow with PKCE
	// (GET /api/v1/auth/oidc/start)
	GetAuthOidcStart(w http.ResponseWriter, r *http.Request)
	// PutAuthPasswort Change the current Nutzer password
	// (PUT /api/v1/auth/passwort)
	PutAuthPasswort(w http.ResponseWriter, r *http.Request, params PutAuthPasswortParams)
	// PostAuthSetup Create the first Admin with the setup token
	// (POST /api/v1/auth/setup)
	PostAuthSetup(w http.ResponseWriter, r *http.Request)
	// GetMe Profile of the current Nutzer
	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// PatchMe Update the profile
	// (PATCH /api/v1/me)
	PatchMe(w http.ResponseWriter, r *http.Request, params PatchMeParams)
	// GetMeSessions Active sessions of the current Nutzer
	// (GET /api/v1/me/sessions)
	GetMeSessions(w http.ResponseWriter, r *http.Request)
	// DeleteMeSession End one session
	// (DELETE /api/v1/me/sessions/{id})
	DeleteMeSession(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminNutzer operation middleware
func (siw *ServerInterfaceWrapper) GetAdminNutzer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminNutzerParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminNutzer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminNutzer operation middleware
func (siw *ServerInterfaceWrapper) PostAdminNutzer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminNutzer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAdminNutzer operation middleware
func (siw *ServerInterfaceWrapper) PatchAdminNutzer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchAdminNutzerParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAdminNutzer(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAuthConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthOidcCallback operation middleware
func (siw *ServerInterfaceWrapper) GetAuthOidcCallback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthOidcCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthOidcCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthOidcStart operation middleware
func (siw *ServerInterfaceWrapper) GetAuthOidcStart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthOidcStart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAuthPasswort operation middleware
func (siw *ServerInterfaceWrapper) PutAuthPasswort(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PutAuthPasswortParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthPasswort(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthSetup operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSetup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchMe operation middleware
func (siw *ServerInterfaceWrapper) PatchMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchMeParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeSessions operation middleware
func (siw *ServerInterfaceWrapper) GetMeSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMeSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteMeSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMeSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/config", wrapper.GetAuthConfig)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/login", wrapper.PostAuthLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/logout", wrapper.PostAuthLogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/oidc/start", wrapper.GetAuthOidcStart)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/oidc/callback", wrapper.GetAuthOidcCallback)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/setup", wrapper.PostAuthSetup)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/auth/passwort", wrapper.PutAuthPasswort)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/me", wrapper.PatchMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/me/sessions", wrapper.GetMeSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/me/sessions/{id}", wrapper.DeleteMeSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/admin/nutzer", wrapper.GetAdminNutzer)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/admin/nutzer", wrapper.PostAdminNutzer)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/admin/nutzer/{id}", wrapper.PatchAdminNutzer)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type GetAdminNutzerRequestObject struct {
	Params GetAdminNutzerParams
}

type GetAdminNutzerResponseObject interface {
	VisitGetAdminNutzerResponse(w http.ResponseWriter) error
}

type GetAdminNutzer200JSONResponse NutzerListe

func (response GetAdminNutzer200JSONResponse) VisitGetAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminNutzer401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetAdminNutzer401ApplicationProblemPlusJSONResponse) VisitGetAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminNutzer403ApplicationProblemPlusJSONResponse Problem

func (response GetAdminNutzer403ApplicationProblemPlusJSONResponse) VisitGetAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminNutzerRequestObject struct {
	Body *PostAdminNutzerJSONRequestBody
}

type PostAdminNutzerResponseObject interface {
	VisitPostAdminNutzerResponse(w http.ResponseWriter) error
}

type PostAdminNutzer201JSONResponse Nutzer

func (response PostAdminNutzer201JSONResponse) VisitPostAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminNutzer400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response PostAdminNutzer400ApplicationProblemPlusJSONResponse) VisitPostAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminNutzer401ApplicationProblemPlusJSONResponse Problem

func (response PostAdminNutzer401ApplicationProblemPlusJSONResponse) VisitPostAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAdminNutzer403ApplicationProblemPlusJSONResponse Problem

func (response PostAdminNutzer403ApplicationProblemPlusJSONResponse) VisitPostAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzerRequestObject struct {
	Id     string `json:"id"`
	Params PatchAdminNutzerParams
	Body   *PatchAdminNutzerJSONRequestBody
}

type PatchAdminNutzerResponseObject interface {
	VisitPatchAdminNutzerResponse(w http.ResponseWriter) error
}

type PatchAdminNutzer200JSONResponse Nutzer

func (response PatchAdminNutzer200JSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzer400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response PatchAdminNutzer400ApplicationProblemPlusJSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzer401ApplicationProblemPlusJSONResponse Problem

func (response PatchAdminNutzer401ApplicationProblemPlusJSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzer403ApplicationProblemPlusJSONResponse Problem

func (response PatchAdminNutzer403ApplicationProblemPlusJSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzer404ApplicationProblemPlusJSONResponse Problem

func (response PatchAdminNutzer404ApplicationProblemPlusJSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzer409ApplicationProblemPlusJSONResponse Problem

func (response PatchAdminNutzer409ApplicationProblemPlusJSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzer412ApplicationProblemPlusJSONResponse Problem

func (response PatchAdminNutzer412ApplicationProblemPlusJSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminNutzer428ApplicationProblemPlusJSONResponse Problem

func (response PatchAdminNutzer428ApplicationProblemPlusJSONResponse) VisitPatchAdminNutzerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthConfigRequestObject struct {
}

type GetAuthConfigResponseObject interface {
	VisitGetAuthConfigResponse(w http.ResponseWriter) error
}

type GetAuthConfig200JSONResponse AuthConfig

func (response GetAuthConfig200JSONResponse) VisitGetAuthConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLoginRequestObject struct {
	Body *PostAuthLoginJSONRequestBody
}

type PostAuthLoginResponseObject interface {
	VisitPostAuthLoginResponse(w http.ResponseWriter) error
}

type PostAuthLogin200JSONResponse Nutzer

func (response PostAuthLogin200JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response PostAuthLogin401ApplicationProblemPlusJSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogin429ApplicationProblemPlusJSONResponse Problem

func (response PostAuthLogin429ApplicationProblemPlusJSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthLogoutRequestObject struct {
}

type PostAuthLogoutResponseObject interface {
	VisitPostAuthLogoutResponse(w http.ResponseWriter) error
}

type PostAuthLogout204Response struct {
}

func (response PostAuthLogout204Response) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse Nutzer

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMe401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetAuthMe401ApplicationProblemPlusJSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthOidcCallbackRequestObject struct {
	Params GetAuthOidcCallbackParams
}

type GetAuthOidcCallbackResponseObject interface {
	VisitGetAuthOidcCallbackResponse(w http.ResponseWriter) error
}

type GetAuthOidcCallback302ResponseHeaders struct {
	Location *string
}

type GetAuthOidcCallback302Response struct {
	Headers GetAuthOidcCallback302ResponseHeaders
}

func (response GetAuthOidcCallback302Response) VisitGetAuthOidcCallbackResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(302)
	return nil
}

type GetAuthOidcStartRequestObject struct {
}

type GetAuthOidcStartResponseObject interface {
	VisitGetAuthOidcStartResponse(w http.ResponseWriter) error
}

type GetAuthOidcStart302ResponseHeaders struct {
	Location *string
}

type GetAuthOidcStart302Response struct {
	Headers GetAuthOidcStart302ResponseHeaders
}

func (response GetAuthOidcStart302Response) VisitGetAuthOidcStartResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(302)
	return nil
}

type GetAuthOidcStart400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetAuthOidcStart400ApplicationProblemPlusJSONResponse) VisitGetAuthOidcStartResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutAuthPasswortRequestObject struct {
	Params PutAuthPasswortParams
	Body   *PutAuthPasswortJSONRequestBody
}

type PutAuthPasswortResponseObject interface {
	VisitPutAuthPasswortResponse(w http.ResponseWriter) error
}

type PutAuthPasswort204Response struct {
}

func (response PutAuthPasswort204Response) VisitPutAuthPasswortResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutAuthPasswort400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response PutAuthPasswort400ApplicationProblemPlusJSONResponse) VisitPutAuthPasswortResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutAuthPasswort401ApplicationProblemPlusJSONResponse Problem

func (response PutAuthPasswort401ApplicationProblemPlusJSONResponse) VisitPutAuthPasswortResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PutAuthPasswort428ApplicationProblemPlusJSONResponse Problem

func (response PutAuthPasswort428ApplicationProblemPlusJSONResponse) VisitPutAuthPasswortResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthSetupRequestObject struct {
	Body *PostAuthSetupJSONRequestBody
}

type PostAuthSetupResponseObject interface {
	VisitPostAuthSetupResponse(w http.ResponseWriter) error
}

type PostAuthSetup201JSONResponse Nutzer

func (response PostAuthSetup201JSONResponse) VisitPostAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthSetup400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response PostAuthSetup400ApplicationProblemPlusJSONResponse) VisitPostAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostAuthSetup403ApplicationProblemPlusJSONResponse Problem

func (response PostAuthSetup403ApplicationProblemPlusJSONResponse) VisitPostAuthSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Nutzer

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchMeRequestObject struct {
	Params PatchMeParams
	Body   *PatchMeJSONRequestBody
}

type PatchMeResponseObject interface {
	VisitPatchMeResponse(w http.ResponseWriter) error
}

type PatchMe200JSONResponse Nutzer

func (response PatchMe200JSONResponse) VisitPatchMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchMe400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response PatchMe400ApplicationProblemPlusJSONResponse) VisitPatchMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchMe401ApplicationProblemPlusJSONResponse Problem

func (response PatchMe401ApplicationProblemPlusJSONResponse) VisitPatchMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchMe412ApplicationProblemPlusJSONResponse Problem

func (response PatchMe412ApplicationProblemPlusJSONResponse) VisitPatchMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type PatchMe428ApplicationProblemPlusJSONResponse Problem

func (response PatchMe428ApplicationProblemPlusJSONResponse) VisitPatchMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(428)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeSessionsRequestObject struct {
}

type GetMeSessionsResponseObject interface {
	VisitGetMeSessionsResponse(w http.ResponseWriter) error
}

type GetMeSessions200JSONResponse struct {
	Items []Session `json:"items"`
}

func (response GetMeSessions200JSONResponse) VisitGetMeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeSessions401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetMeSessions401ApplicationProblemPlusJSONResponse) VisitGetMeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMeSessionRequestObject struct {
	Id string `json:"id"`
}

type DeleteMeSessionResponseObject interface {
	VisitDeleteMeSessionResponse(w http.ResponseWriter) error
}

type DeleteMeSession204Response struct {
}

func (response DeleteMeSession204Response) VisitDeleteMeSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMeSession401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response DeleteMeSession401ApplicationProblemPlusJSONResponse) VisitDeleteMeSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMeSession404ApplicationProblemPlusJSONResponse Problem

func (response DeleteMeSession404ApplicationProblemPlusJSONResponse) VisitDeleteMeSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAdminNutzer List Nutzer
	// (GET /api/v1/admin/nutzer)
	GetAdminNutzer(ctx context.Context, request GetAdminNutzerRequestObject) (GetAdminNutzerResponseObject, error)
	// PostAdminNutzer Create a Nutzer
	// (POST /api/v1/admin/nutzer)
	PostAdminNutzer(ctx context.Context, request PostAdminNutzerRequestObject) (PostAdminNutzerResponseObject, error)
	// PatchAdminNutzer Update a Nutzer
	// (PATCH /api/v1/admin/nutzer/{id})
	PatchAdminNutzer(ctx context.Context, request PatchAdminNutzerRequestObject) (PatchAdminNutzerResponseObject, error)
	// GetAuthConfig Active login methods
	// (GET /api/v1/auth/config)
	GetAuthConfig(ctx context.Context, request GetAuthConfigRequestObject) (GetAuthConfigResponseObject, error)
	// PostAuthLogin Password login
	// (POST /api/v1/auth/login)
	PostAuthLogin(ctx context.Context, request PostAuthLoginRequestObject) (PostAuthLoginResponseObject, error)
	// PostAuthLogout End the current session
	// (POST /api/v1/auth/logout)
	PostAuthLogout(ctx context.Context, request PostAuthLogoutRequestObject) (PostAuthLogoutResponseObject, error)
	// GetAuthMe Current Nutzer
	// (GET /api/v1/auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// GetAuthOidcCallback OIDC redirect URI
	// (GET /api/v1/auth/oidc/callback)
	GetAuthOidcCallback(ctx context.Context, request GetAuthOidcCallbackRequestObject) (GetAuthOidcCallbackResponseObject, error)
	// GetAuthOidcStart Start the OIDC authorization code flow with PKCE
	// (GET /api/v1/auth/oidc/start)
	GetAuthOidcStart(ctx context.Context, request GetAuthOidcStartRequestObject) (GetAuthOidcStartResponseObject, error)
	// PutAuthPasswort Change the current Nutzer password
	// (PUT /api/v1/auth/passwort)
	PutAuthPasswort(ctx context.Context, request PutAuthPasswortRequestObject) (PutAuthPasswortResponseObject, error)
	// PostAuthSetup Create the first Admin with the setup token
	// (POST /api/v1/auth/setup)
	PostAuthSetup(ctx context.Context, request PostAuthSetupRequestObject) (PostAuthSetupResponseObject, error)
	// GetMe Profile of the current Nutzer
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// PatchMe Update the profile
	// (PATCH /api/v1/me)
	PatchMe(ctx context.Context, request PatchMeRequestObject) (PatchMeResponseObject, error)
	// GetMeSessions Active sessions of the current Nutzer
	// (GET /api/v1/me/sessions)
	GetMeSessions(ctx context.Context, request GetMeSessionsRequestObject) (GetMeSessionsResponseObject, error)
	// DeleteMeSession End one session
	// (DELETE /api/v1/me/sessions/{id})
	DeleteMeSession(ctx context.Context, request DeleteMeSessionRequestObject) (DeleteMeSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAdminNutzer operation middleware
func (sh *strictHandler) GetAdminNutzer(w http.ResponseWriter, r *http.Request, params GetAdminNutzerParams) {
	var request GetAdminNutzerRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminNutzer(ctx, request.(GetAdminNutzerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminNutzer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminNutzerResponseObject); ok {
		if err := validResponse.VisitGetAdminNutzerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAdminNutzer operation middleware
func (sh *strictHandler) PostAdminNutzer(w http.ResponseWriter, r *http.Request) {
	var request PostAdminNutzerRequestObject

	var body PostAdminNutzerJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAdminNutzer(ctx, request.(PostAdminNutzerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAdminNutzer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAdminNutzerResponseObject); ok {
		if err := validResponse.VisitPostAdminNutzerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchAdminNutzer operation middleware
func (sh *strictHandler) PatchAdminNutzer(w http.ResponseWriter, r *http.Request, id string, params PatchAdminNutzerParams) {
	var request PatchAdminNutzerRequestObject

	request.Id = id
	request.Params = params

	var body PatchAdminNutzerJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchAdminNutzer(ctx, request.(PatchAdminNutzerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchAdminNutzer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchAdminNutzerResponseObject); ok {
		if err := validResponse.VisitPatchAdminNutzerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthConfig operation middleware
func (sh *strictHandler) GetAuthConfig(w http.ResponseWriter, r *http.Request) {
	var request GetAuthConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthConfig(ctx, request.(GetAuthConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthConfigResponseObject); ok {
		if err := validResponse.VisitGetAuthConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogin operation middleware
func (sh *strictHandler) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLoginRequestObject

	var body PostAuthLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogin(ctx, request.(PostAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLoginResponseObject); ok {
		if err := validResponse.VisitPostAuthLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogout operation middleware
func (sh *strictHandler) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogout(ctx, request.(PostAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostAuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthOidcCallback operation middleware
func (sh *strictHandler) GetAuthOidcCallback(w http.ResponseWriter, r *http.Request, params GetAuthOidcCallbackParams) {
	var request GetAuthOidcCallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthOidcCallback(ctx, request.(GetAuthOidcCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthOidcCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthOidcCallbackResponseObject); ok {
		if err := validResponse.VisitGetAuthOidcCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthOidcStart operation middleware
func (sh *strictHandler) GetAuthOidcStart(w http.ResponseWriter, r *http.Request) {
	var request GetAuthOidcStartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthOidcStart(ctx, request.(GetAuthOidcStartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthOidcStart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthOidcStartResponseObject); ok {
		if err := validResponse.VisitGetAuthOidcStartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutAuthPasswort operation middleware
func (sh *strictHandler) PutAuthPasswort(w http.ResponseWriter, r *http.Request, params PutAuthPasswortParams) {
	var request PutAuthPasswortRequestObject

	request.Params = params

	var body PutAuthPasswortJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutAuthPasswort(ctx, request.(PutAuthPasswortRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutAuthPasswort")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutAuthPasswortResponseObject); ok {
		if err := validResponse.VisitPutAuthPasswortResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthSetup operation middleware
func (sh *strictHandler) PostAuthSetup(w http.ResponseWriter, r *http.Request) {
	var request PostAuthSetupRequestObject

	var body PostAuthSetupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthSetup(ctx, request.(PostAuthSetupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthSetup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthSetupResponseObject); ok {
		if err := validResponse.VisitPostAuthSetupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchMe operation middleware
func (sh *strictHandler) PatchMe(w http.ResponseWriter, r *http.Request, params PatchMeParams) {
	var request PatchMeRequestObject

	request.Params = params

	var body PatchMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchMe(ctx, request.(PatchMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchMeResponseObject); ok {
		if err := validResponse.VisitPatchMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMeSessions operation middleware
func (sh *strictHandler) GetMeSessions(w http.ResponseWriter, r *http.Request) {
	var request GetMeSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMeSessions(ctx, request.(GetMeSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMeSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeSessionsResponseObject); ok {
		if err := validResponse.VisitGetMeSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMeSession operation middleware
func (sh *strictHandler) DeleteMeSession(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteMeSessionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMeSession(ctx, request.(DeleteMeSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMeSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteMeSessionResponseObject); ok {
		if err := validResponse.VisitDeleteMeSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
