// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abrechnung.sql

package sqlitedb

import (
	"context"
	"time"
)

const claimVorschuss = `-- name: ClaimVorschuss :one
UPDATE vorschuss SET
  abrechnung_id = ?1,
  geaendert_am = ?2,
  version = version + 1
WHERE id = ?3 AND nutzer_id = ?4 AND abrechnung_id IS NULL
RETURNING id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, abrechnung_id, erstellt_am, geaendert_am, version
`

type ClaimVorschussParams struct {
	AbrechnungID *string
	GeaendertAm  time.Time
	ID           string
	NutzerID     string
}

func (q *Queries) ClaimVorschuss(ctx context.Context, arg ClaimVorschussParams) (Vorschuss, error) {
	row := q.db.QueryRowContext(ctx, claimVorschuss,
		arg.AbrechnungID,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
	)
	var i Vorschuss
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Datum,
		&i.Betrag,
		&i.Notiz,
		&i.AbrechnungID,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const deleteAbrechnungEntwurf = `-- name: DeleteAbrechnungEntwurf :execrows
DELETE FROM abrechnung
WHERE id = ?1 AND nutzer_id = ?2
  AND status = 'entwurf' AND aktuelle_export_version = 0 AND einreichung_laeuft = FALSE
`

type DeleteAbrechnungEntwurfParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteAbrechnungEntwurf(ctx context.Context, arg DeleteAbrechnungEntwurfParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAbrechnungEntwurf, arg.ID, arg.NutzerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAbrechnungReisen = `-- name: DeleteAbrechnungReisen :exec
DELETE FROM abrechnung_reise WHERE abrechnung_id = ?1
`

func (q *Queries) DeleteAbrechnungReisen(ctx context.Context, abrechnungID string) error {
	_, err := q.db.ExecContext(ctx, deleteAbrechnungReisen, abrechnungID)
	return err
}

const failExportRow = `-- name: FailExportRow :exec
UPDATE export SET status = 'fehlgeschlagen', fehler = ?1
WHERE id = ?2 AND status = 'in_erstellung'
`

type FailExportRowParams struct {
	Fehler *string
	ID     string
}

func (q *Queries) FailExportRow(ctx context.Context, arg FailExportRowParams) error {
	_, err := q.db.ExecContext(ctx, failExportRow, arg.Fehler, arg.ID)
	return err
}

const finishEinreichung = `-- name: FinishEinreichung :one
UPDATE abrechnung SET
  status = 'eingereicht',
  eingereicht_am = ?1,
  aktuelle_export_version = ?2,
  einreichung_laeuft = FALSE,
  einreichung_fehler = NULL,
  geaendert_am = ?3,
  version = version + 1
WHERE id = ?4 AND einreichung_laeuft = TRUE
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type FinishEinreichungParams struct {
	EingereichtAm         *time.Time
	AktuelleExportVersion int64
	GeaendertAm           time.Time
	ID                    string
}

func (q *Queries) FinishEinreichung(ctx context.Context, arg FinishEinreichungParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, finishEinreichung,
		arg.EingereichtAm,
		arg.AktuelleExportVersion,
		arg.GeaendertAm,
		arg.ID,
	)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const finishExportRow = `-- name: FinishExportRow :one
UPDATE export SET
  status = 'fertig',
  pdf_schluessel = ?1,
  pdf_sha256 = ?2,
  zip_schluessel = ?3,
  zip_sha256 = ?4,
  snapshot = ?5
WHERE id = ?6 AND status = 'in_erstellung'
RETURNING id, abrechnung_id, nutzer_id, version, anlass, erstellt_am, pdf_schluessel, pdf_sha256, zip_schluessel, zip_sha256, snapshot, ersetzt_durch_version, status, fehler
`

type FinishExportRowParams struct {
	PdfSchluessel *string
	PdfSha256     *string
	ZipSchluessel *string
	ZipSha256     *string
	Snapshot      string
	ID            string
}

func (q *Queries) FinishExportRow(ctx context.Context, arg FinishExportRowParams) (Export, error) {
	row := q.db.QueryRowContext(ctx, finishExportRow,
		arg.PdfSchluessel,
		arg.PdfSha256,
		arg.ZipSchluessel,
		arg.ZipSha256,
		arg.Snapshot,
		arg.ID,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.AbrechnungID,
		&i.NutzerID,
		&i.Version,
		&i.Anlass,
		&i.ErstelltAm,
		&i.PdfSchluessel,
		&i.PdfSha256,
		&i.ZipSchluessel,
		&i.ZipSha256,
		&i.Snapshot,
		&i.ErsetztDurchVersion,
		&i.Status,
		&i.Fehler,
	)
	return i, err
}

const getAbrechnung = `-- name: GetAbrechnung :one
SELECT id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version FROM abrechnung
WHERE id = ?1 AND nutzer_id = ?2
`

type GetAbrechnungParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetAbrechnung(ctx context.Context, arg GetAbrechnungParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, getAbrechnung, arg.ID, arg.NutzerID)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getAbrechnungByID = `-- name: GetAbrechnungByID :one
SELECT id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version FROM abrechnung
WHERE id = ?1
`

func (q *Queries) GetAbrechnungByID(ctx context.Context, id string) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, getAbrechnungByID, id)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getExport = `-- name: GetExport :one
SELECT id, abrechnung_id, nutzer_id, version, anlass, erstellt_am, pdf_schluessel, pdf_sha256, zip_schluessel, zip_sha256, snapshot, ersetzt_durch_version, status, fehler FROM export
WHERE id = ?1 AND nutzer_id = ?2
`

type GetExportParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetExport(ctx context.Context, arg GetExportParams) (Export, error) {
	row := q.db.QueryRowContext(ctx, getExport, arg.ID, arg.NutzerID)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.AbrechnungID,
		&i.NutzerID,
		&i.Version,
		&i.Anlass,
		&i.ErstelltAm,
		&i.PdfSchluessel,
		&i.PdfSha256,
		&i.ZipSchluessel,
		&i.ZipSha256,
		&i.Snapshot,
		&i.ErsetztDurchVersion,
		&i.Status,
		&i.Fehler,
	)
	return i, err
}

const getExportByID = `-- name: GetExportByID :one
SELECT id, abrechnung_id, nutzer_id, version, anlass, erstellt_am, pdf_schluessel, pdf_sha256, zip_schluessel, zip_sha256, snapshot, ersetzt_durch_version, status, fehler FROM export
WHERE id = ?1
`

func (q *Queries) GetExportByID(ctx context.Context, id string) (Export, error) {
	row := q.db.QueryRowContext(ctx, getExportByID, id)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.AbrechnungID,
		&i.NutzerID,
		&i.Version,
		&i.Anlass,
		&i.ErstelltAm,
		&i.PdfSchluessel,
		&i.PdfSha256,
		&i.ZipSchluessel,
		&i.ZipSha256,
		&i.Snapshot,
		&i.ErsetztDurchVersion,
		&i.Status,
		&i.Fehler,
	)
	return i, err
}

const insertAbrechnung = `-- name: InsertAbrechnung :one
INSERT INTO abrechnung (
  id, nutzer_id, arbeitgeber_id, zeitraum_art, von, bis, titel, status, export_sprache,
  quittierte_warnungen, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, 'entwurf', ?8,
  '[]', ?9, ?10, 1
)
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type InsertAbrechnungParams struct {
	ID            string
	NutzerID      string
	ArbeitgeberID string
	ZeitraumArt   string
	Von           string
	Bis           string
	Titel         string
	ExportSprache string
	ErstelltAm    time.Time
	GeaendertAm   time.Time
}

func (q *Queries) InsertAbrechnung(ctx context.Context, arg InsertAbrechnungParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, insertAbrechnung,
		arg.ID,
		arg.NutzerID,
		arg.ArbeitgeberID,
		arg.ZeitraumArt,
		arg.Von,
		arg.Bis,
		arg.Titel,
		arg.ExportSprache,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertAbrechnungReise = `-- name: InsertAbrechnungReise :exec
INSERT INTO abrechnung_reise (abrechnung_id, reise_id)
VALUES (?1, ?2)
`

type InsertAbrechnungReiseParams struct {
	AbrechnungID string
	ReiseID      string
}

func (q *Queries) InsertAbrechnungReise(ctx context.Context, arg InsertAbrechnungReiseParams) error {
	_, err := q.db.ExecContext(ctx, insertAbrechnungReise, arg.AbrechnungID, arg.ReiseID)
	return err
}

const insertExport = `-- name: InsertExport :one
INSERT INTO export (
  id, abrechnung_id, nutzer_id, version, anlass, erstellt_am, snapshot, status
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, 'in_erstellung'
)
RETURNING id, abrechnung_id, nutzer_id, version, anlass, erstellt_am, pdf_schluessel, pdf_sha256, zip_schluessel, zip_sha256, snapshot, ersetzt_durch_version, status, fehler
`

type InsertExportParams struct {
	ID           string
	AbrechnungID string
	NutzerID     string
	Version      int64
	Anlass       string
	ErstelltAm   time.Time
	Snapshot     string
}

func (q *Queries) InsertExport(ctx context.Context, arg InsertExportParams) (Export, error) {
	row := q.db.QueryRowContext(ctx, insertExport,
		arg.ID,
		arg.AbrechnungID,
		arg.NutzerID,
		arg.Version,
		arg.Anlass,
		arg.ErstelltAm,
		arg.Snapshot,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.AbrechnungID,
		&i.NutzerID,
		&i.Version,
		&i.Anlass,
		&i.ErstelltAm,
		&i.PdfSchluessel,
		&i.PdfSha256,
		&i.ZipSchluessel,
		&i.ZipSha256,
		&i.Snapshot,
		&i.ErsetztDurchVersion,
		&i.Status,
		&i.Fehler,
	)
	return i, err
}

const listAbrechnungReiseIDs = `-- name: ListAbrechnungReiseIDs :many
SELECT reise_id FROM abrechnung_reise
WHERE abrechnung_id = ?1
ORDER BY reise_id
`

func (q *Queries) ListAbrechnungReiseIDs(ctx context.Context, abrechnungID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAbrechnungReiseIDs, abrechnungID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var reise_id string
		if err := rows.Scan(&reise_id); err != nil {
			return nil, err
		}
		items = append(items, reise_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAbrechnungen = `-- name: ListAbrechnungen :many
SELECT id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version FROM abrechnung
WHERE nutzer_id = ?1
  AND (?2 IS NULL OR id < ?2)
ORDER BY id DESC
LIMIT ?3
`

type ListAbrechnungenParams struct {
	NutzerID string
	Cursor   interface{}
	LimitN   int64
}

func (q *Queries) ListAbrechnungen(ctx context.Context, arg ListAbrechnungenParams) ([]Abrechnung, error) {
	rows, err := q.db.QueryContext(ctx, listAbrechnungen, arg.NutzerID, arg.Cursor, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Abrechnung
	for rows.Next() {
		var i Abrechnung
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ArbeitgeberID,
			&i.Abrechnungsnummer,
			&i.ZeitraumArt,
			&i.Von,
			&i.Bis,
			&i.Titel,
			&i.Status,
			&i.EingereichtAm,
			&i.BezahltAm,
			&i.BezahltVermerk,
			&i.ExportSprache,
			&i.AktuelleExportVersion,
			&i.EinreichungLaeuft,
			&i.EinreichungFehler,
			&i.QuittierteWarnungen,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExporte = `-- name: ListExporte :many
SELECT id, abrechnung_id, nutzer_id, version, anlass, erstellt_am, pdf_schluessel, pdf_sha256, zip_schluessel, zip_sha256, snapshot, ersetzt_durch_version, status, fehler FROM export
WHERE abrechnung_id = ?1 AND nutzer_id = ?2
ORDER BY version
`

type ListExporteParams struct {
	AbrechnungID string
	NutzerID     string
}

func (q *Queries) ListExporte(ctx context.Context, arg ListExporteParams) ([]Export, error) {
	rows, err := q.db.QueryContext(ctx, listExporte, arg.AbrechnungID, arg.NutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Export
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.AbrechnungID,
			&i.NutzerID,
			&i.Version,
			&i.Anlass,
			&i.ErstelltAm,
			&i.PdfSchluessel,
			&i.PdfSha256,
			&i.ZipSchluessel,
			&i.ZipSha256,
			&i.Snapshot,
			&i.ErsetztDurchVersion,
			&i.Status,
			&i.Fehler,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReisenByArbeitgeberStatus = `-- name: ListReisenByArbeitgeberStatus :many
SELECT id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone, notiz, vorlage_id, status, erstellt_am, geaendert_am, version FROM reise
WHERE nutzer_id = ?1
  AND arbeitgeber_id = ?2
  AND status = ?3
ORDER BY ende, id
`

type ListReisenByArbeitgeberStatusParams struct {
	NutzerID      string
	ArbeitgeberID string
	Status        string
}

func (q *Queries) ListReisenByArbeitgeberStatus(ctx context.Context, arg ListReisenByArbeitgeberStatusParams) ([]Reise, error) {
	rows, err := q.db.QueryContext(ctx, listReisenByArbeitgeberStatus, arg.NutzerID, arg.ArbeitgeberID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reise
	for rows.Next() {
		var i Reise
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ArbeitgeberID,
			&i.Anlass,
			&i.Projekt,
			&i.Beginn,
			&i.BeginnZone,
			&i.Ende,
			&i.EndeZone,
			&i.Notiz,
			&i.VorlageID,
			&i.Status,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVorschuesseByArbeitgeber = `-- name: ListVorschuesseByArbeitgeber :many
SELECT id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, abrechnung_id, erstellt_am, geaendert_am, version FROM vorschuss
WHERE nutzer_id = ?1 AND arbeitgeber_id = ?2
ORDER BY datum, id
`

type ListVorschuesseByArbeitgeberParams struct {
	NutzerID      string
	ArbeitgeberID string
}

func (q *Queries) ListVorschuesseByArbeitgeber(ctx context.Context, arg ListVorschuesseByArbeitgeberParams) ([]Vorschuss, error) {
	rows, err := q.db.QueryContext(ctx, listVorschuesseByArbeitgeber, arg.NutzerID, arg.ArbeitgeberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vorschuss
	for rows.Next() {
		var i Vorschuss
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ArbeitgeberID,
			&i.Datum,
			&i.Betrag,
			&i.Notiz,
			&i.AbrechnungID,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVorschuesseOfAbrechnung = `-- name: ListVorschuesseOfAbrechnung :many
SELECT id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, abrechnung_id, erstellt_am, geaendert_am, version FROM vorschuss
WHERE nutzer_id = ?1 AND abrechnung_id = ?2
ORDER BY datum, id
`

type ListVorschuesseOfAbrechnungParams struct {
	NutzerID     string
	AbrechnungID *string
}

func (q *Queries) ListVorschuesseOfAbrechnung(ctx context.Context, arg ListVorschuesseOfAbrechnungParams) ([]Vorschuss, error) {
	rows, err := q.db.QueryContext(ctx, listVorschuesseOfAbrechnung, arg.NutzerID, arg.AbrechnungID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vorschuss
	for rows.Next() {
		var i Vorschuss
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ArbeitgeberID,
			&i.Datum,
			&i.Betrag,
			&i.Notiz,
			&i.AbrechnungID,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBezahlt = `-- name: MarkBezahlt :one
UPDATE abrechnung SET
  status = 'bezahlt',
  bezahlt_am = ?1,
  bezahlt_vermerk = ?2,
  geaendert_am = ?3,
  version = version + 1
WHERE id = ?4 AND nutzer_id = ?5 AND version = ?6
  AND status = 'eingereicht'
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type MarkBezahltParams struct {
	BezahltAm      *string
	BezahltVermerk *string
	GeaendertAm    time.Time
	ID             string
	NutzerID       string
	Version        int64
}

func (q *Queries) MarkBezahlt(ctx context.Context, arg MarkBezahltParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, markBezahlt,
		arg.BezahltAm,
		arg.BezahltVermerk,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const markBezahltZurueck = `-- name: MarkBezahltZurueck :one
UPDATE abrechnung SET
  status = 'eingereicht',
  bezahlt_am = NULL,
  bezahlt_vermerk = NULL,
  geaendert_am = ?1,
  version = version + 1
WHERE id = ?2 AND nutzer_id = ?3 AND version = ?4
  AND status = 'bezahlt'
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type MarkBezahltZurueckParams struct {
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) MarkBezahltZurueck(ctx context.Context, arg MarkBezahltZurueckParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, markBezahltZurueck,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const markEinreichung = `-- name: MarkEinreichung :one
UPDATE abrechnung SET
  abrechnungsnummer = ?1,
  einreichung_laeuft = TRUE,
  einreichung_fehler = NULL,
  quittierte_warnungen = ?2,
  geaendert_am = ?3,
  version = version + 1
WHERE id = ?4 AND nutzer_id = ?5 AND version = ?6
  AND status = 'entwurf' AND einreichung_laeuft = FALSE
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type MarkEinreichungParams struct {
	Abrechnungsnummer   *string
	QuittierteWarnungen string
	GeaendertAm         time.Time
	ID                  string
	NutzerID            string
	Version             int64
}

func (q *Queries) MarkEinreichung(ctx context.Context, arg MarkEinreichungParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, markEinreichung,
		arg.Abrechnungsnummer,
		arg.QuittierteWarnungen,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const markEntsperrt = `-- name: MarkEntsperrt :one
UPDATE abrechnung SET
  status = 'entwurf',
  geaendert_am = ?1,
  version = version + 1
WHERE id = ?2 AND nutzer_id = ?3 AND version = ?4
  AND status = 'eingereicht'
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type MarkEntsperrtParams struct {
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) MarkEntsperrt(ctx context.Context, arg MarkEntsperrtParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, markEntsperrt,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const markExportErsetzt = `-- name: MarkExportErsetzt :exec
UPDATE export SET ersetzt_durch_version = ?1
WHERE abrechnung_id = ?2
  AND status = 'fertig'
  AND id != ?3
  AND ersetzt_durch_version IS NULL
`

type MarkExportErsetztParams struct {
	ErsetztDurchVersion *int64
	AbrechnungID        string
	ID                  string
}

func (q *Queries) MarkExportErsetzt(ctx context.Context, arg MarkExportErsetztParams) error {
	_, err := q.db.ExecContext(ctx, markExportErsetzt, arg.ErsetztDurchVersion, arg.AbrechnungID, arg.ID)
	return err
}

const maxExportVersion = `-- name: MaxExportVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS BIGINT) AS version
FROM export
WHERE abrechnung_id = ?1
`

func (q *Queries) MaxExportVersion(ctx context.Context, abrechnungID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxExportVersion, abrechnungID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const nextAbrechnungsnummer = `-- name: NextAbrechnungsnummer :one
INSERT INTO abrechnungsnummer_folge (nutzer_id, arbeitgeber_id, jahr, naechste)
VALUES (?1, ?2, ?3, 1)
ON CONFLICT (nutzer_id, arbeitgeber_id, jahr) DO UPDATE SET
  naechste = abrechnungsnummer_folge.naechste + 1
RETURNING naechste
`

type NextAbrechnungsnummerParams struct {
	NutzerID      string
	ArbeitgeberID string
	Jahr          int64
}

func (q *Queries) NextAbrechnungsnummer(ctx context.Context, arg NextAbrechnungsnummerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAbrechnungsnummer, arg.NutzerID, arg.ArbeitgeberID, arg.Jahr)
	var naechste int64
	err := row.Scan(&naechste)
	return naechste, err
}

const releaseVorschuesse = `-- name: ReleaseVorschuesse :exec
UPDATE vorschuss SET
  abrechnung_id = NULL,
  geaendert_am = ?1,
  version = version + 1
WHERE nutzer_id = ?2 AND abrechnung_id = ?3
`

type ReleaseVorschuesseParams struct {
	GeaendertAm  time.Time
	NutzerID     string
	AbrechnungID *string
}

func (q *Queries) ReleaseVorschuesse(ctx context.Context, arg ReleaseVorschuesseParams) error {
	_, err := q.db.ExecContext(ctx, releaseVorschuesse, arg.GeaendertAm, arg.NutzerID, arg.AbrechnungID)
	return err
}

const rollbackEinreichung = `-- name: RollbackEinreichung :one
UPDATE abrechnung SET
  einreichung_laeuft = FALSE,
  einreichung_fehler = ?1,
  geaendert_am = ?2,
  version = version + 1
WHERE id = ?3 AND einreichung_laeuft = TRUE
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type RollbackEinreichungParams struct {
	EinreichungFehler *string
	GeaendertAm       time.Time
	ID                string
}

func (q *Queries) RollbackEinreichung(ctx context.Context, arg RollbackEinreichungParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, rollbackEinreichung, arg.EinreichungFehler, arg.GeaendertAm, arg.ID)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const setReiseStatus = `-- name: SetReiseStatus :exec
UPDATE reise SET
  status = ?1,
  geaendert_am = ?2,
  version = version + 1
WHERE id = ?3 AND nutzer_id = ?4
`

type SetReiseStatusParams struct {
	Status      string
	GeaendertAm time.Time
	ID          string
	NutzerID    string
}

func (q *Queries) SetReiseStatus(ctx context.Context, arg SetReiseStatusParams) error {
	_, err := q.db.ExecContext(ctx, setReiseStatus,
		arg.Status,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
	)
	return err
}

const updateAbrechnungKopf = `-- name: UpdateAbrechnungKopf :one
UPDATE abrechnung SET
  titel = ?1,
  export_sprache = ?2,
  geaendert_am = ?3,
  version = version + 1
WHERE id = ?4 AND nutzer_id = ?5 AND version = ?6
  AND status = 'entwurf' AND einreichung_laeuft = FALSE
RETURNING id, nutzer_id, arbeitgeber_id, abrechnungsnummer, zeitraum_art, von, bis, titel, status, eingereicht_am, bezahlt_am, bezahlt_vermerk, export_sprache, aktuelle_export_version, einreichung_laeuft, einreichung_fehler, quittierte_warnungen, erstellt_am, geaendert_am, version
`

type UpdateAbrechnungKopfParams struct {
	Titel         string
	ExportSprache string
	GeaendertAm   time.Time
	ID            string
	NutzerID      string
	Version       int64
}

func (q *Queries) UpdateAbrechnungKopf(ctx context.Context, arg UpdateAbrechnungKopfParams) (Abrechnung, error) {
	row := q.db.QueryRowContext(ctx, updateAbrechnungKopf,
		arg.Titel,
		arg.ExportSprache,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Abrechnung
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Abrechnungsnummer,
		&i.ZeitraumArt,
		&i.Von,
		&i.Bis,
		&i.Titel,
		&i.Status,
		&i.EingereichtAm,
		&i.BezahltAm,
		&i.BezahltVermerk,
		&i.ExportSprache,
		&i.AktuelleExportVersion,
		&i.EinreichungLaeuft,
		&i.EinreichungFehler,
		&i.QuittierteWarnungen,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}
