// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arbeitgeber.sql

package sqlitedb

import (
	"context"
	"time"
)

const clearAndereStandards = `-- name: ClearAndereStandards :exec
UPDATE arbeitgeber SET
  ist_standard = FALSE,
  geaendert_am = ?1,
  version = version + 1
WHERE nutzer_id = ?2
  AND ist_standard = TRUE
  AND archiviert = FALSE
  AND id <> ?3
`

type ClearAndereStandardsParams struct {
	GeaendertAm time.Time
	NutzerID    string
	ID          string
}

func (q *Queries) ClearAndereStandards(ctx context.Context, arg ClearAndereStandardsParams) error {
	_, err := q.db.ExecContext(ctx, clearAndereStandards, arg.GeaendertAm, arg.NutzerID, arg.ID)
	return err
}

const countAktiveArbeitgeber = `-- name: CountAktiveArbeitgeber :one
SELECT CAST(COUNT(*) AS BIGINT) FROM arbeitgeber
WHERE nutzer_id = ?1 AND archiviert = FALSE
`

func (q *Queries) CountAktiveArbeitgeber(ctx context.Context, nutzerID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAktiveArbeitgeber, nutzerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const firstOtherAktiverArbeitgeber = `-- name: FirstOtherAktiverArbeitgeber :one
SELECT id, nutzer_id, name, anschrift, ust_id, steuernummer, logo_datei_id, ist_standard, konstellation, abrechnungsnummer_praefix, archiviert, erstellt_am, geaendert_am, version FROM arbeitgeber
WHERE nutzer_id = ?1 AND archiviert = FALSE AND id <> ?2
ORDER BY erstellt_am, id
LIMIT 1
`

type FirstOtherAktiverArbeitgeberParams struct {
	NutzerID string
	ID       string
}

func (q *Queries) FirstOtherAktiverArbeitgeber(ctx context.Context, arg FirstOtherAktiverArbeitgeberParams) (Arbeitgeber, error) {
	row := q.db.QueryRowContext(ctx, firstOtherAktiverArbeitgeber, arg.NutzerID, arg.ID)
	var i Arbeitgeber
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Name,
		&i.Anschrift,
		&i.UstID,
		&i.Steuernummer,
		&i.LogoDateiID,
		&i.IstStandard,
		&i.Konstellation,
		&i.AbrechnungsnummerPraefix,
		&i.Archiviert,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getArbeitgeber = `-- name: GetArbeitgeber :one
SELECT id, nutzer_id, name, anschrift, ust_id, steuernummer, logo_datei_id, ist_standard, konstellation, abrechnungsnummer_praefix, archiviert, erstellt_am, geaendert_am, version FROM arbeitgeber
WHERE id = ?1 AND nutzer_id = ?2
`

type GetArbeitgeberParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetArbeitgeber(ctx context.Context, arg GetArbeitgeberParams) (Arbeitgeber, error) {
	row := q.db.QueryRowContext(ctx, getArbeitgeber, arg.ID, arg.NutzerID)
	var i Arbeitgeber
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Name,
		&i.Anschrift,
		&i.UstID,
		&i.Steuernummer,
		&i.LogoDateiID,
		&i.IstStandard,
		&i.Konstellation,
		&i.AbrechnungsnummerPraefix,
		&i.Archiviert,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getDatei = `-- name: GetDatei :one
SELECT id, nutzer_id, mime, bytes, sha256, speicher_schluessel, erstellt_am FROM datei WHERE id = ?1 AND nutzer_id = ?2
`

type GetDateiParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetDatei(ctx context.Context, arg GetDateiParams) (Datei, error) {
	row := q.db.QueryRowContext(ctx, getDatei, arg.ID, arg.NutzerID)
	var i Datei
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Mime,
		&i.Bytes,
		&i.Sha256,
		&i.SpeicherSchluessel,
		&i.ErstelltAm,
	)
	return i, err
}

const insertArbeitgeber = `-- name: InsertArbeitgeber :one
INSERT INTO arbeitgeber (
  id, nutzer_id, name, anschrift, ust_id, steuernummer, logo_datei_id,
  ist_standard, konstellation, abrechnungsnummer_praefix, archiviert,
  erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10,
  ?11, ?12, ?13, 1
)
RETURNING id, nutzer_id, name, anschrift, ust_id, steuernummer, logo_datei_id, ist_standard, konstellation, abrechnungsnummer_praefix, archiviert, erstellt_am, geaendert_am, version
`

type InsertArbeitgeberParams struct {
	ID                       string
	NutzerID                 string
	Name                     string
	Anschrift                string
	UstID                    *string
	Steuernummer             *string
	LogoDateiID              *string
	IstStandard              bool
	Konstellation            string
	AbrechnungsnummerPraefix string
	Archiviert               bool
	ErstelltAm               time.Time
	GeaendertAm              time.Time
}

func (q *Queries) InsertArbeitgeber(ctx context.Context, arg InsertArbeitgeberParams) (Arbeitgeber, error) {
	row := q.db.QueryRowContext(ctx, insertArbeitgeber,
		arg.ID,
		arg.NutzerID,
		arg.Name,
		arg.Anschrift,
		arg.UstID,
		arg.Steuernummer,
		arg.LogoDateiID,
		arg.IstStandard,
		arg.Konstellation,
		arg.AbrechnungsnummerPraefix,
		arg.Archiviert,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Arbeitgeber
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Name,
		&i.Anschrift,
		&i.UstID,
		&i.Steuernummer,
		&i.LogoDateiID,
		&i.IstStandard,
		&i.Konstellation,
		&i.AbrechnungsnummerPraefix,
		&i.Archiviert,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertDatei = `-- name: InsertDatei :one
INSERT INTO datei (
  id, nutzer_id, mime, bytes, sha256, speicher_schluessel, erstellt_am
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
RETURNING id, nutzer_id, mime, bytes, sha256, speicher_schluessel, erstellt_am
`

type InsertDateiParams struct {
	ID                 string
	NutzerID           string
	Mime               string
	Bytes              int64
	Sha256             string
	SpeicherSchluessel string
	ErstelltAm         time.Time
}

func (q *Queries) InsertDatei(ctx context.Context, arg InsertDateiParams) (Datei, error) {
	row := q.db.QueryRowContext(ctx, insertDatei,
		arg.ID,
		arg.NutzerID,
		arg.Mime,
		arg.Bytes,
		arg.Sha256,
		arg.SpeicherSchluessel,
		arg.ErstelltAm,
	)
	var i Datei
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Mime,
		&i.Bytes,
		&i.Sha256,
		&i.SpeicherSchluessel,
		&i.ErstelltAm,
	)
	return i, err
}

const listArbeitgeber = `-- name: ListArbeitgeber :many
SELECT id, nutzer_id, name, anschrift, ust_id, steuernummer, logo_datei_id, ist_standard, konstellation, abrechnungsnummer_praefix, archiviert, erstellt_am, geaendert_am, version FROM arbeitgeber
WHERE nutzer_id = ?1
  AND (?2 IS NULL OR id > ?2)
ORDER BY id
LIMIT ?3
`

type ListArbeitgeberParams struct {
	NutzerID string
	Cursor   interface{}
	LimitN   int64
}

func (q *Queries) ListArbeitgeber(ctx context.Context, arg ListArbeitgeberParams) ([]Arbeitgeber, error) {
	rows, err := q.db.QueryContext(ctx, listArbeitgeber, arg.NutzerID, arg.Cursor, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Arbeitgeber
	for rows.Next() {
		var i Arbeitgeber
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Name,
			&i.Anschrift,
			&i.UstID,
			&i.Steuernummer,
			&i.LogoDateiID,
			&i.IstStandard,
			&i.Konstellation,
			&i.AbrechnungsnummerPraefix,
			&i.Archiviert,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArbeitgeber = `-- name: UpdateArbeitgeber :one
UPDATE arbeitgeber SET
  name = ?1,
  anschrift = ?2,
  ust_id = ?3,
  steuernummer = ?4,
  logo_datei_id = ?5,
  ist_standard = ?6,
  konstellation = ?7,
  abrechnungsnummer_praefix = ?8,
  archiviert = ?9,
  geaendert_am = ?10,
  version = version + 1
WHERE id = ?11 AND nutzer_id = ?12 AND version = ?13
RETURNING id, nutzer_id, name, anschrift, ust_id, steuernummer, logo_datei_id, ist_standard, konstellation, abrechnungsnummer_praefix, archiviert, erstellt_am, geaendert_am, version
`

type UpdateArbeitgeberParams struct {
	Name                     string
	Anschrift                string
	UstID                    *string
	Steuernummer             *string
	LogoDateiID              *string
	IstStandard              bool
	Konstellation            string
	AbrechnungsnummerPraefix string
	Archiviert               bool
	GeaendertAm              time.Time
	ID                       string
	NutzerID                 string
	Version                  int64
}

func (q *Queries) UpdateArbeitgeber(ctx context.Context, arg UpdateArbeitgeberParams) (Arbeitgeber, error) {
	row := q.db.QueryRowContext(ctx, updateArbeitgeber,
		arg.Name,
		arg.Anschrift,
		arg.UstID,
		arg.Steuernummer,
		arg.LogoDateiID,
		arg.IstStandard,
		arg.Konstellation,
		arg.AbrechnungsnummerPraefix,
		arg.Archiviert,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Arbeitgeber
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Name,
		&i.Anschrift,
		&i.UstID,
		&i.Steuernummer,
		&i.LogoDateiID,
		&i.IstStandard,
		&i.Konstellation,
		&i.AbrechnungsnummerPraefix,
		&i.Archiviert,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}
