// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlitedb

import (
	"context"
	"time"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_ereignis (
  id, zeitpunkt, akteur_nutzer_id, akteur_art, aktion, objekt_typ, objekt_id,
  vorher, nachher, grund, ip, vorgaenger_hash, hash
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11, ?12, ?13
)
`

type InsertAuditParams struct {
	ID             string
	Zeitpunkt      time.Time
	AkteurNutzerID *string
	AkteurArt      string
	Aktion         string
	ObjektTyp      string
	ObjektID       string
	Vorher         *string
	Nachher        *string
	Grund          *string
	Ip             *string
	VorgaengerHash string
	Hash           string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.ID,
		arg.Zeitpunkt,
		arg.AkteurNutzerID,
		arg.AkteurArt,
		arg.Aktion,
		arg.ObjektTyp,
		arg.ObjektID,
		arg.Vorher,
		arg.Nachher,
		arg.Grund,
		arg.Ip,
		arg.VorgaengerHash,
		arg.Hash,
	)
	return err
}

const lastAuditHash = `-- name: LastAuditHash :one
SELECT hash FROM audit_ereignis ORDER BY id DESC LIMIT 1
`

func (q *Queries) LastAuditHash(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, lastAuditHash)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, zeitpunkt, akteur_nutzer_id, akteur_art, aktion, objekt_typ, objekt_id, vorher, nachher, grund, ip, vorgaenger_hash, hash FROM audit_ereignis ORDER BY id ASC
`

func (q *Queries) ListAudit(ctx context.Context) ([]AuditEreigni, error) {
	rows, err := q.db.QueryContext(ctx, listAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEreigni
	for rows.Next() {
		var i AuditEreigni
		if err := rows.Scan(
			&i.ID,
			&i.Zeitpunkt,
			&i.AkteurNutzerID,
			&i.AkteurArt,
			&i.Aktion,
			&i.ObjektTyp,
			&i.ObjektID,
			&i.Vorher,
			&i.Nachher,
			&i.Grund,
			&i.Ip,
			&i.VorgaengerHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
