// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aufbewahrung.sql

package sqlitedb

import (
	"context"
	"time"
)

const countDoneJobsSince = `-- name: CountDoneJobsSince :one
SELECT CAST(COUNT(*) AS BIGINT) AS n
FROM job
WHERE art = ?1 AND status = 'done' AND geaendert_am >= ?2
`

type CountDoneJobsSinceParams struct {
	Art  string
	Seit time.Time
}

func (q *Queries) CountDoneJobsSince(ctx context.Context, arg CountDoneJobsSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDoneJobsSince, arg.Art, arg.Seit)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countOpenJobsByArt = `-- name: CountOpenJobsByArt :one
SELECT CAST(COUNT(*) AS BIGINT) AS n
FROM job
WHERE art = ?1 AND status IN ('pending', 'running')
`

func (q *Queries) CountOpenJobsByArt(ctx context.Context, art string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenJobsByArt, art)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteBelegdateienByBeleg = `-- name: DeleteBelegdateienByBeleg :exec
DELETE FROM belegdatei WHERE beleg_id = ?1
`

func (q *Queries) DeleteBelegdateienByBeleg(ctx context.Context, belegID string) error {
	_, err := q.db.ExecContext(ctx, deleteBelegdateienByBeleg, belegID)
	return err
}

const deleteBelegtexteByBeleg = `-- name: DeleteBelegtexteByBeleg :exec
DELETE FROM belegtext WHERE beleg_id = ?1
`

func (q *Queries) DeleteBelegtexteByBeleg(ctx context.Context, belegID string) error {
	_, err := q.db.ExecContext(ctx, deleteBelegtexteByBeleg, belegID)
	return err
}

const extendBelegFrist = `-- name: ExtendBelegFrist :exec
UPDATE beleg SET
  aufbewahren_bis = ?1,
  geaendert_am = ?2
WHERE aufbewahren_bis IS NOT NULL
  AND aufbewahren_bis < ?1
  AND id IN (
    SELECT ausgabe_beleg.beleg_id
    FROM ausgabe_beleg
    JOIN ausgabe ON ausgabe.id = ausgabe_beleg.ausgabe_id
    JOIN abrechnung_reise ON abrechnung_reise.reise_id = ausgabe.reise_id
    WHERE abrechnung_reise.abrechnung_id = ?3
  )
`

type ExtendBelegFristParams struct {
	AufbewahrenBis *string
	GeaendertAm    time.Time
	AbrechnungID   string
}

func (q *Queries) ExtendBelegFrist(ctx context.Context, arg ExtendBelegFristParams) error {
	_, err := q.db.ExecContext(ctx, extendBelegFrist, arg.AufbewahrenBis, arg.GeaendertAm, arg.AbrechnungID)
	return err
}

const listRetentionBelege = `-- name: ListRetentionBelege :many
SELECT id, nutzer_id,
  COALESCE(belegnummer, id) AS bezeichnung,
  COALESCE(aufbewahren_bis, '') AS aufbewahren_bis,
  sha256_original,
  inhalt_geloescht_am
FROM beleg
WHERE status IN ('bestaetigt', 'storniert')
  AND aufbewahren_bis IS NOT NULL
ORDER BY aufbewahren_bis, id
`

type ListRetentionBelegeRow struct {
	ID                string
	NutzerID          string
	Bezeichnung       string
	AufbewahrenBis    string
	Sha256Original    string
	InhaltGeloeschtAm *time.Time
}

func (q *Queries) ListRetentionBelege(ctx context.Context) ([]ListRetentionBelegeRow, error) {
	rows, err := q.db.QueryContext(ctx, listRetentionBelege)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetentionBelegeRow
	for rows.Next() {
		var i ListRetentionBelegeRow
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Bezeichnung,
			&i.AufbewahrenBis,
			&i.Sha256Original,
			&i.InhaltGeloeschtAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionExporte = `-- name: ListRetentionExporte :many
SELECT export.id, export.nutzer_id, export.version,
  COALESCE(abrechnung.abrechnungsnummer, export.abrechnung_id) AS bezeichnung,
  COALESCE(export.aufbewahren_bis, '') AS aufbewahren_bis,
  COALESCE(export.pdf_sha256, '') AS sha256,
  export.inhalt_geloescht_am,
  export.pdf_schluessel, export.zip_schluessel
FROM export
JOIN abrechnung ON abrechnung.id = export.abrechnung_id
WHERE export.status = 'fertig'
ORDER BY export.aufbewahren_bis, export.id
`

type ListRetentionExporteRow struct {
	ID                string
	NutzerID          string
	Version           int64
	Bezeichnung       string
	AufbewahrenBis    string
	Sha256            string
	InhaltGeloeschtAm *time.Time
	PdfSchluessel     *string
	ZipSchluessel     *string
}

func (q *Queries) ListRetentionExporte(ctx context.Context) ([]ListRetentionExporteRow, error) {
	rows, err := q.db.QueryContext(ctx, listRetentionExporte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetentionExporteRow
	for rows.Next() {
		var i ListRetentionExporteRow
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Version,
			&i.Bezeichnung,
			&i.AufbewahrenBis,
			&i.Sha256,
			&i.InhaltGeloeschtAm,
			&i.PdfSchluessel,
			&i.ZipSchluessel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBelegInhaltGeloescht = `-- name: MarkBelegInhaltGeloescht :exec
UPDATE beleg SET
  inhalt_geloescht_am = ?1,
  loesch_grund = ?2,
  geaendert_am = ?1,
  version = version + 1
WHERE id = ?3 AND inhalt_geloescht_am IS NULL
`

type MarkBelegInhaltGeloeschtParams struct {
	Jetzt *time.Time
	Grund *string
	ID    string
}

func (q *Queries) MarkBelegInhaltGeloescht(ctx context.Context, arg MarkBelegInhaltGeloeschtParams) error {
	_, err := q.db.ExecContext(ctx, markBelegInhaltGeloescht, arg.Jetzt, arg.Grund, arg.ID)
	return err
}

const markExportInhaltGeloescht = `-- name: MarkExportInhaltGeloescht :exec
UPDATE export SET
  inhalt_geloescht_am = ?1,
  loesch_grund = ?2,
  snapshot = '{"geloescht":true}',
  pdf_schluessel = NULL,
  zip_schluessel = NULL
WHERE id = ?3 AND inhalt_geloescht_am IS NULL
`

type MarkExportInhaltGeloeschtParams struct {
	Jetzt *time.Time
	Grund *string
	ID    string
}

func (q *Queries) MarkExportInhaltGeloescht(ctx context.Context, arg MarkExportInhaltGeloeschtParams) error {
	_, err := q.db.ExecContext(ctx, markExportInhaltGeloescht, arg.Jetzt, arg.Grund, arg.ID)
	return err
}

const maxBelegFristOfAbrechnung = `-- name: MaxBelegFristOfAbrechnung :one
SELECT CAST(COALESCE(MAX(beleg.aufbewahren_bis), '') AS TEXT) AS bis
FROM beleg
JOIN ausgabe_beleg ON ausgabe_beleg.beleg_id = beleg.id
JOIN ausgabe ON ausgabe.id = ausgabe_beleg.ausgabe_id
JOIN abrechnung_reise ON abrechnung_reise.reise_id = ausgabe.reise_id
WHERE abrechnung_reise.abrechnung_id = ?1
`

func (q *Queries) MaxBelegFristOfAbrechnung(ctx context.Context, abrechnungID string) (string, error) {
	row := q.db.QueryRowContext(ctx, maxBelegFristOfAbrechnung, abrechnungID)
	var bis string
	err := row.Scan(&bis)
	return bis, err
}
