// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ausgabe.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteAusgabe = `-- name: DeleteAusgabe :execrows
DELETE FROM ausgabe
WHERE id = ?1 AND nutzer_id = ?2
`

type DeleteAusgabeParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteAusgabe(ctx context.Context, arg DeleteAusgabeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAusgabe, arg.ID, arg.NutzerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAusgabeBelege = `-- name: DeleteAusgabeBelege :exec
DELETE FROM ausgabe_beleg
WHERE ausgabe_id = ?1
`

func (q *Queries) DeleteAusgabeBelege(ctx context.Context, ausgabeID string) error {
	_, err := q.db.ExecContext(ctx, deleteAusgabeBelege, ausgabeID)
	return err
}

const deleteSteueranteile = `-- name: DeleteSteueranteile :exec
DELETE FROM steueranteil
WHERE ausgabe_id = ?1
`

func (q *Queries) DeleteSteueranteile(ctx context.Context, ausgabeID string) error {
	_, err := q.db.ExecContext(ctx, deleteSteueranteile, ausgabeID)
	return err
}

const deleteVorschussOffen = `-- name: DeleteVorschussOffen :execrows
DELETE FROM vorschuss
WHERE id = ?1 AND nutzer_id = ?2 AND abrechnung_id IS NULL
`

type DeleteVorschussOffenParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteVorschussOffen(ctx context.Context, arg DeleteVorschussOffenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVorschussOffen, arg.ID, arg.NutzerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAusgabe = `-- name: GetAusgabe :one
SELECT id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag, kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber, empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung, tse_beleg, erstellt_am, geaendert_am, version FROM ausgabe
WHERE id = ?1 AND nutzer_id = ?2
`

type GetAusgabeParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetAusgabe(ctx context.Context, arg GetAusgabeParams) (Ausgabe, error) {
	row := q.db.QueryRowContext(ctx, getAusgabe, arg.ID, arg.NutzerID)
	var i Ausgabe
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ReiseID,
		&i.Kostenart,
		&i.Datum,
		&i.Leistender,
		&i.Beschreibung,
		&i.Waehrung,
		&i.Betrag,
		&i.Kurs,
		&i.KursQuelle,
		&i.KursDatum,
		&i.KursGrund,
		&i.BetragEur,
		&i.Rechnungsart,
		&i.RechnungAufArbeitgeber,
		&i.Empfaenger,
		&i.Verkehrsmittel,
		&i.UebernachtungNaechte,
		&i.FruehstueckEnthalten,
		&i.Mahlzeit,
		&i.Bewirtung,
		&i.TseBeleg,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getEigenbeleg = `-- name: GetEigenbeleg :one
SELECT ausgabe_id, grund, zahlungsempfaenger, art, erstellt_am, bestaetigt_am, bestaetigt_von FROM eigenbeleg
WHERE ausgabe_id = ?1
`

func (q *Queries) GetEigenbeleg(ctx context.Context, ausgabeID string) (Eigenbeleg, error) {
	row := q.db.QueryRowContext(ctx, getEigenbeleg, ausgabeID)
	var i Eigenbeleg
	err := row.Scan(
		&i.AusgabeID,
		&i.Grund,
		&i.Zahlungsempfaenger,
		&i.Art,
		&i.ErstelltAm,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
	)
	return i, err
}

const getUstMonatskurs = `-- name: GetUstMonatskurs :one
SELECT jahr, monat, waehrung, kurs, abgerufen_am FROM ust_monatskurs
WHERE jahr = ?1 AND monat = ?2 AND waehrung = ?3
`

type GetUstMonatskursParams struct {
	Jahr     int64
	Monat    int64
	Waehrung string
}

func (q *Queries) GetUstMonatskurs(ctx context.Context, arg GetUstMonatskursParams) (UstMonatskur, error) {
	row := q.db.QueryRowContext(ctx, getUstMonatskurs, arg.Jahr, arg.Monat, arg.Waehrung)
	var i UstMonatskur
	err := row.Scan(
		&i.Jahr,
		&i.Monat,
		&i.Waehrung,
		&i.Kurs,
		&i.AbgerufenAm,
	)
	return i, err
}

const getVorschuss = `-- name: GetVorschuss :one
SELECT id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, abrechnung_id, erstellt_am, geaendert_am, version FROM vorschuss
WHERE id = ?1 AND nutzer_id = ?2
`

type GetVorschussParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetVorschuss(ctx context.Context, arg GetVorschussParams) (Vorschuss, error) {
	row := q.db.QueryRowContext(ctx, getVorschuss, arg.ID, arg.NutzerID)
	var i Vorschuss
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Datum,
		&i.Betrag,
		&i.Notiz,
		&i.AbrechnungID,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertAusgabe = `-- name: InsertAusgabe :one
INSERT INTO ausgabe (
  id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag,
  kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber,
  empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung,
  tse_beleg, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9,
  ?10, ?11, ?12, ?13,
  ?14, ?15, ?16,
  ?17, ?18, ?19,
  ?20, ?21, ?22,
  ?23, ?24, ?25, 1
)
RETURNING id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag, kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber, empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung, tse_beleg, erstellt_am, geaendert_am, version
`

type InsertAusgabeParams struct {
	ID                     string
	NutzerID               string
	ReiseID                string
	Kostenart              string
	Datum                  string
	Leistender             string
	Beschreibung           *string
	Waehrung               string
	Betrag                 int64
	Kurs                   *string
	KursQuelle             *string
	KursDatum              *string
	KursGrund              *string
	BetragEur              int64
	Rechnungsart           string
	RechnungAufArbeitgeber bool
	Empfaenger             *string
	Verkehrsmittel         *string
	UebernachtungNaechte   string
	FruehstueckEnthalten   bool
	Mahlzeit               *string
	Bewirtung              *string
	TseBeleg               bool
	ErstelltAm             time.Time
	GeaendertAm            time.Time
}

func (q *Queries) InsertAusgabe(ctx context.Context, arg InsertAusgabeParams) (Ausgabe, error) {
	row := q.db.QueryRowContext(ctx, insertAusgabe,
		arg.ID,
		arg.NutzerID,
		arg.ReiseID,
		arg.Kostenart,
		arg.Datum,
		arg.Leistender,
		arg.Beschreibung,
		arg.Waehrung,
		arg.Betrag,
		arg.Kurs,
		arg.KursQuelle,
		arg.KursDatum,
		arg.KursGrund,
		arg.BetragEur,
		arg.Rechnungsart,
		arg.RechnungAufArbeitgeber,
		arg.Empfaenger,
		arg.Verkehrsmittel,
		arg.UebernachtungNaechte,
		arg.FruehstueckEnthalten,
		arg.Mahlzeit,
		arg.Bewirtung,
		arg.TseBeleg,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Ausgabe
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ReiseID,
		&i.Kostenart,
		&i.Datum,
		&i.Leistender,
		&i.Beschreibung,
		&i.Waehrung,
		&i.Betrag,
		&i.Kurs,
		&i.KursQuelle,
		&i.KursDatum,
		&i.KursGrund,
		&i.BetragEur,
		&i.Rechnungsart,
		&i.RechnungAufArbeitgeber,
		&i.Empfaenger,
		&i.Verkehrsmittel,
		&i.UebernachtungNaechte,
		&i.FruehstueckEnthalten,
		&i.Mahlzeit,
		&i.Bewirtung,
		&i.TseBeleg,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertAusgabeBeleg = `-- name: InsertAusgabeBeleg :exec
INSERT INTO ausgabe_beleg (ausgabe_id, beleg_id)
VALUES (?1, ?2)
`

type InsertAusgabeBelegParams struct {
	AusgabeID string
	BelegID   string
}

func (q *Queries) InsertAusgabeBeleg(ctx context.Context, arg InsertAusgabeBelegParams) error {
	_, err := q.db.ExecContext(ctx, insertAusgabeBeleg, arg.AusgabeID, arg.BelegID)
	return err
}

const insertSteueranteil = `-- name: InsertSteueranteil :one
INSERT INTO steueranteil (
  id, ausgabe_id, position, satz, steuerland, netto, steuer, brutto, netto_eur, steuer_eur, brutto_eur
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9, ?10, ?11
)
RETURNING id, ausgabe_id, position, satz, steuerland, netto, steuer, brutto, netto_eur, steuer_eur, brutto_eur
`

type InsertSteueranteilParams struct {
	ID         string
	AusgabeID  string
	Position   int64
	Satz       int64
	Steuerland string
	Netto      int64
	Steuer     int64
	Brutto     int64
	NettoEur   int64
	SteuerEur  int64
	BruttoEur  int64
}

func (q *Queries) InsertSteueranteil(ctx context.Context, arg InsertSteueranteilParams) (Steueranteil, error) {
	row := q.db.QueryRowContext(ctx, insertSteueranteil,
		arg.ID,
		arg.AusgabeID,
		arg.Position,
		arg.Satz,
		arg.Steuerland,
		arg.Netto,
		arg.Steuer,
		arg.Brutto,
		arg.NettoEur,
		arg.SteuerEur,
		arg.BruttoEur,
	)
	var i Steueranteil
	err := row.Scan(
		&i.ID,
		&i.AusgabeID,
		&i.Position,
		&i.Satz,
		&i.Steuerland,
		&i.Netto,
		&i.Steuer,
		&i.Brutto,
		&i.NettoEur,
		&i.SteuerEur,
		&i.BruttoEur,
	)
	return i, err
}

const insertVorschuss = `-- name: InsertVorschuss :one
INSERT INTO vorschuss (
  id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, 1
)
RETURNING id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, abrechnung_id, erstellt_am, geaendert_am, version
`

type InsertVorschussParams struct {
	ID            string
	NutzerID      string
	ArbeitgeberID string
	Datum         string
	Betrag        int64
	Notiz         *string
	ErstelltAm    time.Time
	GeaendertAm   time.Time
}

func (q *Queries) InsertVorschuss(ctx context.Context, arg InsertVorschussParams) (Vorschuss, error) {
	row := q.db.QueryRowContext(ctx, insertVorschuss,
		arg.ID,
		arg.NutzerID,
		arg.ArbeitgeberID,
		arg.Datum,
		arg.Betrag,
		arg.Notiz,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Vorschuss
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Datum,
		&i.Betrag,
		&i.Notiz,
		&i.AbrechnungID,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const listAusgabenByNutzer = `-- name: ListAusgabenByNutzer :many
SELECT id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag, kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber, empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung, tse_beleg, erstellt_am, geaendert_am, version FROM ausgabe
WHERE nutzer_id = ?1
ORDER BY datum, id
`

func (q *Queries) ListAusgabenByNutzer(ctx context.Context, nutzerID string) ([]Ausgabe, error) {
	rows, err := q.db.QueryContext(ctx, listAusgabenByNutzer, nutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ausgabe
	for rows.Next() {
		var i Ausgabe
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ReiseID,
			&i.Kostenart,
			&i.Datum,
			&i.Leistender,
			&i.Beschreibung,
			&i.Waehrung,
			&i.Betrag,
			&i.Kurs,
			&i.KursQuelle,
			&i.KursDatum,
			&i.KursGrund,
			&i.BetragEur,
			&i.Rechnungsart,
			&i.RechnungAufArbeitgeber,
			&i.Empfaenger,
			&i.Verkehrsmittel,
			&i.UebernachtungNaechte,
			&i.FruehstueckEnthalten,
			&i.Mahlzeit,
			&i.Bewirtung,
			&i.TseBeleg,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAusgabenByReise = `-- name: ListAusgabenByReise :many
SELECT id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag, kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber, empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung, tse_beleg, erstellt_am, geaendert_am, version FROM ausgabe
WHERE reise_id = ?1 AND nutzer_id = ?2
ORDER BY datum, id
`

type ListAusgabenByReiseParams struct {
	ReiseID  string
	NutzerID string
}

func (q *Queries) ListAusgabenByReise(ctx context.Context, arg ListAusgabenByReiseParams) ([]Ausgabe, error) {
	rows, err := q.db.QueryContext(ctx, listAusgabenByReise, arg.ReiseID, arg.NutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ausgabe
	for rows.Next() {
		var i Ausgabe
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ReiseID,
			&i.Kostenart,
			&i.Datum,
			&i.Leistender,
			&i.Beschreibung,
			&i.Waehrung,
			&i.Betrag,
			&i.Kurs,
			&i.KursQuelle,
			&i.KursDatum,
			&i.KursGrund,
			&i.BetragEur,
			&i.Rechnungsart,
			&i.RechnungAufArbeitgeber,
			&i.Empfaenger,
			&i.Verkehrsmittel,
			&i.UebernachtungNaechte,
			&i.FruehstueckEnthalten,
			&i.Mahlzeit,
			&i.Bewirtung,
			&i.TseBeleg,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBelegeForAusgabe = `-- name: ListBelegeForAusgabe :many
SELECT beleg.id, beleg.status
FROM ausgabe_beleg
JOIN beleg ON beleg.id = ausgabe_beleg.beleg_id
WHERE ausgabe_beleg.ausgabe_id = ?1 AND beleg.nutzer_id = ?2
ORDER BY beleg.id
`

type ListBelegeForAusgabeParams struct {
	AusgabeID string
	NutzerID  string
}

type ListBelegeForAusgabeRow struct {
	ID     string
	Status string
}

func (q *Queries) ListBelegeForAusgabe(ctx context.Context, arg ListBelegeForAusgabeParams) ([]ListBelegeForAusgabeRow, error) {
	rows, err := q.db.QueryContext(ctx, listBelegeForAusgabe, arg.AusgabeID, arg.NutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBelegeForAusgabeRow
	for rows.Next() {
		var i ListBelegeForAusgabeRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSteueranteile = `-- name: ListSteueranteile :many
SELECT id, ausgabe_id, position, satz, steuerland, netto, steuer, brutto, netto_eur, steuer_eur, brutto_eur FROM steueranteil
WHERE ausgabe_id = ?1
ORDER BY position
`

func (q *Queries) ListSteueranteile(ctx context.Context, ausgabeID string) ([]Steueranteil, error) {
	rows, err := q.db.QueryContext(ctx, listSteueranteile, ausgabeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Steueranteil
	for rows.Next() {
		var i Steueranteil
		if err := rows.Scan(
			&i.ID,
			&i.AusgabeID,
			&i.Position,
			&i.Satz,
			&i.Steuerland,
			&i.Netto,
			&i.Steuer,
			&i.Brutto,
			&i.NettoEur,
			&i.SteuerEur,
			&i.BruttoEur,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVorschuesse = `-- name: ListVorschuesse :many
SELECT id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, abrechnung_id, erstellt_am, geaendert_am, version FROM vorschuss
WHERE nutzer_id = ?1
ORDER BY datum, id
`

func (q *Queries) ListVorschuesse(ctx context.Context, nutzerID string) ([]Vorschuss, error) {
	rows, err := q.db.QueryContext(ctx, listVorschuesse, nutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vorschuss
	for rows.Next() {
		var i Vorschuss
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ArbeitgeberID,
			&i.Datum,
			&i.Betrag,
			&i.Notiz,
			&i.AbrechnungID,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWechselkurse = `-- name: ListWechselkurse :many
SELECT datum, waehrung, kurs, quelle, abgerufen_am FROM wechselkurs
WHERE waehrung = ?1
ORDER BY datum
`

func (q *Queries) ListWechselkurse(ctx context.Context, waehrung string) ([]Wechselkur, error) {
	rows, err := q.db.QueryContext(ctx, listWechselkurse, waehrung)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wechselkur
	for rows.Next() {
		var i Wechselkur
		if err := rows.Scan(
			&i.Datum,
			&i.Waehrung,
			&i.Kurs,
			&i.Quelle,
			&i.AbgerufenAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWechselkurseAll = `-- name: ListWechselkurseAll :many
SELECT datum, waehrung, kurs, quelle, abgerufen_am FROM wechselkurs
ORDER BY datum, waehrung
`

func (q *Queries) ListWechselkurseAll(ctx context.Context) ([]Wechselkur, error) {
	rows, err := q.db.QueryContext(ctx, listWechselkurseAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wechselkur
	for rows.Next() {
		var i Wechselkur
		if err := rows.Scan(
			&i.Datum,
			&i.Waehrung,
			&i.Kurs,
			&i.Quelle,
			&i.AbgerufenAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBewirtung = `-- name: SetBewirtung :one
UPDATE ausgabe SET
  bewirtung = ?1,
  tse_beleg = ?2,
  geaendert_am = ?3,
  version = version + 1
WHERE id = ?4 AND nutzer_id = ?5 AND version = ?6
RETURNING id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag, kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber, empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung, tse_beleg, erstellt_am, geaendert_am, version
`

type SetBewirtungParams struct {
	Bewirtung   *string
	TseBeleg    bool
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) SetBewirtung(ctx context.Context, arg SetBewirtungParams) (Ausgabe, error) {
	row := q.db.QueryRowContext(ctx, setBewirtung,
		arg.Bewirtung,
		arg.TseBeleg,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Ausgabe
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ReiseID,
		&i.Kostenart,
		&i.Datum,
		&i.Leistender,
		&i.Beschreibung,
		&i.Waehrung,
		&i.Betrag,
		&i.Kurs,
		&i.KursQuelle,
		&i.KursDatum,
		&i.KursGrund,
		&i.BetragEur,
		&i.Rechnungsart,
		&i.RechnungAufArbeitgeber,
		&i.Empfaenger,
		&i.Verkehrsmittel,
		&i.UebernachtungNaechte,
		&i.FruehstueckEnthalten,
		&i.Mahlzeit,
		&i.Bewirtung,
		&i.TseBeleg,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const setRechnungsart = `-- name: SetRechnungsart :one
UPDATE ausgabe SET
  rechnungsart = ?1,
  geaendert_am = ?2,
  version = version + 1
WHERE id = ?3 AND nutzer_id = ?4 AND version = ?5
RETURNING id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag, kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber, empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung, tse_beleg, erstellt_am, geaendert_am, version
`

type SetRechnungsartParams struct {
	Rechnungsart string
	GeaendertAm  time.Time
	ID           string
	NutzerID     string
	Version      int64
}

func (q *Queries) SetRechnungsart(ctx context.Context, arg SetRechnungsartParams) (Ausgabe, error) {
	row := q.db.QueryRowContext(ctx, setRechnungsart,
		arg.Rechnungsart,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Ausgabe
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ReiseID,
		&i.Kostenart,
		&i.Datum,
		&i.Leistender,
		&i.Beschreibung,
		&i.Waehrung,
		&i.Betrag,
		&i.Kurs,
		&i.KursQuelle,
		&i.KursDatum,
		&i.KursGrund,
		&i.BetragEur,
		&i.Rechnungsart,
		&i.RechnungAufArbeitgeber,
		&i.Empfaenger,
		&i.Verkehrsmittel,
		&i.UebernachtungNaechte,
		&i.FruehstueckEnthalten,
		&i.Mahlzeit,
		&i.Bewirtung,
		&i.TseBeleg,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateAusgabe = `-- name: UpdateAusgabe :one
UPDATE ausgabe SET
  kostenart = ?1,
  datum = ?2,
  leistender = ?3,
  beschreibung = ?4,
  waehrung = ?5,
  betrag = ?6,
  kurs = ?7,
  kurs_quelle = ?8,
  kurs_datum = ?9,
  kurs_grund = ?10,
  betrag_eur = ?11,
  rechnungsart = ?12,
  rechnung_auf_arbeitgeber = ?13,
  empfaenger = ?14,
  verkehrsmittel = ?15,
  uebernachtung_naechte = ?16,
  fruehstueck_enthalten = ?17,
  mahlzeit = ?18,
  bewirtung = ?19,
  tse_beleg = ?20,
  geaendert_am = ?21,
  version = version + 1
WHERE id = ?22 AND nutzer_id = ?23 AND version = ?24
RETURNING id, nutzer_id, reise_id, kostenart, datum, leistender, beschreibung, waehrung, betrag, kurs, kurs_quelle, kurs_datum, kurs_grund, betrag_eur, rechnungsart, rechnung_auf_arbeitgeber, empfaenger, verkehrsmittel, uebernachtung_naechte, fruehstueck_enthalten, mahlzeit, bewirtung, tse_beleg, erstellt_am, geaendert_am, version
`

type UpdateAusgabeParams struct {
	Kostenart              string
	Datum                  string
	Leistender             string
	Beschreibung           *string
	Waehrung               string
	Betrag                 int64
	Kurs                   *string
	KursQuelle             *string
	KursDatum              *string
	KursGrund              *string
	BetragEur              int64
	Rechnungsart           string
	RechnungAufArbeitgeber bool
	Empfaenger             *string
	Verkehrsmittel         *string
	UebernachtungNaechte   string
	FruehstueckEnthalten   bool
	Mahlzeit               *string
	Bewirtung              *string
	TseBeleg               bool
	GeaendertAm            time.Time
	ID                     string
	NutzerID               string
	Version                int64
}

func (q *Queries) UpdateAusgabe(ctx context.Context, arg UpdateAusgabeParams) (Ausgabe, error) {
	row := q.db.QueryRowContext(ctx, updateAusgabe,
		arg.Kostenart,
		arg.Datum,
		arg.Leistender,
		arg.Beschreibung,
		arg.Waehrung,
		arg.Betrag,
		arg.Kurs,
		arg.KursQuelle,
		arg.KursDatum,
		arg.KursGrund,
		arg.BetragEur,
		arg.Rechnungsart,
		arg.RechnungAufArbeitgeber,
		arg.Empfaenger,
		arg.Verkehrsmittel,
		arg.UebernachtungNaechte,
		arg.FruehstueckEnthalten,
		arg.Mahlzeit,
		arg.Bewirtung,
		arg.TseBeleg,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Ausgabe
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ReiseID,
		&i.Kostenart,
		&i.Datum,
		&i.Leistender,
		&i.Beschreibung,
		&i.Waehrung,
		&i.Betrag,
		&i.Kurs,
		&i.KursQuelle,
		&i.KursDatum,
		&i.KursGrund,
		&i.BetragEur,
		&i.Rechnungsart,
		&i.RechnungAufArbeitgeber,
		&i.Empfaenger,
		&i.Verkehrsmittel,
		&i.UebernachtungNaechte,
		&i.FruehstueckEnthalten,
		&i.Mahlzeit,
		&i.Bewirtung,
		&i.TseBeleg,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateVorschuss = `-- name: UpdateVorschuss :one
UPDATE vorschuss SET
  datum = ?1,
  betrag = ?2,
  notiz = ?3,
  geaendert_am = ?4,
  version = version + 1
WHERE id = ?5 AND nutzer_id = ?6 AND version = ?7 AND abrechnung_id IS NULL
RETURNING id, nutzer_id, arbeitgeber_id, datum, betrag, notiz, abrechnung_id, erstellt_am, geaendert_am, version
`

type UpdateVorschussParams struct {
	Datum       string
	Betrag      int64
	Notiz       *string
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) UpdateVorschuss(ctx context.Context, arg UpdateVorschussParams) (Vorschuss, error) {
	row := q.db.QueryRowContext(ctx, updateVorschuss,
		arg.Datum,
		arg.Betrag,
		arg.Notiz,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Vorschuss
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Datum,
		&i.Betrag,
		&i.Notiz,
		&i.AbrechnungID,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const upsertEigenbeleg = `-- name: UpsertEigenbeleg :one
INSERT INTO eigenbeleg (
  ausgabe_id, grund, zahlungsempfaenger, art, erstellt_am, bestaetigt_am, bestaetigt_von
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
ON CONFLICT (ausgabe_id) DO UPDATE SET
  grund = excluded.grund,
  zahlungsempfaenger = excluded.zahlungsempfaenger,
  art = excluded.art,
  bestaetigt_am = excluded.bestaetigt_am,
  bestaetigt_von = excluded.bestaetigt_von
RETURNING ausgabe_id, grund, zahlungsempfaenger, art, erstellt_am, bestaetigt_am, bestaetigt_von
`

type UpsertEigenbelegParams struct {
	AusgabeID          string
	Grund              string
	Zahlungsempfaenger string
	Art                string
	ErstelltAm         time.Time
	BestaetigtAm       *time.Time
	BestaetigtVon      *string
}

func (q *Queries) UpsertEigenbeleg(ctx context.Context, arg UpsertEigenbelegParams) (Eigenbeleg, error) {
	row := q.db.QueryRowContext(ctx, upsertEigenbeleg,
		arg.AusgabeID,
		arg.Grund,
		arg.Zahlungsempfaenger,
		arg.Art,
		arg.ErstelltAm,
		arg.BestaetigtAm,
		arg.BestaetigtVon,
	)
	var i Eigenbeleg
	err := row.Scan(
		&i.AusgabeID,
		&i.Grund,
		&i.Zahlungsempfaenger,
		&i.Art,
		&i.ErstelltAm,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
	)
	return i, err
}

const upsertUstMonatskurs = `-- name: UpsertUstMonatskurs :exec
INSERT INTO ust_monatskurs (jahr, monat, waehrung, kurs, abgerufen_am)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (jahr, monat, waehrung) DO UPDATE SET
  kurs = excluded.kurs,
  abgerufen_am = excluded.abgerufen_am
`

type UpsertUstMonatskursParams struct {
	Jahr        int64
	Monat       int64
	Waehrung    string
	Kurs        string
	AbgerufenAm time.Time
}

func (q *Queries) UpsertUstMonatskurs(ctx context.Context, arg UpsertUstMonatskursParams) error {
	_, err := q.db.ExecContext(ctx, upsertUstMonatskurs,
		arg.Jahr,
		arg.Monat,
		arg.Waehrung,
		arg.Kurs,
		arg.AbgerufenAm,
	)
	return err
}

const upsertWechselkurs = `-- name: UpsertWechselkurs :exec
INSERT INTO wechselkurs (datum, waehrung, kurs, quelle, abgerufen_am)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (datum, waehrung) DO UPDATE SET
  kurs = excluded.kurs,
  quelle = excluded.quelle,
  abgerufen_am = excluded.abgerufen_am
`

type UpsertWechselkursParams struct {
	Datum       string
	Waehrung    string
	Kurs        string
	Quelle      string
	AbgerufenAm time.Time
}

func (q *Queries) UpsertWechselkurs(ctx context.Context, arg UpsertWechselkursParams) error {
	_, err := q.db.ExecContext(ctx, upsertWechselkurs,
		arg.Datum,
		arg.Waehrung,
		arg.Kurs,
		arg.Quelle,
		arg.AbgerufenAm,
	)
	return err
}
