// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: belegtext.sql

package sqlitedb

import (
	"context"
	"time"
)

const insertBelegtext = `-- name: InsertBelegtext :one
INSERT INTO belegtext (
  id, beleg_id, version, quelle, felder, volltext, bestaetigt_am, bestaetigt_von
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8
)
RETURNING id, beleg_id, version, quelle, felder, volltext, bestaetigt_am, bestaetigt_von
`

type InsertBelegtextParams struct {
	ID            string
	BelegID       string
	Version       int64
	Quelle        string
	Felder        string
	Volltext      string
	BestaetigtAm  *time.Time
	BestaetigtVon *string
}

func (q *Queries) InsertBelegtext(ctx context.Context, arg InsertBelegtextParams) (Belegtext, error) {
	row := q.db.QueryRowContext(ctx, insertBelegtext,
		arg.ID,
		arg.BelegID,
		arg.Version,
		arg.Quelle,
		arg.Felder,
		arg.Volltext,
		arg.BestaetigtAm,
		arg.BestaetigtVon,
	)
	var i Belegtext
	err := row.Scan(
		&i.ID,
		&i.BelegID,
		&i.Version,
		&i.Quelle,
		&i.Felder,
		&i.Volltext,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
	)
	return i, err
}

const latestJob = `-- name: LatestJob :one
SELECT id, art, status, payload, versuche, naechster_versuch_am, fehler, erstellt_am, geaendert_am
FROM job
WHERE art = ?1 AND payload = ?2
ORDER BY erstellt_am DESC
LIMIT 1
`

type LatestJobParams struct {
	Art     string
	Payload *string
}

func (q *Queries) LatestJob(ctx context.Context, arg LatestJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, latestJob, arg.Art, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Art,
		&i.Status,
		&i.Payload,
		&i.Versuche,
		&i.NaechsterVersuchAm,
		&i.Fehler,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const listBelegtexte = `-- name: ListBelegtexte :many
SELECT id, beleg_id, version, quelle, felder, volltext, bestaetigt_am, bestaetigt_von
FROM belegtext
WHERE beleg_id = ?1
ORDER BY version
`

func (q *Queries) ListBelegtexte(ctx context.Context, belegID string) ([]Belegtext, error) {
	rows, err := q.db.QueryContext(ctx, listBelegtexte, belegID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Belegtext
	for rows.Next() {
		var i Belegtext
		if err := rows.Scan(
			&i.ID,
			&i.BelegID,
			&i.Version,
			&i.Quelle,
			&i.Felder,
			&i.Volltext,
			&i.BestaetigtAm,
			&i.BestaetigtVon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxBelegtextVersion = `-- name: MaxBelegtextVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS BIGINT) AS version
FROM belegtext
WHERE beleg_id = ?1
`

func (q *Queries) MaxBelegtextVersion(ctx context.Context, belegID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxBelegtextVersion, belegID)
	var version int64
	err := row.Scan(&version)
	return version, err
}
