// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beleg.sql

package sqlitedb

import (
	"context"
	"time"
)

const bumpBelegnummer = `-- name: BumpBelegnummer :one
INSERT INTO beleg_nummer (nutzer_id, jahr, naechste)
VALUES (?1, ?2, 1)
ON CONFLICT (nutzer_id, jahr) DO UPDATE SET naechste = beleg_nummer.naechste + 1
RETURNING naechste
`

type BumpBelegnummerParams struct {
	NutzerID string
	Jahr     int64
}

func (q *Queries) BumpBelegnummer(ctx context.Context, arg BumpBelegnummerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpBelegnummer, arg.NutzerID, arg.Jahr)
	var naechste int64
	err := row.Scan(&naechste)
	return naechste, err
}

const claimJob = `-- name: ClaimJob :one
UPDATE job SET
  status = 'running',
  versuche = versuche + 1,
  geaendert_am = ?1
WHERE id = (
  SELECT id FROM job
  WHERE (status = 'pending' AND (naechster_versuch_am IS NULL OR naechster_versuch_am <= ?1))
     OR (status = 'running' AND job.geaendert_am <= ?2)
  ORDER BY id
  LIMIT 1
)
RETURNING id, art, status, payload, versuche, naechster_versuch_am, fehler, erstellt_am, geaendert_am
`

type ClaimJobParams struct {
	Jetzt time.Time
	Stale time.Time
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.Jetzt, arg.Stale)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Art,
		&i.Status,
		&i.Payload,
		&i.Versuche,
		&i.NaechsterVersuchAm,
		&i.Fehler,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const clearErfassung = `-- name: ClearErfassung :exec
UPDATE beleg SET
  erfassung_loeschen_am = NULL,
  geaendert_am = ?1,
  version = version + 1
WHERE id = ?2
`

type ClearErfassungParams struct {
	GeaendertAm time.Time
	ID          string
}

func (q *Queries) ClearErfassung(ctx context.Context, arg ClearErfassungParams) error {
	_, err := q.db.ExecContext(ctx, clearErfassung, arg.GeaendertAm, arg.ID)
	return err
}

const confirmBeleg = `-- name: ConfirmBeleg :one
UPDATE beleg SET
  status = 'bestaetigt',
  belegnummer = ?1,
  bestaetigt_am = ?2,
  bestaetigt_von = ?3,
  aufbewahren_bis = ?4,
  erfassung_loeschen_am = ?5,
  geaendert_am = ?6,
  version = version + 1
WHERE id = ?7 AND nutzer_id = ?8
  AND status = 'zur_bestaetigung' AND version = ?9
RETURNING id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version
`

type ConfirmBelegParams struct {
	Belegnummer         *string
	BestaetigtAm        *time.Time
	BestaetigtVon       *string
	AufbewahrenBis      *string
	ErfassungLoeschenAm *time.Time
	GeaendertAm         time.Time
	ID                  string
	NutzerID            string
	Version             int64
}

func (q *Queries) ConfirmBeleg(ctx context.Context, arg ConfirmBelegParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, confirmBeleg,
		arg.Belegnummer,
		arg.BestaetigtAm,
		arg.BestaetigtVon,
		arg.AufbewahrenBis,
		arg.ErfassungLoeschenAm,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const deleteBelegOffen = `-- name: DeleteBelegOffen :execrows
DELETE FROM beleg
WHERE id = ?1 AND nutzer_id = ?2
  AND version = ?3
  AND status IN ('hochgeladen', 'in_aufbereitung', 'zur_bestaetigung', 'fehlgeschlagen')
`

type DeleteBelegOffenParams struct {
	ID       string
	NutzerID string
	Version  int64
}

func (q *Queries) DeleteBelegOffen(ctx context.Context, arg DeleteBelegOffenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBelegOffen, arg.ID, arg.NutzerID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBelegdateiVariante = `-- name: DeleteBelegdateiVariante :exec
DELETE FROM belegdatei
WHERE beleg_id = ?1 AND variante = ?2
`

type DeleteBelegdateiVarianteParams struct {
	BelegID  string
	Variante string
}

func (q *Queries) DeleteBelegdateiVariante(ctx context.Context, arg DeleteBelegdateiVarianteParams) error {
	_, err := q.db.ExecContext(ctx, deleteBelegdateiVariante, arg.BelegID, arg.Variante)
	return err
}

const deleteJobsForBeleg = `-- name: DeleteJobsForBeleg :exec
DELETE FROM job
WHERE payload = ?1
`

func (q *Queries) DeleteJobsForBeleg(ctx context.Context, belegID *string) error {
	_, err := q.db.ExecContext(ctx, deleteJobsForBeleg, belegID)
	return err
}

const failJobRow = `-- name: FailJobRow :exec
UPDATE job SET
  status = 'failed',
  fehler = ?1,
  geaendert_am = ?2
WHERE id = ?3
`

type FailJobRowParams struct {
	Fehler *string
	Jetzt  time.Time
	ID     string
}

func (q *Queries) FailJobRow(ctx context.Context, arg FailJobRowParams) error {
	_, err := q.db.ExecContext(ctx, failJobRow, arg.Fehler, arg.Jetzt, arg.ID)
	return err
}

const findBelegByDateiSHA = `-- name: FindBelegByDateiSHA :one
SELECT beleg.id, beleg.nutzer_id, beleg.belegnummer, beleg.typ, beleg.status, beleg.seiten, beleg.sha256_original, beleg.pipeline_version, beleg.pipeline_parameter, beleg.bestaetigt_am, beleg.bestaetigt_von, beleg.storno_grund, beleg.storniert_am, beleg.aufbewahren_bis, beleg.erfassung_loeschen_am, beleg.duplikat_von, beleg.erstellt_am, beleg.geaendert_am, beleg.version FROM beleg
JOIN belegdatei ON belegdatei.beleg_id = beleg.id
WHERE beleg.nutzer_id = ?1
  AND belegdatei.sha256 = ?2
  AND belegdatei.variante IN ('archiv', 'original')
  AND beleg.status != 'storniert'
ORDER BY beleg.id
LIMIT 1
`

type FindBelegByDateiSHAParams struct {
	NutzerID string
	Sha256   string
}

func (q *Queries) FindBelegByDateiSHA(ctx context.Context, arg FindBelegByDateiSHAParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, findBelegByDateiSHA, arg.NutzerID, arg.Sha256)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const findBelegBySHA = `-- name: FindBelegBySHA :one
SELECT id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version FROM beleg
WHERE nutzer_id = ?1
  AND sha256_original = ?2
  AND status != 'storniert'
ORDER BY id
LIMIT 1
`

type FindBelegBySHAParams struct {
	NutzerID string
	Sha256   string
}

func (q *Queries) FindBelegBySHA(ctx context.Context, arg FindBelegBySHAParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, findBelegBySHA, arg.NutzerID, arg.Sha256)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :exec
UPDATE job SET
  status = 'done',
  fehler = NULL,
  geaendert_am = ?1
WHERE id = ?2
`

type FinishJobParams struct {
	Jetzt time.Time
	ID    string
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob, arg.Jetzt, arg.ID)
	return err
}

const getBeleg = `-- name: GetBeleg :one
SELECT id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version FROM beleg
WHERE id = ?1 AND nutzer_id = ?2
`

type GetBelegParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetBeleg(ctx context.Context, arg GetBelegParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, getBeleg, arg.ID, arg.NutzerID)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getBelegByID = `-- name: GetBelegByID :one
SELECT id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version FROM beleg
WHERE id = ?1
`

func (q *Queries) GetBelegByID(ctx context.Context, id string) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, getBelegByID, id)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getBelegdatei = `-- name: GetBelegdatei :one
SELECT id, beleg_id, variante, seite, speicher_schluessel, mime, bytes, sha256, unveraenderbar FROM belegdatei
WHERE beleg_id = ?1 AND variante = ?2 AND seite = ?3
`

type GetBelegdateiParams struct {
	BelegID  string
	Variante string
	Seite    int64
}

func (q *Queries) GetBelegdatei(ctx context.Context, arg GetBelegdateiParams) (Belegdatei, error) {
	row := q.db.QueryRowContext(ctx, getBelegdatei, arg.BelegID, arg.Variante, arg.Seite)
	var i Belegdatei
	err := row.Scan(
		&i.ID,
		&i.BelegID,
		&i.Variante,
		&i.Seite,
		&i.SpeicherSchluessel,
		&i.Mime,
		&i.Bytes,
		&i.Sha256,
		&i.Unveraenderbar,
	)
	return i, err
}

const insertBeleg = `-- name: InsertBeleg :one
INSERT INTO beleg (
  id, nutzer_id, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter,
  duplikat_von, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8,
  ?9, ?10, ?11, 1
)
RETURNING id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version
`

type InsertBelegParams struct {
	ID                string
	NutzerID          string
	Typ               string
	Status            string
	Seiten            int64
	Sha256Original    string
	PipelineVersion   string
	PipelineParameter string
	DuplikatVon       *string
	ErstelltAm        time.Time
	GeaendertAm       time.Time
}

func (q *Queries) InsertBeleg(ctx context.Context, arg InsertBelegParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, insertBeleg,
		arg.ID,
		arg.NutzerID,
		arg.Typ,
		arg.Status,
		arg.Seiten,
		arg.Sha256Original,
		arg.PipelineVersion,
		arg.PipelineParameter,
		arg.DuplikatVon,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertBelegdatei = `-- name: InsertBelegdatei :one
INSERT INTO belegdatei (
  id, beleg_id, variante, seite, speicher_schluessel, mime, bytes, sha256, unveraenderbar
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9
)
RETURNING id, beleg_id, variante, seite, speicher_schluessel, mime, bytes, sha256, unveraenderbar
`

type InsertBelegdateiParams struct {
	ID                 string
	BelegID            string
	Variante           string
	Seite              int64
	SpeicherSchluessel string
	Mime               string
	Bytes              int64
	Sha256             string
	Unveraenderbar     bool
}

func (q *Queries) InsertBelegdatei(ctx context.Context, arg InsertBelegdateiParams) (Belegdatei, error) {
	row := q.db.QueryRowContext(ctx, insertBelegdatei,
		arg.ID,
		arg.BelegID,
		arg.Variante,
		arg.Seite,
		arg.SpeicherSchluessel,
		arg.Mime,
		arg.Bytes,
		arg.Sha256,
		arg.Unveraenderbar,
	)
	var i Belegdatei
	err := row.Scan(
		&i.ID,
		&i.BelegID,
		&i.Variante,
		&i.Seite,
		&i.SpeicherSchluessel,
		&i.Mime,
		&i.Bytes,
		&i.Sha256,
		&i.Unveraenderbar,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO job (
  id, art, status, payload, versuche, naechster_versuch_am, erstellt_am, geaendert_am
) VALUES (
  ?1, ?2, 'pending', ?3, 0,
  ?4, ?5, ?6
)
RETURNING id, art, status, payload, versuche, naechster_versuch_am, fehler, erstellt_am, geaendert_am
`

type InsertJobParams struct {
	ID                 string
	Art                string
	Payload            *string
	NaechsterVersuchAm *time.Time
	ErstelltAm         time.Time
	GeaendertAm        time.Time
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.Art,
		arg.Payload,
		arg.NaechsterVersuchAm,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Art,
		&i.Status,
		&i.Payload,
		&i.Versuche,
		&i.NaechsterVersuchAm,
		&i.Fehler,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const listBelegdateien = `-- name: ListBelegdateien :many
SELECT id, beleg_id, variante, seite, speicher_schluessel, mime, bytes, sha256, unveraenderbar FROM belegdatei
WHERE beleg_id = ?1
ORDER BY variante, seite
`

func (q *Queries) ListBelegdateien(ctx context.Context, belegID string) ([]Belegdatei, error) {
	rows, err := q.db.QueryContext(ctx, listBelegdateien, belegID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Belegdatei
	for rows.Next() {
		var i Belegdatei
		if err := rows.Scan(
			&i.ID,
			&i.BelegID,
			&i.Variante,
			&i.Seite,
			&i.SpeicherSchluessel,
			&i.Mime,
			&i.Bytes,
			&i.Sha256,
			&i.Unveraenderbar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBelege = `-- name: ListBelege :many
SELECT id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version FROM beleg
WHERE nutzer_id = ?1
  AND (?2 = '' OR status = ?2)
  AND (
    ?3 = 0
    OR status IN ('hochgeladen', 'in_aufbereitung', 'zur_bestaetigung', 'fehlgeschlagen')
  )
  AND (?4 = '' OR id < ?4)
ORDER BY id DESC
LIMIT ?5
`

type ListBelegeParams struct {
	NutzerID   string
	Status     interface{}
	NurEingang interface{}
	Cursor     interface{}
	LimitN     int64
}

func (q *Queries) ListBelege(ctx context.Context, arg ListBelegeParams) ([]Beleg, error) {
	rows, err := q.db.QueryContext(ctx, listBelege,
		arg.NutzerID,
		arg.Status,
		arg.NurEingang,
		arg.Cursor,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Beleg
	for rows.Next() {
		var i Beleg
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Belegnummer,
			&i.Typ,
			&i.Status,
			&i.Seiten,
			&i.Sha256Original,
			&i.PipelineVersion,
			&i.PipelineParameter,
			&i.BestaetigtAm,
			&i.BestaetigtVon,
			&i.StornoGrund,
			&i.StorniertAm,
			&i.AufbewahrenBis,
			&i.ErfassungLoeschenAm,
			&i.DuplikatVon,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffeneDuplikate = `-- name: ListOffeneDuplikate :many
SELECT id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version FROM beleg
WHERE nutzer_id = ?1
  AND duplikat_von IS NOT NULL
  AND status != 'storniert'
ORDER BY id DESC
LIMIT 100
`

func (q *Queries) ListOffeneDuplikate(ctx context.Context, nutzerID string) ([]Beleg, error) {
	rows, err := q.db.QueryContext(ctx, listOffeneDuplikate, nutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Beleg
	for rows.Next() {
		var i Beleg
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Belegnummer,
			&i.Typ,
			&i.Status,
			&i.Seiten,
			&i.Sha256Original,
			&i.PipelineVersion,
			&i.PipelineParameter,
			&i.BestaetigtAm,
			&i.BestaetigtVon,
			&i.StornoGrund,
			&i.StorniertAm,
			&i.AufbewahrenBis,
			&i.ErfassungLoeschenAm,
			&i.DuplikatVon,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBelegdateienFest = `-- name: MarkBelegdateienFest :exec
UPDATE belegdatei SET unveraenderbar = TRUE
WHERE beleg_id = ?1
  AND variante IN ('archiv', 'original', 'export_jpeg')
`

func (q *Queries) MarkBelegdateienFest(ctx context.Context, belegID string) error {
	_, err := q.db.ExecContext(ctx, markBelegdateienFest, belegID)
	return err
}

const rescheduleJob = `-- name: RescheduleJob :exec
UPDATE job SET
  status = 'pending',
  fehler = ?1,
  naechster_versuch_am = ?2,
  geaendert_am = ?3
WHERE id = ?4
`

type RescheduleJobParams struct {
	Fehler             *string
	NaechsterVersuchAm *time.Time
	Jetzt              time.Time
	ID                 string
}

func (q *Queries) RescheduleJob(ctx context.Context, arg RescheduleJobParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleJob,
		arg.Fehler,
		arg.NaechsterVersuchAm,
		arg.Jetzt,
		arg.ID,
	)
	return err
}

const resumeJobs = `-- name: ResumeJobs :exec
UPDATE job SET
  status = 'pending',
  geaendert_am = ?1
WHERE status = 'running'
`

func (q *Queries) ResumeJobs(ctx context.Context, jetzt time.Time) error {
	_, err := q.db.ExecContext(ctx, resumeJobs, jetzt)
	return err
}

const setBelegFailed = `-- name: SetBelegFailed :exec
UPDATE beleg SET
  status = 'fehlgeschlagen',
  geaendert_am = ?1,
  version = version + 1
WHERE id = ?2
  AND status IN ('hochgeladen', 'in_aufbereitung', 'fehlgeschlagen')
`

type SetBelegFailedParams struct {
	GeaendertAm time.Time
	ID          string
}

func (q *Queries) SetBelegFailed(ctx context.Context, arg SetBelegFailedParams) error {
	_, err := q.db.ExecContext(ctx, setBelegFailed, arg.GeaendertAm, arg.ID)
	return err
}

const stornoBeleg = `-- name: StornoBeleg :one
UPDATE beleg SET
  status = 'storniert',
  storno_grund = ?1,
  storniert_am = ?2,
  geaendert_am = ?3,
  version = version + 1
WHERE id = ?4 AND nutzer_id = ?5
  AND status = 'bestaetigt' AND version = ?6
RETURNING id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version
`

type StornoBelegParams struct {
	StornoGrund *string
	StorniertAm *time.Time
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) StornoBeleg(ctx context.Context, arg StornoBelegParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, stornoBeleg,
		arg.StornoGrund,
		arg.StorniertAm,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const touchBelegReprocess = `-- name: TouchBelegReprocess :one
UPDATE beleg SET
  status = 'in_aufbereitung',
  pipeline_parameter = ?1,
  geaendert_am = ?2,
  version = version + 1
WHERE id = ?3 AND nutzer_id = ?4
  AND version = ?5
  AND status IN ('hochgeladen', 'in_aufbereitung', 'zur_bestaetigung', 'fehlgeschlagen')
RETURNING id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version
`

type TouchBelegReprocessParams struct {
	PipelineParameter string
	GeaendertAm       time.Time
	ID                string
	NutzerID          string
	Version           int64
}

func (q *Queries) TouchBelegReprocess(ctx context.Context, arg TouchBelegReprocessParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, touchBelegReprocess,
		arg.PipelineParameter,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateBelegReady = `-- name: UpdateBelegReady :one
UPDATE beleg SET
  status = 'zur_bestaetigung',
  seiten = ?1,
  pipeline_version = ?2,
  pipeline_parameter = ?3,
  geaendert_am = ?4,
  version = version + 1
WHERE id = ?5
  AND status IN ('hochgeladen', 'in_aufbereitung', 'zur_bestaetigung', 'fehlgeschlagen')
RETURNING id, nutzer_id, belegnummer, typ, status, seiten, sha256_original, pipeline_version, pipeline_parameter, bestaetigt_am, bestaetigt_von, storno_grund, storniert_am, aufbewahren_bis, erfassung_loeschen_am, duplikat_von, erstellt_am, geaendert_am, version
`

type UpdateBelegReadyParams struct {
	Seiten            int64
	PipelineVersion   string
	PipelineParameter string
	GeaendertAm       time.Time
	ID                string
}

func (q *Queries) UpdateBelegReady(ctx context.Context, arg UpdateBelegReadyParams) (Beleg, error) {
	row := q.db.QueryRowContext(ctx, updateBelegReady,
		arg.Seiten,
		arg.PipelineVersion,
		arg.PipelineParameter,
		arg.GeaendertAm,
		arg.ID,
	)
	var i Beleg
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Belegnummer,
		&i.Typ,
		&i.Status,
		&i.Seiten,
		&i.Sha256Original,
		&i.PipelineVersion,
		&i.PipelineParameter,
		&i.BestaetigtAm,
		&i.BestaetigtVon,
		&i.StornoGrund,
		&i.StorniertAm,
		&i.AufbewahrenBis,
		&i.ErfassungLoeschenAm,
		&i.DuplikatVon,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}
