// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identitaet.sql

package sqlitedb

import (
	"context"
	"time"
)

const createIdentitaet = `-- name: CreateIdentitaet :one
INSERT INTO nutzer_identitaet (
  id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8
)
RETURNING id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am
`

type CreateIdentitaetParams struct {
	ID             string
	NutzerID       string
	Art            string
	Aussteller     string
	Subjekt        string
	ZuletztGesehen *time.Time
	ErstelltAm     time.Time
	GeaendertAm    time.Time
}

func (q *Queries) CreateIdentitaet(ctx context.Context, arg CreateIdentitaetParams) (NutzerIdentitaet, error) {
	row := q.db.QueryRowContext(ctx, createIdentitaet,
		arg.ID,
		arg.NutzerID,
		arg.Art,
		arg.Aussteller,
		arg.Subjekt,
		arg.ZuletztGesehen,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i NutzerIdentitaet
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Art,
		&i.Aussteller,
		&i.Subjekt,
		&i.ZuletztGesehen,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const deleteIdentitaet = `-- name: DeleteIdentitaet :exec
DELETE FROM nutzer_identitaet WHERE id = ?1 AND nutzer_id = ?2
`

type DeleteIdentitaetParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteIdentitaet(ctx context.Context, arg DeleteIdentitaetParams) error {
	_, err := q.db.ExecContext(ctx, deleteIdentitaet, arg.ID, arg.NutzerID)
	return err
}

const getIdentitaet = `-- name: GetIdentitaet :one
SELECT id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am FROM nutzer_identitaet
WHERE art = ?1 AND aussteller = ?2 AND subjekt = ?3
`

type GetIdentitaetParams struct {
	Art        string
	Aussteller string
	Subjekt    string
}

func (q *Queries) GetIdentitaet(ctx context.Context, arg GetIdentitaetParams) (NutzerIdentitaet, error) {
	row := q.db.QueryRowContext(ctx, getIdentitaet, arg.Art, arg.Aussteller, arg.Subjekt)
	var i NutzerIdentitaet
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Art,
		&i.Aussteller,
		&i.Subjekt,
		&i.ZuletztGesehen,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const getIdentitaetByID = `-- name: GetIdentitaetByID :one
SELECT id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am FROM nutzer_identitaet WHERE id = ?1 AND nutzer_id = ?2
`

type GetIdentitaetByIDParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetIdentitaetByID(ctx context.Context, arg GetIdentitaetByIDParams) (NutzerIdentitaet, error) {
	row := q.db.QueryRowContext(ctx, getIdentitaetByID, arg.ID, arg.NutzerID)
	var i NutzerIdentitaet
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Art,
		&i.Aussteller,
		&i.Subjekt,
		&i.ZuletztGesehen,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const listIdentitaetenByNutzer = `-- name: ListIdentitaetenByNutzer :many
SELECT id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am FROM nutzer_identitaet WHERE nutzer_id = ?1 ORDER BY id
`

func (q *Queries) ListIdentitaetenByNutzer(ctx context.Context, nutzerID string) ([]NutzerIdentitaet, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitaetenByNutzer, nutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NutzerIdentitaet
	for rows.Next() {
		var i NutzerIdentitaet
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Art,
			&i.Aussteller,
			&i.Subjekt,
			&i.ZuletztGesehen,
			&i.ErstelltAm,
			&i.GeaendertAm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchIdentitaet = `-- name: TouchIdentitaet :exec
UPDATE nutzer_identitaet SET
  zuletzt_gesehen = ?1,
  geaendert_am = ?2
WHERE id = ?3
`

type TouchIdentitaetParams struct {
	ZuletztGesehen *time.Time
	GeaendertAm    time.Time
	ID             string
}

func (q *Queries) TouchIdentitaet(ctx context.Context, arg TouchIdentitaetParams) error {
	_, err := q.db.ExecContext(ctx, touchIdentitaet, arg.ZuletztGesehen, arg.GeaendertAm, arg.ID)
	return err
}
