// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identitaet.sql

package sqlitedb

import (
	"context"
	"time"
)

const createIdentitaet = `-- name: CreateIdentitaet :one
INSERT INTO nutzer_identitaet (
  id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8
)
RETURNING id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am
`

type CreateIdentitaetParams struct {
	ID             string
	NutzerID       string
	Art            string
	Aussteller     string
	Subjekt        string
	ZuletztGesehen *time.Time
	ErstelltAm     time.Time
	GeaendertAm    time.Time
}

func (q *Queries) CreateIdentitaet(ctx context.Context, arg CreateIdentitaetParams) (NutzerIdentitaet, error) {
	row := q.db.QueryRowContext(ctx, createIdentitaet,
		arg.ID,
		arg.NutzerID,
		arg.Art,
		arg.Aussteller,
		arg.Subjekt,
		arg.ZuletztGesehen,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i NutzerIdentitaet
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Art,
		&i.Aussteller,
		&i.Subjekt,
		&i.ZuletztGesehen,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const getIdentitaet = `-- name: GetIdentitaet :one
SELECT id, nutzer_id, art, aussteller, subjekt, zuletzt_gesehen, erstellt_am, geaendert_am FROM nutzer_identitaet
WHERE art = ?1 AND aussteller = ?2 AND subjekt = ?3
`

type GetIdentitaetParams struct {
	Art        string
	Aussteller string
	Subjekt    string
}

func (q *Queries) GetIdentitaet(ctx context.Context, arg GetIdentitaetParams) (NutzerIdentitaet, error) {
	row := q.db.QueryRowContext(ctx, getIdentitaet, arg.Art, arg.Aussteller, arg.Subjekt)
	var i NutzerIdentitaet
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Art,
		&i.Aussteller,
		&i.Subjekt,
		&i.ZuletztGesehen,
		&i.ErstelltAm,
		&i.GeaendertAm,
	)
	return i, err
}

const touchIdentitaet = `-- name: TouchIdentitaet :exec
UPDATE nutzer_identitaet SET
  zuletzt_gesehen = ?1,
  geaendert_am = ?2
WHERE id = ?3
`

type TouchIdentitaetParams struct {
	ZuletztGesehen *time.Time
	GeaendertAm    time.Time
	ID             string
}

func (q *Queries) TouchIdentitaet(ctx context.Context, arg TouchIdentitaetParams) error {
	_, err := q.db.ExecContext(ctx, touchIdentitaet, arg.ZuletztGesehen, arg.GeaendertAm, arg.ID)
	return err
}
