// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"time"
)

type AuditEreigni struct {
	ID             string
	Zeitpunkt      time.Time
	AkteurNutzerID *string
	AkteurArt      string
	Aktion         string
	ObjektTyp      string
	ObjektID       string
	Vorher         *string
	Nachher        *string
	Grund          *string
	Ip             *string
	VorgaengerHash string
	Hash           string
}

type Job struct {
	ID                 string
	Art                string
	Status             string
	Payload            *string
	Versuche           int64
	NaechsterVersuchAm *time.Time
	Fehler             *string
	ErstelltAm         time.Time
	GeaendertAm        time.Time
}

type Nutzer struct {
	ID               string
	Anzeigename      string
	Email            *string
	Benutzername     string
	PasswortHash     *string
	IstAdminLokal    bool
	AdminUeberGruppe bool
	Sprache          string
	Personalnummer   *string
	KiErlaubt        bool
	Aktiv            bool
	LetzteAnmeldung  *time.Time
	ErstelltAm       time.Time
	GeaendertAm      time.Time
	Version          int64
}

type NutzerIdentitaet struct {
	ID             string
	NutzerID       string
	Art            string
	Aussteller     string
	Subjekt        string
	ZuletztGesehen *time.Time
	ErstelltAm     time.Time
	GeaendertAm    time.Time
}

type Session struct {
	Token         string
	Data          string
	Expiry        time.Time
	NutzerID      *string
	UserAgent     *string
	Ip            *string
	OeffentlichID string
	ErstelltAm    time.Time
	LetzteNutzung time.Time
}
