// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"time"
)

type Abrechnung struct {
	ID                    string
	NutzerID              string
	ArbeitgeberID         string
	Abrechnungsnummer     *string
	ZeitraumArt           string
	Von                   string
	Bis                   string
	Titel                 string
	Status                string
	EingereichtAm         *time.Time
	BezahltAm             *string
	BezahltVermerk        *string
	ExportSprache         string
	AktuelleExportVersion int64
	EinreichungLaeuft     bool
	EinreichungFehler     *string
	QuittierteWarnungen   string
	ErstelltAm            time.Time
	GeaendertAm           time.Time
	Version               int64
}

type AbrechnungReise struct {
	AbrechnungID string
	ReiseID      string
}

type AbrechnungsnummerFolge struct {
	NutzerID      string
	ArbeitgeberID string
	Jahr          int64
	Naechste      int64
}

type Arbeitgeber struct {
	ID                       string
	NutzerID                 string
	Name                     string
	Anschrift                string
	UstID                    *string
	Steuernummer             *string
	LogoDateiID              *string
	IstStandard              bool
	Konstellation            string
	AbrechnungsnummerPraefix string
	Archiviert               bool
	ErstelltAm               time.Time
	GeaendertAm              time.Time
	Version                  int64
}

type AuditEreigni struct {
	ID             string
	Zeitpunkt      time.Time
	AkteurNutzerID *string
	AkteurArt      string
	Aktion         string
	ObjektTyp      string
	ObjektID       string
	Vorher         *string
	Nachher        *string
	Grund          *string
	Ip             *string
	VorgaengerHash string
	Hash           string
}

type Ausgabe struct {
	ID                     string
	NutzerID               string
	ReiseID                string
	Kostenart              string
	Datum                  string
	Leistender             string
	Beschreibung           *string
	Waehrung               string
	Betrag                 int64
	Kurs                   *string
	KursQuelle             *string
	KursDatum              *string
	KursGrund              *string
	BetragEur              int64
	Rechnungsart           string
	RechnungAufArbeitgeber bool
	Empfaenger             *string
	Verkehrsmittel         *string
	UebernachtungNaechte   string
	FruehstueckEnthalten   bool
	Mahlzeit               *string
	Bewirtung              *string
	TseBeleg               bool
	ErstelltAm             time.Time
	GeaendertAm            time.Time
	Version                int64
}

type AusgabeBeleg struct {
	AusgabeID string
	BelegID   string
}

type Auslandssatz struct {
	ID            string
	Jahr          int64
	LandIso       string
	LandNameDe    string
	Satzort       string
	OrtName       string
	Vma24h        int64
	Vma8h         int64
	Uebernachtung int64
}

type Beleg struct {
	ID                  string
	NutzerID            string
	Belegnummer         *string
	Typ                 string
	Status              string
	Seiten              int64
	Sha256Original      string
	PipelineVersion     string
	PipelineParameter   string
	BestaetigtAm        *time.Time
	BestaetigtVon       *string
	StornoGrund         *string
	StorniertAm         *time.Time
	AufbewahrenBis      *string
	ErfassungLoeschenAm *time.Time
	DuplikatVon         *string
	ErstelltAm          time.Time
	GeaendertAm         time.Time
	Version             int64
}

type BelegNummer struct {
	NutzerID string
	Jahr     int64
	Naechste int64
}

type Belegdatei struct {
	ID                 string
	BelegID            string
	Variante           string
	Seite              int64
	SpeicherSchluessel string
	Mime               string
	Bytes              int64
	Sha256             string
	Unveraenderbar     bool
}

type Belegtext struct {
	ID            string
	BelegID       string
	Version       int64
	Quelle        string
	Felder        string
	Volltext      string
	BestaetigtAm  *time.Time
	BestaetigtVon *string
}

type Datei struct {
	ID                 string
	NutzerID           string
	Mime               string
	Bytes              int64
	Sha256             string
	SpeicherSchluessel string
	ErstelltAm         time.Time
}

type Eigenbeleg struct {
	AusgabeID          string
	Grund              string
	Zahlungsempfaenger string
	Art                string
	ErstelltAm         time.Time
	BestaetigtAm       *time.Time
	BestaetigtVon      *string
}

type Export struct {
	ID                  string
	AbrechnungID        string
	NutzerID            string
	Version             int64
	Anlass              string
	ErstelltAm          time.Time
	PdfSchluessel       *string
	PdfSha256           *string
	ZipSchluessel       *string
	ZipSha256           *string
	Snapshot            string
	ErsetztDurchVersion *int64
	Status              string
	Fehler              *string
}

type Fahrt struct {
	ID            string
	ReiseID       string
	NutzerID      string
	Datum         string
	StartOrt      string
	Ziel          string
	Zweck         *string
	Fahrzeugart   string
	Km            int64
	HinUndZurueck bool
	VorlageID     *string
	ErstelltAm    time.Time
	GeaendertAm   time.Time
	Version       int64
}

type Job struct {
	ID                 string
	Art                string
	Status             string
	Payload            *string
	Versuche           int64
	NaechsterVersuchAm *time.Time
	Fehler             *string
	ErstelltAm         time.Time
	GeaendertAm        time.Time
}

type Nutzer struct {
	ID               string
	Anzeigename      string
	Email            *string
	Benutzername     string
	PasswortHash     *string
	IstAdminLokal    bool
	AdminUeberGruppe bool
	Sprache          string
	Personalnummer   *string
	KiErlaubt        bool
	Aktiv            bool
	LetzteAnmeldung  *time.Time
	ErstelltAm       time.Time
	GeaendertAm      time.Time
	Version          int64
}

type NutzerIdentitaet struct {
	ID             string
	NutzerID       string
	Art            string
	Aussteller     string
	Subjekt        string
	ZuletztGesehen *time.Time
	ErstelltAm     time.Time
	GeaendertAm    time.Time
}

type Ortswechsel struct {
	ID                              string
	ReiseID                         string
	Reihenfolge                     int64
	Abfahrt                         *time.Time
	AbfahrtZone                     *string
	Ankunft                         time.Time
	AnkunftZone                     string
	Verkehrsmittel                  string
	LandIso                         string
	Satzort                         string
	Ort                             string
	TaetigkeitsstaetteID            *string
	ZwischenlandungMitUebernachtung bool
}

type Reise struct {
	ID            string
	NutzerID      string
	ArbeitgeberID string
	Anlass        string
	Projekt       *string
	Beginn        time.Time
	BeginnZone    string
	Ende          time.Time
	EndeZone      string
	Notiz         *string
	VorlageID     *string
	Status        string
	ErstelltAm    time.Time
	GeaendertAm   time.Time
	Version       int64
}

type Reisetag struct {
	ID                        string
	ReiseID                   string
	Datum                     string
	LandManuell               *string
	SatzortManuell            *string
	LandBegruendung           *string
	FruehstueckGestellt       bool
	MittagGestellt            bool
	AbendGestellt             bool
	ZuzahlungFruehstueck      int64
	ZuzahlungMittag           int64
	ZuzahlungAbend            int64
	MahlzeitQuelle            string
	Unterkunft                string
	VerpflegungAusgeschlossen bool
	AusschlussGrund           *string
}

type SatzOverride struct {
	ID        string
	Jahr      int64
	LandIso   *string
	Satzort   *string
	Feld      string
	AlterWert string
	NeuerWert string
	Grund     string
	AdminID   string
	Zeitpunkt time.Time
}

type Satztabelle struct {
	Jahr                         int64
	Status                       string
	Quelle                       string
	VmaInland24h                 int64
	VmaInland8h                  int64
	KuerzungFruehstueckPct       int64
	KuerzungHauptmahlzeitPct     int64
	UebernachtungInlandPauschale int64
	KmKraftwagen                 int64
	KmAnderesMotorfahrzeug       int64
	SachbezugFruehstueck         int64
	SachbezugHauptmahlzeit       int64
	UeblicheMahlzeitGrenze       int64
	Kleinbetragsgrenze           int64
	BewirtungAbzugPct            int64
	UstSaetze                    string
	AufbewahrungJahre            int64
	Ersatzlaender                string
	FlugZwischentageLand         string
	SchiffLand                   string
	ErstelltAm                   time.Time
	GeaendertAm                  time.Time
	Version                      int64
}

type Session struct {
	Token         string
	Data          string
	Expiry        time.Time
	NutzerID      *string
	UserAgent     *string
	Ip            *string
	OeffentlichID string
	ErstelltAm    time.Time
	LetzteNutzung time.Time
}

type Steueranteil struct {
	ID         string
	AusgabeID  string
	Position   int64
	Satz       int64
	Steuerland string
	Netto      int64
	Steuer     int64
	Brutto     int64
	NettoEur   int64
	SteuerEur  int64
	BruttoEur  int64
}

type Taetigkeitsstaette struct {
	ID          string
	NutzerID    string
	Bezeichnung string
	Anschrift   string
	LandIso     string
	Satzort     string
	Kunde       *string
	ErstelltAm  time.Time
	GeaendertAm time.Time
	Version     int64
}

type UstMonatskur struct {
	Jahr        int64
	Monat       int64
	Waehrung    string
	Kurs        string
	AbgerufenAm time.Time
}

type Vorlage struct {
	ID          string
	NutzerID    string
	Name        string
	Art         string
	Daten       string
	ErstelltAm  time.Time
	GeaendertAm time.Time
	Version     int64
}

type Vorschuss struct {
	ID            string
	NutzerID      string
	ArbeitgeberID string
	Datum         string
	Betrag        int64
	Notiz         *string
	AbrechnungID  *string
	ErstelltAm    time.Time
	GeaendertAm   time.Time
	Version       int64
}

type Wechselkur struct {
	Datum       string
	Waehrung    string
	Kurs        string
	Quelle      string
	AbgerufenAm time.Time
}
