// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nutzer.sql

package sqlitedb

import (
	"context"
	"time"
)

const countAktiveAdmins = `-- name: CountAktiveAdmins :one
SELECT CAST(COUNT(*) AS BIGINT) FROM nutzer
WHERE aktiv = TRUE AND (ist_admin_lokal = TRUE OR admin_ueber_gruppe = TRUE)
`

func (q *Queries) CountAktiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAktiveAdmins)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countNutzer = `-- name: CountNutzer :one
SELECT CAST(COUNT(*) AS BIGINT) FROM nutzer
`

func (q *Queries) CountNutzer(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNutzer)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNutzer = `-- name: CreateNutzer :one
INSERT INTO nutzer (
  id, anzeigename, email, benutzername, passwort_hash,
  ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer,
  ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9,
  ?10, ?11, ?12, ?13, ?14, 1
)
RETURNING id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version
`

type CreateNutzerParams struct {
	ID               string
	Anzeigename      string
	Email            *string
	Benutzername     string
	PasswortHash     *string
	IstAdminLokal    bool
	AdminUeberGruppe bool
	Sprache          string
	Personalnummer   *string
	KiErlaubt        bool
	Aktiv            bool
	LetzteAnmeldung  *time.Time
	ErstelltAm       time.Time
	GeaendertAm      time.Time
}

func (q *Queries) CreateNutzer(ctx context.Context, arg CreateNutzerParams) (Nutzer, error) {
	row := q.db.QueryRowContext(ctx, createNutzer,
		arg.ID,
		arg.Anzeigename,
		arg.Email,
		arg.Benutzername,
		arg.PasswortHash,
		arg.IstAdminLokal,
		arg.AdminUeberGruppe,
		arg.Sprache,
		arg.Personalnummer,
		arg.KiErlaubt,
		arg.Aktiv,
		arg.LetzteAnmeldung,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Nutzer
	err := row.Scan(
		&i.ID,
		&i.Anzeigename,
		&i.Email,
		&i.Benutzername,
		&i.PasswortHash,
		&i.IstAdminLokal,
		&i.AdminUeberGruppe,
		&i.Sprache,
		&i.Personalnummer,
		&i.KiErlaubt,
		&i.Aktiv,
		&i.LetzteAnmeldung,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getNutzerByBenutzername = `-- name: GetNutzerByBenutzername :one
SELECT id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version FROM nutzer WHERE benutzername = ?1
`

func (q *Queries) GetNutzerByBenutzername(ctx context.Context, benutzername string) (Nutzer, error) {
	row := q.db.QueryRowContext(ctx, getNutzerByBenutzername, benutzername)
	var i Nutzer
	err := row.Scan(
		&i.ID,
		&i.Anzeigename,
		&i.Email,
		&i.Benutzername,
		&i.PasswortHash,
		&i.IstAdminLokal,
		&i.AdminUeberGruppe,
		&i.Sprache,
		&i.Personalnummer,
		&i.KiErlaubt,
		&i.Aktiv,
		&i.LetzteAnmeldung,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getNutzerByEmail = `-- name: GetNutzerByEmail :one
SELECT id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version FROM nutzer WHERE email = ?1
`

func (q *Queries) GetNutzerByEmail(ctx context.Context, email *string) (Nutzer, error) {
	row := q.db.QueryRowContext(ctx, getNutzerByEmail, email)
	var i Nutzer
	err := row.Scan(
		&i.ID,
		&i.Anzeigename,
		&i.Email,
		&i.Benutzername,
		&i.PasswortHash,
		&i.IstAdminLokal,
		&i.AdminUeberGruppe,
		&i.Sprache,
		&i.Personalnummer,
		&i.KiErlaubt,
		&i.Aktiv,
		&i.LetzteAnmeldung,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getNutzerByID = `-- name: GetNutzerByID :one
SELECT id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version FROM nutzer WHERE id = ?1
`

func (q *Queries) GetNutzerByID(ctx context.Context, id string) (Nutzer, error) {
	row := q.db.QueryRowContext(ctx, getNutzerByID, id)
	var i Nutzer
	err := row.Scan(
		&i.ID,
		&i.Anzeigename,
		&i.Email,
		&i.Benutzername,
		&i.PasswortHash,
		&i.IstAdminLokal,
		&i.AdminUeberGruppe,
		&i.Sprache,
		&i.Personalnummer,
		&i.KiErlaubt,
		&i.Aktiv,
		&i.LetzteAnmeldung,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const listNutzer = `-- name: ListNutzer :many
SELECT id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version FROM nutzer
WHERE ?1 IS NULL OR id > ?1
ORDER BY id
LIMIT ?2
`

type ListNutzerParams struct {
	Cursor interface{}
	LimitN int64
}

func (q *Queries) ListNutzer(ctx context.Context, arg ListNutzerParams) ([]Nutzer, error) {
	rows, err := q.db.QueryContext(ctx, listNutzer, arg.Cursor, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nutzer
	for rows.Next() {
		var i Nutzer
		if err := rows.Scan(
			&i.ID,
			&i.Anzeigename,
			&i.Email,
			&i.Benutzername,
			&i.PasswortHash,
			&i.IstAdminLokal,
			&i.AdminUeberGruppe,
			&i.Sprache,
			&i.Personalnummer,
			&i.KiErlaubt,
			&i.Aktiv,
			&i.LetzteAnmeldung,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdminUeberGruppe = `-- name: SetAdminUeberGruppe :exec
UPDATE nutzer SET
  admin_ueber_gruppe = ?1,
  geaendert_am = ?2
WHERE id = ?3
`

type SetAdminUeberGruppeParams struct {
	AdminUeberGruppe bool
	GeaendertAm      time.Time
	ID               string
}

func (q *Queries) SetAdminUeberGruppe(ctx context.Context, arg SetAdminUeberGruppeParams) error {
	_, err := q.db.ExecContext(ctx, setAdminUeberGruppe, arg.AdminUeberGruppe, arg.GeaendertAm, arg.ID)
	return err
}

const touchAnmeldung = `-- name: TouchAnmeldung :exec
UPDATE nutzer SET letzte_anmeldung = ?1 WHERE id = ?2
`

type TouchAnmeldungParams struct {
	LetzteAnmeldung *time.Time
	ID              string
}

func (q *Queries) TouchAnmeldung(ctx context.Context, arg TouchAnmeldungParams) error {
	_, err := q.db.ExecContext(ctx, touchAnmeldung, arg.LetzteAnmeldung, arg.ID)
	return err
}

const updateNutzerAdmin = `-- name: UpdateNutzerAdmin :one
UPDATE nutzer SET
  aktiv = ?1,
  ist_admin_lokal = ?2,
  passwort_hash = COALESCE(?3, passwort_hash),
  geaendert_am = ?4,
  version = version + 1
WHERE id = ?5 AND version = ?6
RETURNING id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version
`

type UpdateNutzerAdminParams struct {
	Aktiv         bool
	IstAdminLokal bool
	PasswortHash  *string
	GeaendertAm   time.Time
	ID            string
	Version       int64
}

func (q *Queries) UpdateNutzerAdmin(ctx context.Context, arg UpdateNutzerAdminParams) (Nutzer, error) {
	row := q.db.QueryRowContext(ctx, updateNutzerAdmin,
		arg.Aktiv,
		arg.IstAdminLokal,
		arg.PasswortHash,
		arg.GeaendertAm,
		arg.ID,
		arg.Version,
	)
	var i Nutzer
	err := row.Scan(
		&i.ID,
		&i.Anzeigename,
		&i.Email,
		&i.Benutzername,
		&i.PasswortHash,
		&i.IstAdminLokal,
		&i.AdminUeberGruppe,
		&i.Sprache,
		&i.Personalnummer,
		&i.KiErlaubt,
		&i.Aktiv,
		&i.LetzteAnmeldung,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateNutzerPasswort = `-- name: UpdateNutzerPasswort :one
UPDATE nutzer SET
  passwort_hash = ?1,
  geaendert_am = ?2,
  version = version + 1
WHERE id = ?3 AND version = ?4
RETURNING id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version
`

type UpdateNutzerPasswortParams struct {
	PasswortHash *string
	GeaendertAm  time.Time
	ID           string
	Version      int64
}

func (q *Queries) UpdateNutzerPasswort(ctx context.Context, arg UpdateNutzerPasswortParams) (Nutzer, error) {
	row := q.db.QueryRowContext(ctx, updateNutzerPasswort,
		arg.PasswortHash,
		arg.GeaendertAm,
		arg.ID,
		arg.Version,
	)
	var i Nutzer
	err := row.Scan(
		&i.ID,
		&i.Anzeigename,
		&i.Email,
		&i.Benutzername,
		&i.PasswortHash,
		&i.IstAdminLokal,
		&i.AdminUeberGruppe,
		&i.Sprache,
		&i.Personalnummer,
		&i.KiErlaubt,
		&i.Aktiv,
		&i.LetzteAnmeldung,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateNutzerProfil = `-- name: UpdateNutzerProfil :one
UPDATE nutzer SET
  anzeigename = ?1,
  sprache = ?2,
  personalnummer = ?3,
  ki_erlaubt = ?4,
  geaendert_am = ?5,
  version = version + 1
WHERE id = ?6 AND version = ?7
RETURNING id, anzeigename, email, benutzername, passwort_hash, ist_admin_lokal, admin_ueber_gruppe, sprache, personalnummer, ki_erlaubt, aktiv, letzte_anmeldung, erstellt_am, geaendert_am, version
`

type UpdateNutzerProfilParams struct {
	Anzeigename    string
	Sprache        string
	Personalnummer *string
	KiErlaubt      bool
	GeaendertAm    time.Time
	ID             string
	Version        int64
}

func (q *Queries) UpdateNutzerProfil(ctx context.Context, arg UpdateNutzerProfilParams) (Nutzer, error) {
	row := q.db.QueryRowContext(ctx, updateNutzerProfil,
		arg.Anzeigename,
		arg.Sprache,
		arg.Personalnummer,
		arg.KiErlaubt,
		arg.GeaendertAm,
		arg.ID,
		arg.Version,
	)
	var i Nutzer
	err := row.Scan(
		&i.ID,
		&i.Anzeigename,
		&i.Email,
		&i.Benutzername,
		&i.PasswortHash,
		&i.IstAdminLokal,
		&i.AdminUeberGruppe,
		&i.Sprache,
		&i.Personalnummer,
		&i.KiErlaubt,
		&i.Aktiv,
		&i.LetzteAnmeldung,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}
