// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"context"
	"time"
)

type Querier interface {
	BumpBelegnummer(ctx context.Context, arg BumpBelegnummerParams) (int64, error)
	ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error)
	ClearAndereStandards(ctx context.Context, arg ClearAndereStandardsParams) error
	ClearErfassung(ctx context.Context, arg ClearErfassungParams) error
	ConfirmBeleg(ctx context.Context, arg ConfirmBelegParams) (Beleg, error)
	CountAktiveAdmins(ctx context.Context) (int64, error)
	CountAktiveArbeitgeber(ctx context.Context, nutzerID string) (int64, error)
	CountNutzer(ctx context.Context) (int64, error)
	CreateIdentitaet(ctx context.Context, arg CreateIdentitaetParams) (NutzerIdentitaet, error)
	CreateNutzer(ctx context.Context, arg CreateNutzerParams) (Nutzer, error)
	DeleteAusgabe(ctx context.Context, arg DeleteAusgabeParams) (int64, error)
	DeleteAusgabeBelege(ctx context.Context, ausgabeID string) error
	DeleteAuslandssaetze(ctx context.Context, jahr int64) error
	DeleteBelegOffen(ctx context.Context, arg DeleteBelegOffenParams) (int64, error)
	DeleteBelegdateiVariante(ctx context.Context, arg DeleteBelegdateiVarianteParams) error
	DeleteFahrt(ctx context.Context, arg DeleteFahrtParams) (int64, error)
	DeleteIdentitaet(ctx context.Context, arg DeleteIdentitaetParams) error
	DeleteJobsForBeleg(ctx context.Context, belegID *string) error
	DeleteOrtswechsel(ctx context.Context, reiseID string) error
	DeleteReise(ctx context.Context, arg DeleteReiseParams) (int64, error)
	DeleteReisetag(ctx context.Context, arg DeleteReisetagParams) error
	DeleteSatzOverrides(ctx context.Context, jahr int64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSessionByPublicID(ctx context.Context, arg DeleteSessionByPublicIDParams) error
	DeleteSessionsForNutzer(ctx context.Context, nutzerID *string) error
	DeleteSteueranteile(ctx context.Context, ausgabeID string) error
	DeleteTaetigkeitsstaette(ctx context.Context, arg DeleteTaetigkeitsstaetteParams) error
	DeleteVorlage(ctx context.Context, arg DeleteVorlageParams) (int64, error)
	DeleteVorschussOffen(ctx context.Context, arg DeleteVorschussOffenParams) (int64, error)
	FailJobRow(ctx context.Context, arg FailJobRowParams) error
	FindBelegByDateiSHA(ctx context.Context, arg FindBelegByDateiSHAParams) (Beleg, error)
	FindBelegBySHA(ctx context.Context, arg FindBelegBySHAParams) (Beleg, error)
	FinishJob(ctx context.Context, arg FinishJobParams) error
	FirstOtherAktiverArbeitgeber(ctx context.Context, arg FirstOtherAktiverArbeitgeberParams) (Arbeitgeber, error)
	GetArbeitgeber(ctx context.Context, arg GetArbeitgeberParams) (Arbeitgeber, error)
	GetAusgabe(ctx context.Context, arg GetAusgabeParams) (Ausgabe, error)
	GetBeleg(ctx context.Context, arg GetBelegParams) (Beleg, error)
	GetBelegByID(ctx context.Context, id string) (Beleg, error)
	GetBelegdatei(ctx context.Context, arg GetBelegdateiParams) (Belegdatei, error)
	GetDatei(ctx context.Context, arg GetDateiParams) (Datei, error)
	GetEigenbeleg(ctx context.Context, ausgabeID string) (Eigenbeleg, error)
	GetFahrt(ctx context.Context, arg GetFahrtParams) (Fahrt, error)
	GetIdentitaet(ctx context.Context, arg GetIdentitaetParams) (NutzerIdentitaet, error)
	GetIdentitaetByID(ctx context.Context, arg GetIdentitaetByIDParams) (NutzerIdentitaet, error)
	GetNutzerByBenutzername(ctx context.Context, benutzername string) (Nutzer, error)
	GetNutzerByEmail(ctx context.Context, email *string) (Nutzer, error)
	GetNutzerByID(ctx context.Context, id string) (Nutzer, error)
	GetReise(ctx context.Context, arg GetReiseParams) (Reise, error)
	GetReisetag(ctx context.Context, arg GetReisetagParams) (Reisetag, error)
	GetSatztabelle(ctx context.Context, jahr int64) (Satztabelle, error)
	GetSession(ctx context.Context, token string) (Session, error)
	GetTaetigkeitsstaette(ctx context.Context, arg GetTaetigkeitsstaetteParams) (Taetigkeitsstaette, error)
	GetUstMonatskurs(ctx context.Context, arg GetUstMonatskursParams) (UstMonatskur, error)
	GetVorlage(ctx context.Context, arg GetVorlageParams) (Vorlage, error)
	GetVorschuss(ctx context.Context, arg GetVorschussParams) (Vorschuss, error)
	InsertArbeitgeber(ctx context.Context, arg InsertArbeitgeberParams) (Arbeitgeber, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	InsertAusgabe(ctx context.Context, arg InsertAusgabeParams) (Ausgabe, error)
	InsertAusgabeBeleg(ctx context.Context, arg InsertAusgabeBelegParams) error
	InsertAuslandssatz(ctx context.Context, arg InsertAuslandssatzParams) error
	InsertBeleg(ctx context.Context, arg InsertBelegParams) (Beleg, error)
	InsertBelegdatei(ctx context.Context, arg InsertBelegdateiParams) (Belegdatei, error)
	InsertDatei(ctx context.Context, arg InsertDateiParams) (Datei, error)
	InsertFahrt(ctx context.Context, arg InsertFahrtParams) (Fahrt, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (Job, error)
	InsertOrtswechsel(ctx context.Context, arg InsertOrtswechselParams) (Ortswechsel, error)
	InsertReise(ctx context.Context, arg InsertReiseParams) (Reise, error)
	InsertReisetag(ctx context.Context, arg InsertReisetagParams) (Reisetag, error)
	InsertSatzOverride(ctx context.Context, arg InsertSatzOverrideParams) (SatzOverride, error)
	InsertSatztabelle(ctx context.Context, arg InsertSatztabelleParams) (Satztabelle, error)
	InsertSteueranteil(ctx context.Context, arg InsertSteueranteilParams) (Steueranteil, error)
	InsertTaetigkeitsstaette(ctx context.Context, arg InsertTaetigkeitsstaetteParams) (Taetigkeitsstaette, error)
	InsertVorlage(ctx context.Context, arg InsertVorlageParams) (Vorlage, error)
	InsertVorschuss(ctx context.Context, arg InsertVorschussParams) (Vorschuss, error)
	LastAuditHash(ctx context.Context) (string, error)
	ListArbeitgeber(ctx context.Context, arg ListArbeitgeberParams) ([]Arbeitgeber, error)
	ListAudit(ctx context.Context) ([]AuditEreigni, error)
	ListAuditFiltered(ctx context.Context, arg ListAuditFilteredParams) ([]AuditEreigni, error)
	ListAusgabenByNutzer(ctx context.Context, nutzerID string) ([]Ausgabe, error)
	ListAusgabenByReise(ctx context.Context, arg ListAusgabenByReiseParams) ([]Ausgabe, error)
	ListAuslandssaetze(ctx context.Context, jahr int64) ([]Auslandssatz, error)
	ListBelegdateien(ctx context.Context, belegID string) ([]Belegdatei, error)
	ListBelege(ctx context.Context, arg ListBelegeParams) ([]Beleg, error)
	ListBelegeForAusgabe(ctx context.Context, arg ListBelegeForAusgabeParams) ([]ListBelegeForAusgabeRow, error)
	ListFahrten(ctx context.Context, arg ListFahrtenParams) ([]Fahrt, error)
	ListFahrtenByNutzer(ctx context.Context, nutzerID string) ([]Fahrt, error)
	ListIdentitaetenByNutzer(ctx context.Context, nutzerID string) ([]NutzerIdentitaet, error)
	ListLaender(ctx context.Context, jahr int64) ([]ListLaenderRow, error)
	ListNutzer(ctx context.Context, arg ListNutzerParams) ([]Nutzer, error)
	ListOffeneDuplikate(ctx context.Context, nutzerID string) ([]Beleg, error)
	ListOrtswechsel(ctx context.Context, reiseID string) ([]Ortswechsel, error)
	ListProjekte(ctx context.Context, arg ListProjekteParams) ([]ListProjekteRow, error)
	ListReisen(ctx context.Context, arg ListReisenParams) ([]Reise, error)
	ListReisenAll(ctx context.Context, nutzerID string) ([]Reise, error)
	ListReisetage(ctx context.Context, reiseID string) ([]Reisetag, error)
	ListSatzOverrides(ctx context.Context, jahr int64) ([]SatzOverride, error)
	ListSatztabellen(ctx context.Context) ([]Satztabelle, error)
	ListSessionsByNutzer(ctx context.Context, arg ListSessionsByNutzerParams) ([]Session, error)
	ListSteueranteile(ctx context.Context, ausgabeID string) ([]Steueranteil, error)
	ListTaetigkeitsstaetten(ctx context.Context, arg ListTaetigkeitsstaettenParams) ([]Taetigkeitsstaette, error)
	ListVorlagen(ctx context.Context, arg ListVorlagenParams) ([]Vorlage, error)
	ListVorschuesse(ctx context.Context, nutzerID string) ([]Vorschuss, error)
	ListWechselkurse(ctx context.Context, waehrung string) ([]Wechselkur, error)
	ListWechselkurseAll(ctx context.Context) ([]Wechselkur, error)
	MarkBelegdateienFest(ctx context.Context, belegID string) error
	RescheduleJob(ctx context.Context, arg RescheduleJobParams) error
	ResumeJobs(ctx context.Context, jetzt time.Time) error
	SetAdminUeberGruppe(ctx context.Context, arg SetAdminUeberGruppeParams) error
	SetBelegFailed(ctx context.Context, arg SetBelegFailedParams) error
	SetBewirtung(ctx context.Context, arg SetBewirtungParams) (Ausgabe, error)
	SetRechnungsart(ctx context.Context, arg SetRechnungsartParams) (Ausgabe, error)
	StornoBeleg(ctx context.Context, arg StornoBelegParams) (Beleg, error)
	TouchAnmeldung(ctx context.Context, arg TouchAnmeldungParams) error
	TouchBelegReprocess(ctx context.Context, arg TouchBelegReprocessParams) (Beleg, error)
	TouchIdentitaet(ctx context.Context, arg TouchIdentitaetParams) error
	TouchReise(ctx context.Context, arg TouchReiseParams) (Reise, error)
	TouchSatztabelle(ctx context.Context, arg TouchSatztabelleParams) (Satztabelle, error)
	UpdateArbeitgeber(ctx context.Context, arg UpdateArbeitgeberParams) (Arbeitgeber, error)
	UpdateAusgabe(ctx context.Context, arg UpdateAusgabeParams) (Ausgabe, error)
	UpdateBelegReady(ctx context.Context, arg UpdateBelegReadyParams) (Beleg, error)
	UpdateFahrt(ctx context.Context, arg UpdateFahrtParams) (Fahrt, error)
	UpdateNutzerAdmin(ctx context.Context, arg UpdateNutzerAdminParams) (Nutzer, error)
	UpdateNutzerPasswort(ctx context.Context, arg UpdateNutzerPasswortParams) (Nutzer, error)
	UpdateNutzerProfil(ctx context.Context, arg UpdateNutzerProfilParams) (Nutzer, error)
	UpdateReise(ctx context.Context, arg UpdateReiseParams) (Reise, error)
	UpdateReisetag(ctx context.Context, arg UpdateReisetagParams) (Reisetag, error)
	UpdateReisetagMeals(ctx context.Context, arg UpdateReisetagMealsParams) (Reisetag, error)
	UpdateTaetigkeitsstaette(ctx context.Context, arg UpdateTaetigkeitsstaetteParams) (Taetigkeitsstaette, error)
	UpdateVorlage(ctx context.Context, arg UpdateVorlageParams) (Vorlage, error)
	UpdateVorschuss(ctx context.Context, arg UpdateVorschussParams) (Vorschuss, error)
	UpsertEigenbeleg(ctx context.Context, arg UpsertEigenbelegParams) (Eigenbeleg, error)
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
	UpsertUstMonatskurs(ctx context.Context, arg UpsertUstMonatskursParams) error
	UpsertWechselkurs(ctx context.Context, arg UpsertWechselkursParams) error
}

var _ Querier = (*Queries)(nil)
