// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reise.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteFahrt = `-- name: DeleteFahrt :execrows
DELETE FROM fahrt
WHERE id = ?1 AND nutzer_id = ?2
`

type DeleteFahrtParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteFahrt(ctx context.Context, arg DeleteFahrtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFahrt, arg.ID, arg.NutzerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOrtswechsel = `-- name: DeleteOrtswechsel :exec
DELETE FROM ortswechsel WHERE reise_id = ?1
`

func (q *Queries) DeleteOrtswechsel(ctx context.Context, reiseID string) error {
	_, err := q.db.ExecContext(ctx, deleteOrtswechsel, reiseID)
	return err
}

const deleteReise = `-- name: DeleteReise :execrows
DELETE FROM reise
WHERE id = ?1 AND nutzer_id = ?2
`

type DeleteReiseParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteReise(ctx context.Context, arg DeleteReiseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReise, arg.ID, arg.NutzerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReisetag = `-- name: DeleteReisetag :exec
DELETE FROM reisetag
WHERE reise_id = ?1 AND datum = ?2
`

type DeleteReisetagParams struct {
	ReiseID string
	Datum   string
}

func (q *Queries) DeleteReisetag(ctx context.Context, arg DeleteReisetagParams) error {
	_, err := q.db.ExecContext(ctx, deleteReisetag, arg.ReiseID, arg.Datum)
	return err
}

const deleteVorlage = `-- name: DeleteVorlage :execrows
DELETE FROM vorlage
WHERE id = ?1 AND nutzer_id = ?2
`

type DeleteVorlageParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteVorlage(ctx context.Context, arg DeleteVorlageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVorlage, arg.ID, arg.NutzerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFahrt = `-- name: GetFahrt :one
SELECT id, reise_id, nutzer_id, datum, start_ort, ziel, zweck, fahrzeugart, km, hin_und_zurueck, vorlage_id, erstellt_am, geaendert_am, version FROM fahrt
WHERE id = ?1 AND nutzer_id = ?2
`

type GetFahrtParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetFahrt(ctx context.Context, arg GetFahrtParams) (Fahrt, error) {
	row := q.db.QueryRowContext(ctx, getFahrt, arg.ID, arg.NutzerID)
	var i Fahrt
	err := row.Scan(
		&i.ID,
		&i.ReiseID,
		&i.NutzerID,
		&i.Datum,
		&i.StartOrt,
		&i.Ziel,
		&i.Zweck,
		&i.Fahrzeugart,
		&i.Km,
		&i.HinUndZurueck,
		&i.VorlageID,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getReise = `-- name: GetReise :one
SELECT id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone, notiz, vorlage_id, status, erstellt_am, geaendert_am, version FROM reise
WHERE id = ?1 AND nutzer_id = ?2
`

type GetReiseParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetReise(ctx context.Context, arg GetReiseParams) (Reise, error) {
	row := q.db.QueryRowContext(ctx, getReise, arg.ID, arg.NutzerID)
	var i Reise
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Anlass,
		&i.Projekt,
		&i.Beginn,
		&i.BeginnZone,
		&i.Ende,
		&i.EndeZone,
		&i.Notiz,
		&i.VorlageID,
		&i.Status,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const getReisetag = `-- name: GetReisetag :one
SELECT id, reise_id, datum, land_manuell, satzort_manuell, land_begruendung, fruehstueck_gestellt, mittag_gestellt, abend_gestellt, zuzahlung_fruehstueck, zuzahlung_mittag, zuzahlung_abend, mahlzeit_quelle, unterkunft, verpflegung_ausgeschlossen, ausschluss_grund FROM reisetag
WHERE reise_id = ?1 AND datum = ?2
`

type GetReisetagParams struct {
	ReiseID string
	Datum   string
}

func (q *Queries) GetReisetag(ctx context.Context, arg GetReisetagParams) (Reisetag, error) {
	row := q.db.QueryRowContext(ctx, getReisetag, arg.ReiseID, arg.Datum)
	var i Reisetag
	err := row.Scan(
		&i.ID,
		&i.ReiseID,
		&i.Datum,
		&i.LandManuell,
		&i.SatzortManuell,
		&i.LandBegruendung,
		&i.FruehstueckGestellt,
		&i.MittagGestellt,
		&i.AbendGestellt,
		&i.ZuzahlungFruehstueck,
		&i.ZuzahlungMittag,
		&i.ZuzahlungAbend,
		&i.MahlzeitQuelle,
		&i.Unterkunft,
		&i.VerpflegungAusgeschlossen,
		&i.AusschlussGrund,
	)
	return i, err
}

const getVorlage = `-- name: GetVorlage :one
SELECT id, nutzer_id, name, art, daten, erstellt_am, geaendert_am, version FROM vorlage
WHERE id = ?1 AND nutzer_id = ?2
`

type GetVorlageParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetVorlage(ctx context.Context, arg GetVorlageParams) (Vorlage, error) {
	row := q.db.QueryRowContext(ctx, getVorlage, arg.ID, arg.NutzerID)
	var i Vorlage
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Name,
		&i.Art,
		&i.Daten,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertFahrt = `-- name: InsertFahrt :one
INSERT INTO fahrt (
  id, reise_id, nutzer_id, datum, start_ort, ziel, zweck, fahrzeugart, km, hin_und_zurueck,
  vorlage_id, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9, ?10,
  ?11, ?12, ?13, 1
)
RETURNING id, reise_id, nutzer_id, datum, start_ort, ziel, zweck, fahrzeugart, km, hin_und_zurueck, vorlage_id, erstellt_am, geaendert_am, version
`

type InsertFahrtParams struct {
	ID            string
	ReiseID       string
	NutzerID      string
	Datum         string
	StartOrt      string
	Ziel          string
	Zweck         *string
	Fahrzeugart   string
	Km            int64
	HinUndZurueck bool
	VorlageID     *string
	ErstelltAm    time.Time
	GeaendertAm   time.Time
}

func (q *Queries) InsertFahrt(ctx context.Context, arg InsertFahrtParams) (Fahrt, error) {
	row := q.db.QueryRowContext(ctx, insertFahrt,
		arg.ID,
		arg.ReiseID,
		arg.NutzerID,
		arg.Datum,
		arg.StartOrt,
		arg.Ziel,
		arg.Zweck,
		arg.Fahrzeugart,
		arg.Km,
		arg.HinUndZurueck,
		arg.VorlageID,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Fahrt
	err := row.Scan(
		&i.ID,
		&i.ReiseID,
		&i.NutzerID,
		&i.Datum,
		&i.StartOrt,
		&i.Ziel,
		&i.Zweck,
		&i.Fahrzeugart,
		&i.Km,
		&i.HinUndZurueck,
		&i.VorlageID,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertOrtswechsel = `-- name: InsertOrtswechsel :one
INSERT INTO ortswechsel (
  id, reise_id, reihenfolge, abfahrt, abfahrt_zone, ankunft, ankunft_zone,
  verkehrsmittel, land_iso, satzort, ort, taetigkeitsstaette_id, zwischenlandung_mit_uebernachtung
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9,
  ?10, ?11, ?12, ?13
)
RETURNING id, reise_id, reihenfolge, abfahrt, abfahrt_zone, ankunft, ankunft_zone, verkehrsmittel, land_iso, satzort, ort, taetigkeitsstaette_id, zwischenlandung_mit_uebernachtung
`

type InsertOrtswechselParams struct {
	ID                              string
	ReiseID                         string
	Reihenfolge                     int64
	Abfahrt                         *time.Time
	AbfahrtZone                     *string
	Ankunft                         time.Time
	AnkunftZone                     string
	Verkehrsmittel                  string
	LandIso                         string
	Satzort                         string
	Ort                             string
	TaetigkeitsstaetteID            *string
	ZwischenlandungMitUebernachtung bool
}

func (q *Queries) InsertOrtswechsel(ctx context.Context, arg InsertOrtswechselParams) (Ortswechsel, error) {
	row := q.db.QueryRowContext(ctx, insertOrtswechsel,
		arg.ID,
		arg.ReiseID,
		arg.Reihenfolge,
		arg.Abfahrt,
		arg.AbfahrtZone,
		arg.Ankunft,
		arg.AnkunftZone,
		arg.Verkehrsmittel,
		arg.LandIso,
		arg.Satzort,
		arg.Ort,
		arg.TaetigkeitsstaetteID,
		arg.ZwischenlandungMitUebernachtung,
	)
	var i Ortswechsel
	err := row.Scan(
		&i.ID,
		&i.ReiseID,
		&i.Reihenfolge,
		&i.Abfahrt,
		&i.AbfahrtZone,
		&i.Ankunft,
		&i.AnkunftZone,
		&i.Verkehrsmittel,
		&i.LandIso,
		&i.Satzort,
		&i.Ort,
		&i.TaetigkeitsstaetteID,
		&i.ZwischenlandungMitUebernachtung,
	)
	return i, err
}

const insertReise = `-- name: InsertReise :one
INSERT INTO reise (
  id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone,
  notiz, vorlage_id, status, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9,
  ?10, ?11, ?12,
  ?13, ?14, 1
)
RETURNING id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone, notiz, vorlage_id, status, erstellt_am, geaendert_am, version
`

type InsertReiseParams struct {
	ID            string
	NutzerID      string
	ArbeitgeberID string
	Anlass        string
	Projekt       *string
	Beginn        time.Time
	BeginnZone    string
	Ende          time.Time
	EndeZone      string
	Notiz         *string
	VorlageID     *string
	Status        string
	ErstelltAm    time.Time
	GeaendertAm   time.Time
}

func (q *Queries) InsertReise(ctx context.Context, arg InsertReiseParams) (Reise, error) {
	row := q.db.QueryRowContext(ctx, insertReise,
		arg.ID,
		arg.NutzerID,
		arg.ArbeitgeberID,
		arg.Anlass,
		arg.Projekt,
		arg.Beginn,
		arg.BeginnZone,
		arg.Ende,
		arg.EndeZone,
		arg.Notiz,
		arg.VorlageID,
		arg.Status,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Reise
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Anlass,
		&i.Projekt,
		&i.Beginn,
		&i.BeginnZone,
		&i.Ende,
		&i.EndeZone,
		&i.Notiz,
		&i.VorlageID,
		&i.Status,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertReisetag = `-- name: InsertReisetag :one
INSERT INTO reisetag (
  id, reise_id, datum, land_manuell, satzort_manuell, land_begruendung,
  fruehstueck_gestellt, mittag_gestellt, abend_gestellt,
  zuzahlung_fruehstueck, zuzahlung_mittag, zuzahlung_abend,
  mahlzeit_quelle, unterkunft, verpflegung_ausgeschlossen, ausschluss_grund
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9,
  ?10, ?11, ?12,
  ?13, ?14, ?15, ?16
)
RETURNING id, reise_id, datum, land_manuell, satzort_manuell, land_begruendung, fruehstueck_gestellt, mittag_gestellt, abend_gestellt, zuzahlung_fruehstueck, zuzahlung_mittag, zuzahlung_abend, mahlzeit_quelle, unterkunft, verpflegung_ausgeschlossen, ausschluss_grund
`

type InsertReisetagParams struct {
	ID                        string
	ReiseID                   string
	Datum                     string
	LandManuell               *string
	SatzortManuell            *string
	LandBegruendung           *string
	FruehstueckGestellt       bool
	MittagGestellt            bool
	AbendGestellt             bool
	ZuzahlungFruehstueck      int64
	ZuzahlungMittag           int64
	ZuzahlungAbend            int64
	MahlzeitQuelle            string
	Unterkunft                string
	VerpflegungAusgeschlossen bool
	AusschlussGrund           *string
}

func (q *Queries) InsertReisetag(ctx context.Context, arg InsertReisetagParams) (Reisetag, error) {
	row := q.db.QueryRowContext(ctx, insertReisetag,
		arg.ID,
		arg.ReiseID,
		arg.Datum,
		arg.LandManuell,
		arg.SatzortManuell,
		arg.LandBegruendung,
		arg.FruehstueckGestellt,
		arg.MittagGestellt,
		arg.AbendGestellt,
		arg.ZuzahlungFruehstueck,
		arg.ZuzahlungMittag,
		arg.ZuzahlungAbend,
		arg.MahlzeitQuelle,
		arg.Unterkunft,
		arg.VerpflegungAusgeschlossen,
		arg.AusschlussGrund,
	)
	var i Reisetag
	err := row.Scan(
		&i.ID,
		&i.ReiseID,
		&i.Datum,
		&i.LandManuell,
		&i.SatzortManuell,
		&i.LandBegruendung,
		&i.FruehstueckGestellt,
		&i.MittagGestellt,
		&i.AbendGestellt,
		&i.ZuzahlungFruehstueck,
		&i.ZuzahlungMittag,
		&i.ZuzahlungAbend,
		&i.MahlzeitQuelle,
		&i.Unterkunft,
		&i.VerpflegungAusgeschlossen,
		&i.AusschlussGrund,
	)
	return i, err
}

const insertVorlage = `-- name: InsertVorlage :one
INSERT INTO vorlage (
  id, nutzer_id, name, art, daten, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, 1
)
RETURNING id, nutzer_id, name, art, daten, erstellt_am, geaendert_am, version
`

type InsertVorlageParams struct {
	ID          string
	NutzerID    string
	Name        string
	Art         string
	Daten       string
	ErstelltAm  time.Time
	GeaendertAm time.Time
}

func (q *Queries) InsertVorlage(ctx context.Context, arg InsertVorlageParams) (Vorlage, error) {
	row := q.db.QueryRowContext(ctx, insertVorlage,
		arg.ID,
		arg.NutzerID,
		arg.Name,
		arg.Art,
		arg.Daten,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Vorlage
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Name,
		&i.Art,
		&i.Daten,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const listFahrten = `-- name: ListFahrten :many
SELECT id, reise_id, nutzer_id, datum, start_ort, ziel, zweck, fahrzeugart, km, hin_und_zurueck, vorlage_id, erstellt_am, geaendert_am, version FROM fahrt
WHERE reise_id = ?1 AND nutzer_id = ?2
ORDER BY datum, id
`

type ListFahrtenParams struct {
	ReiseID  string
	NutzerID string
}

func (q *Queries) ListFahrten(ctx context.Context, arg ListFahrtenParams) ([]Fahrt, error) {
	rows, err := q.db.QueryContext(ctx, listFahrten, arg.ReiseID, arg.NutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fahrt
	for rows.Next() {
		var i Fahrt
		if err := rows.Scan(
			&i.ID,
			&i.ReiseID,
			&i.NutzerID,
			&i.Datum,
			&i.StartOrt,
			&i.Ziel,
			&i.Zweck,
			&i.Fahrzeugart,
			&i.Km,
			&i.HinUndZurueck,
			&i.VorlageID,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFahrtenByNutzer = `-- name: ListFahrtenByNutzer :many
SELECT id, reise_id, nutzer_id, datum, start_ort, ziel, zweck, fahrzeugart, km, hin_und_zurueck, vorlage_id, erstellt_am, geaendert_am, version FROM fahrt
WHERE nutzer_id = ?1
ORDER BY id
`

func (q *Queries) ListFahrtenByNutzer(ctx context.Context, nutzerID string) ([]Fahrt, error) {
	rows, err := q.db.QueryContext(ctx, listFahrtenByNutzer, nutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fahrt
	for rows.Next() {
		var i Fahrt
		if err := rows.Scan(
			&i.ID,
			&i.ReiseID,
			&i.NutzerID,
			&i.Datum,
			&i.StartOrt,
			&i.Ziel,
			&i.Zweck,
			&i.Fahrzeugart,
			&i.Km,
			&i.HinUndZurueck,
			&i.VorlageID,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrtswechsel = `-- name: ListOrtswechsel :many
SELECT id, reise_id, reihenfolge, abfahrt, abfahrt_zone, ankunft, ankunft_zone, verkehrsmittel, land_iso, satzort, ort, taetigkeitsstaette_id, zwischenlandung_mit_uebernachtung FROM ortswechsel
WHERE reise_id = ?1
ORDER BY reihenfolge
`

func (q *Queries) ListOrtswechsel(ctx context.Context, reiseID string) ([]Ortswechsel, error) {
	rows, err := q.db.QueryContext(ctx, listOrtswechsel, reiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ortswechsel
	for rows.Next() {
		var i Ortswechsel
		if err := rows.Scan(
			&i.ID,
			&i.ReiseID,
			&i.Reihenfolge,
			&i.Abfahrt,
			&i.AbfahrtZone,
			&i.Ankunft,
			&i.AnkunftZone,
			&i.Verkehrsmittel,
			&i.LandIso,
			&i.Satzort,
			&i.Ort,
			&i.TaetigkeitsstaetteID,
			&i.ZwischenlandungMitUebernachtung,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjekte = `-- name: ListProjekte :many
SELECT projekt, MAX(beginn) AS zuletzt
FROM reise
WHERE nutzer_id = ?1
  AND projekt IS NOT NULL
  AND projekt != ''
  AND (?2 = '' OR projekt LIKE ?3)
GROUP BY projekt
ORDER BY MAX(beginn) DESC
LIMIT ?4
`

type ListProjekteParams struct {
	NutzerID string
	Q        interface{}
	QLike    *string
	LimitN   int64
}

type ListProjekteRow struct {
	Projekt *string
	Zuletzt interface{}
}

func (q *Queries) ListProjekte(ctx context.Context, arg ListProjekteParams) ([]ListProjekteRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjekte,
		arg.NutzerID,
		arg.Q,
		arg.QLike,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjekteRow
	for rows.Next() {
		var i ListProjekteRow
		if err := rows.Scan(&i.Projekt, &i.Zuletzt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReisen = `-- name: ListReisen :many
SELECT id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone, notiz, vorlage_id, status, erstellt_am, geaendert_am, version FROM reise
WHERE nutzer_id = ?1
  AND (?2 = '' OR status = ?2)
  AND (?3 = '' OR arbeitgeber_id = ?3)
  AND (?4 = '' OR projekt = ?4)
  AND (
    ?5 = ''
    OR anlass LIKE ?6
    OR COALESCE(projekt, '') LIKE ?6
  )
  AND (?7 IS NULL OR ende >= ?7)
  AND (?8 IS NULL OR beginn <= ?8)
  AND (?9 IS NULL OR id > ?9)
ORDER BY id
LIMIT ?10
`

type ListReisenParams struct {
	NutzerID      string
	Status        interface{}
	ArbeitgeberID interface{}
	Projekt       interface{}
	Q             interface{}
	QLike         string
	Von           interface{}
	Bis           interface{}
	Cursor        interface{}
	LimitN        int64
}

func (q *Queries) ListReisen(ctx context.Context, arg ListReisenParams) ([]Reise, error) {
	rows, err := q.db.QueryContext(ctx, listReisen,
		arg.NutzerID,
		arg.Status,
		arg.ArbeitgeberID,
		arg.Projekt,
		arg.Q,
		arg.QLike,
		arg.Von,
		arg.Bis,
		arg.Cursor,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reise
	for rows.Next() {
		var i Reise
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ArbeitgeberID,
			&i.Anlass,
			&i.Projekt,
			&i.Beginn,
			&i.BeginnZone,
			&i.Ende,
			&i.EndeZone,
			&i.Notiz,
			&i.VorlageID,
			&i.Status,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReisenAll = `-- name: ListReisenAll :many
SELECT id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone, notiz, vorlage_id, status, erstellt_am, geaendert_am, version FROM reise
WHERE nutzer_id = ?1
ORDER BY id
`

func (q *Queries) ListReisenAll(ctx context.Context, nutzerID string) ([]Reise, error) {
	rows, err := q.db.QueryContext(ctx, listReisenAll, nutzerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reise
	for rows.Next() {
		var i Reise
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.ArbeitgeberID,
			&i.Anlass,
			&i.Projekt,
			&i.Beginn,
			&i.BeginnZone,
			&i.Ende,
			&i.EndeZone,
			&i.Notiz,
			&i.VorlageID,
			&i.Status,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReisetage = `-- name: ListReisetage :many
SELECT id, reise_id, datum, land_manuell, satzort_manuell, land_begruendung, fruehstueck_gestellt, mittag_gestellt, abend_gestellt, zuzahlung_fruehstueck, zuzahlung_mittag, zuzahlung_abend, mahlzeit_quelle, unterkunft, verpflegung_ausgeschlossen, ausschluss_grund FROM reisetag
WHERE reise_id = ?1
ORDER BY datum
`

func (q *Queries) ListReisetage(ctx context.Context, reiseID string) ([]Reisetag, error) {
	rows, err := q.db.QueryContext(ctx, listReisetage, reiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reisetag
	for rows.Next() {
		var i Reisetag
		if err := rows.Scan(
			&i.ID,
			&i.ReiseID,
			&i.Datum,
			&i.LandManuell,
			&i.SatzortManuell,
			&i.LandBegruendung,
			&i.FruehstueckGestellt,
			&i.MittagGestellt,
			&i.AbendGestellt,
			&i.ZuzahlungFruehstueck,
			&i.ZuzahlungMittag,
			&i.ZuzahlungAbend,
			&i.MahlzeitQuelle,
			&i.Unterkunft,
			&i.VerpflegungAusgeschlossen,
			&i.AusschlussGrund,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVorlagen = `-- name: ListVorlagen :many
SELECT id, nutzer_id, name, art, daten, erstellt_am, geaendert_am, version FROM vorlage
WHERE nutzer_id = ?1
  AND (?2 = '' OR art = ?2)
  AND (?3 IS NULL OR id > ?3)
ORDER BY id
LIMIT ?4
`

type ListVorlagenParams struct {
	NutzerID string
	Art      interface{}
	Cursor   interface{}
	LimitN   int64
}

func (q *Queries) ListVorlagen(ctx context.Context, arg ListVorlagenParams) ([]Vorlage, error) {
	rows, err := q.db.QueryContext(ctx, listVorlagen,
		arg.NutzerID,
		arg.Art,
		arg.Cursor,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vorlage
	for rows.Next() {
		var i Vorlage
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Name,
			&i.Art,
			&i.Daten,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchReise = `-- name: TouchReise :one
UPDATE reise SET
  geaendert_am = ?1,
  version = version + 1
WHERE id = ?2 AND nutzer_id = ?3 AND version = ?4
RETURNING id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone, notiz, vorlage_id, status, erstellt_am, geaendert_am, version
`

type TouchReiseParams struct {
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) TouchReise(ctx context.Context, arg TouchReiseParams) (Reise, error) {
	row := q.db.QueryRowContext(ctx, touchReise,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Reise
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Anlass,
		&i.Projekt,
		&i.Beginn,
		&i.BeginnZone,
		&i.Ende,
		&i.EndeZone,
		&i.Notiz,
		&i.VorlageID,
		&i.Status,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateFahrt = `-- name: UpdateFahrt :one
UPDATE fahrt SET
  datum = ?1,
  start_ort = ?2,
  ziel = ?3,
  zweck = ?4,
  fahrzeugart = ?5,
  km = ?6,
  hin_und_zurueck = ?7,
  geaendert_am = ?8,
  version = version + 1
WHERE id = ?9 AND nutzer_id = ?10 AND version = ?11
RETURNING id, reise_id, nutzer_id, datum, start_ort, ziel, zweck, fahrzeugart, km, hin_und_zurueck, vorlage_id, erstellt_am, geaendert_am, version
`

type UpdateFahrtParams struct {
	Datum         string
	StartOrt      string
	Ziel          string
	Zweck         *string
	Fahrzeugart   string
	Km            int64
	HinUndZurueck bool
	GeaendertAm   time.Time
	ID            string
	NutzerID      string
	Version       int64
}

func (q *Queries) UpdateFahrt(ctx context.Context, arg UpdateFahrtParams) (Fahrt, error) {
	row := q.db.QueryRowContext(ctx, updateFahrt,
		arg.Datum,
		arg.StartOrt,
		arg.Ziel,
		arg.Zweck,
		arg.Fahrzeugart,
		arg.Km,
		arg.HinUndZurueck,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Fahrt
	err := row.Scan(
		&i.ID,
		&i.ReiseID,
		&i.NutzerID,
		&i.Datum,
		&i.StartOrt,
		&i.Ziel,
		&i.Zweck,
		&i.Fahrzeugart,
		&i.Km,
		&i.HinUndZurueck,
		&i.VorlageID,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateReise = `-- name: UpdateReise :one
UPDATE reise SET
  arbeitgeber_id = ?1,
  anlass = ?2,
  projekt = ?3,
  beginn = ?4,
  beginn_zone = ?5,
  ende = ?6,
  ende_zone = ?7,
  notiz = ?8,
  geaendert_am = ?9,
  version = version + 1
WHERE id = ?10 AND nutzer_id = ?11 AND version = ?12
RETURNING id, nutzer_id, arbeitgeber_id, anlass, projekt, beginn, beginn_zone, ende, ende_zone, notiz, vorlage_id, status, erstellt_am, geaendert_am, version
`

type UpdateReiseParams struct {
	ArbeitgeberID string
	Anlass        string
	Projekt       *string
	Beginn        time.Time
	BeginnZone    string
	Ende          time.Time
	EndeZone      string
	Notiz         *string
	GeaendertAm   time.Time
	ID            string
	NutzerID      string
	Version       int64
}

func (q *Queries) UpdateReise(ctx context.Context, arg UpdateReiseParams) (Reise, error) {
	row := q.db.QueryRowContext(ctx, updateReise,
		arg.ArbeitgeberID,
		arg.Anlass,
		arg.Projekt,
		arg.Beginn,
		arg.BeginnZone,
		arg.Ende,
		arg.EndeZone,
		arg.Notiz,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Reise
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.ArbeitgeberID,
		&i.Anlass,
		&i.Projekt,
		&i.Beginn,
		&i.BeginnZone,
		&i.Ende,
		&i.EndeZone,
		&i.Notiz,
		&i.VorlageID,
		&i.Status,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const updateReisetag = `-- name: UpdateReisetag :one
UPDATE reisetag SET
  land_manuell = ?1,
  satzort_manuell = ?2,
  land_begruendung = ?3,
  fruehstueck_gestellt = ?4,
  mittag_gestellt = ?5,
  abend_gestellt = ?6,
  zuzahlung_fruehstueck = ?7,
  zuzahlung_mittag = ?8,
  zuzahlung_abend = ?9,
  mahlzeit_quelle = ?10,
  unterkunft = ?11,
  verpflegung_ausgeschlossen = ?12,
  ausschluss_grund = ?13
WHERE reise_id = ?14 AND datum = ?15
RETURNING id, reise_id, datum, land_manuell, satzort_manuell, land_begruendung, fruehstueck_gestellt, mittag_gestellt, abend_gestellt, zuzahlung_fruehstueck, zuzahlung_mittag, zuzahlung_abend, mahlzeit_quelle, unterkunft, verpflegung_ausgeschlossen, ausschluss_grund
`

type UpdateReisetagParams struct {
	LandManuell               *string
	SatzortManuell            *string
	LandBegruendung           *string
	FruehstueckGestellt       bool
	MittagGestellt            bool
	AbendGestellt             bool
	ZuzahlungFruehstueck      int64
	ZuzahlungMittag           int64
	ZuzahlungAbend            int64
	MahlzeitQuelle            string
	Unterkunft                string
	VerpflegungAusgeschlossen bool
	AusschlussGrund           *string
	ReiseID                   string
	Datum                     string
}

func (q *Queries) UpdateReisetag(ctx context.Context, arg UpdateReisetagParams) (Reisetag, error) {
	row := q.db.QueryRowContext(ctx, updateReisetag,
		arg.LandManuell,
		arg.SatzortManuell,
		arg.LandBegruendung,
		arg.FruehstueckGestellt,
		arg.MittagGestellt,
		arg.AbendGestellt,
		arg.ZuzahlungFruehstueck,
		arg.ZuzahlungMittag,
		arg.ZuzahlungAbend,
		arg.MahlzeitQuelle,
		arg.Unterkunft,
		arg.VerpflegungAusgeschlossen,
		arg.AusschlussGrund,
		arg.ReiseID,
		arg.Datum,
	)
	var i Reisetag
	err := row.Scan(
		&i.ID,
		&i.ReiseID,
		&i.Datum,
		&i.LandManuell,
		&i.SatzortManuell,
		&i.LandBegruendung,
		&i.FruehstueckGestellt,
		&i.MittagGestellt,
		&i.AbendGestellt,
		&i.ZuzahlungFruehstueck,
		&i.ZuzahlungMittag,
		&i.ZuzahlungAbend,
		&i.MahlzeitQuelle,
		&i.Unterkunft,
		&i.VerpflegungAusgeschlossen,
		&i.AusschlussGrund,
	)
	return i, err
}

const updateVorlage = `-- name: UpdateVorlage :one
UPDATE vorlage SET
  name = ?1,
  daten = ?2,
  geaendert_am = ?3,
  version = version + 1
WHERE id = ?4 AND nutzer_id = ?5 AND version = ?6
RETURNING id, nutzer_id, name, art, daten, erstellt_am, geaendert_am, version
`

type UpdateVorlageParams struct {
	Name        string
	Daten       string
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) UpdateVorlage(ctx context.Context, arg UpdateVorlageParams) (Vorlage, error) {
	row := q.db.QueryRowContext(ctx, updateVorlage,
		arg.Name,
		arg.Daten,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Vorlage
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Name,
		&i.Art,
		&i.Daten,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}
