// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: satztabelle.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteAuslandssaetze = `-- name: DeleteAuslandssaetze :exec
DELETE FROM auslandssatz WHERE jahr = ?1
`

func (q *Queries) DeleteAuslandssaetze(ctx context.Context, jahr int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuslandssaetze, jahr)
	return err
}

const deleteSatzOverrides = `-- name: DeleteSatzOverrides :exec
DELETE FROM satz_override WHERE jahr = ?1
`

func (q *Queries) DeleteSatzOverrides(ctx context.Context, jahr int64) error {
	_, err := q.db.ExecContext(ctx, deleteSatzOverrides, jahr)
	return err
}

const getSatztabelle = `-- name: GetSatztabelle :one
SELECT jahr, status, quelle, vma_inland_24h, vma_inland_8h, kuerzung_fruehstueck_pct, kuerzung_hauptmahlzeit_pct, uebernachtung_inland_pauschale, km_kraftwagen, km_anderes_motorfahrzeug, sachbezug_fruehstueck, sachbezug_hauptmahlzeit, uebliche_mahlzeit_grenze, kleinbetragsgrenze, bewirtung_abzug_pct, ust_saetze, aufbewahrung_jahre, ersatzlaender, flug_zwischentage_land, schiff_land, erstellt_am, geaendert_am, version FROM satztabelle WHERE jahr = ?1
`

func (q *Queries) GetSatztabelle(ctx context.Context, jahr int64) (Satztabelle, error) {
	row := q.db.QueryRowContext(ctx, getSatztabelle, jahr)
	var i Satztabelle
	err := row.Scan(
		&i.Jahr,
		&i.Status,
		&i.Quelle,
		&i.VmaInland24h,
		&i.VmaInland8h,
		&i.KuerzungFruehstueckPct,
		&i.KuerzungHauptmahlzeitPct,
		&i.UebernachtungInlandPauschale,
		&i.KmKraftwagen,
		&i.KmAnderesMotorfahrzeug,
		&i.SachbezugFruehstueck,
		&i.SachbezugHauptmahlzeit,
		&i.UeblicheMahlzeitGrenze,
		&i.Kleinbetragsgrenze,
		&i.BewirtungAbzugPct,
		&i.UstSaetze,
		&i.AufbewahrungJahre,
		&i.Ersatzlaender,
		&i.FlugZwischentageLand,
		&i.SchiffLand,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertAuslandssatz = `-- name: InsertAuslandssatz :exec
INSERT INTO auslandssatz (
  id, jahr, land_iso, land_name_de, satzort, ort_name, vma_24h, vma_8h, uebernachtung
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8, ?9
)
`

type InsertAuslandssatzParams struct {
	ID            string
	Jahr          int64
	LandIso       string
	LandNameDe    string
	Satzort       string
	OrtName       string
	Vma24h        int64
	Vma8h         int64
	Uebernachtung int64
}

func (q *Queries) InsertAuslandssatz(ctx context.Context, arg InsertAuslandssatzParams) error {
	_, err := q.db.ExecContext(ctx, insertAuslandssatz,
		arg.ID,
		arg.Jahr,
		arg.LandIso,
		arg.LandNameDe,
		arg.Satzort,
		arg.OrtName,
		arg.Vma24h,
		arg.Vma8h,
		arg.Uebernachtung,
	)
	return err
}

const insertSatzOverride = `-- name: InsertSatzOverride :one
INSERT INTO satz_override (
  id, jahr, land_iso, satzort, feld, alter_wert, neuer_wert, grund, admin_id, zeitpunkt
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9, ?10
)
RETURNING id, jahr, land_iso, satzort, feld, alter_wert, neuer_wert, grund, admin_id, zeitpunkt
`

type InsertSatzOverrideParams struct {
	ID        string
	Jahr      int64
	LandIso   *string
	Satzort   *string
	Feld      string
	AlterWert string
	NeuerWert string
	Grund     string
	AdminID   string
	Zeitpunkt time.Time
}

func (q *Queries) InsertSatzOverride(ctx context.Context, arg InsertSatzOverrideParams) (SatzOverride, error) {
	row := q.db.QueryRowContext(ctx, insertSatzOverride,
		arg.ID,
		arg.Jahr,
		arg.LandIso,
		arg.Satzort,
		arg.Feld,
		arg.AlterWert,
		arg.NeuerWert,
		arg.Grund,
		arg.AdminID,
		arg.Zeitpunkt,
	)
	var i SatzOverride
	err := row.Scan(
		&i.ID,
		&i.Jahr,
		&i.LandIso,
		&i.Satzort,
		&i.Feld,
		&i.AlterWert,
		&i.NeuerWert,
		&i.Grund,
		&i.AdminID,
		&i.Zeitpunkt,
	)
	return i, err
}

const insertSatztabelle = `-- name: InsertSatztabelle :one
INSERT INTO satztabelle (
  jahr, status, quelle,
  vma_inland_24h, vma_inland_8h, kuerzung_fruehstueck_pct, kuerzung_hauptmahlzeit_pct,
  uebernachtung_inland_pauschale, km_kraftwagen, km_anderes_motorfahrzeug,
  sachbezug_fruehstueck, sachbezug_hauptmahlzeit, uebliche_mahlzeit_grenze,
  kleinbetragsgrenze, bewirtung_abzug_pct, ust_saetze, aufbewahrung_jahre,
  ersatzlaender, flug_zwischentage_land, schiff_land, erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5,
  ?6, ?7,
  ?8, ?9, ?10,
  ?11, ?12, ?13,
  ?14, ?15, ?16,
  ?17, ?18, ?19,
  ?20, ?21, ?22, 1
)
RETURNING jahr, status, quelle, vma_inland_24h, vma_inland_8h, kuerzung_fruehstueck_pct, kuerzung_hauptmahlzeit_pct, uebernachtung_inland_pauschale, km_kraftwagen, km_anderes_motorfahrzeug, sachbezug_fruehstueck, sachbezug_hauptmahlzeit, uebliche_mahlzeit_grenze, kleinbetragsgrenze, bewirtung_abzug_pct, ust_saetze, aufbewahrung_jahre, ersatzlaender, flug_zwischentage_land, schiff_land, erstellt_am, geaendert_am, version
`

type InsertSatztabelleParams struct {
	Jahr                         int64
	Status                       string
	Quelle                       string
	VmaInland24h                 int64
	VmaInland8h                  int64
	KuerzungFruehstueckPct       int64
	KuerzungHauptmahlzeitPct     int64
	UebernachtungInlandPauschale int64
	KmKraftwagen                 int64
	KmAnderesMotorfahrzeug       int64
	SachbezugFruehstueck         int64
	SachbezugHauptmahlzeit       int64
	UeblicheMahlzeitGrenze       int64
	Kleinbetragsgrenze           int64
	BewirtungAbzugPct            int64
	UstSaetze                    string
	AufbewahrungJahre            int64
	Ersatzlaender                string
	FlugZwischentageLand         string
	SchiffLand                   string
	ErstelltAm                   time.Time
	GeaendertAm                  time.Time
}

func (q *Queries) InsertSatztabelle(ctx context.Context, arg InsertSatztabelleParams) (Satztabelle, error) {
	row := q.db.QueryRowContext(ctx, insertSatztabelle,
		arg.Jahr,
		arg.Status,
		arg.Quelle,
		arg.VmaInland24h,
		arg.VmaInland8h,
		arg.KuerzungFruehstueckPct,
		arg.KuerzungHauptmahlzeitPct,
		arg.UebernachtungInlandPauschale,
		arg.KmKraftwagen,
		arg.KmAnderesMotorfahrzeug,
		arg.SachbezugFruehstueck,
		arg.SachbezugHauptmahlzeit,
		arg.UeblicheMahlzeitGrenze,
		arg.Kleinbetragsgrenze,
		arg.BewirtungAbzugPct,
		arg.UstSaetze,
		arg.AufbewahrungJahre,
		arg.Ersatzlaender,
		arg.FlugZwischentageLand,
		arg.SchiffLand,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Satztabelle
	err := row.Scan(
		&i.Jahr,
		&i.Status,
		&i.Quelle,
		&i.VmaInland24h,
		&i.VmaInland8h,
		&i.KuerzungFruehstueckPct,
		&i.KuerzungHauptmahlzeitPct,
		&i.UebernachtungInlandPauschale,
		&i.KmKraftwagen,
		&i.KmAnderesMotorfahrzeug,
		&i.SachbezugFruehstueck,
		&i.SachbezugHauptmahlzeit,
		&i.UeblicheMahlzeitGrenze,
		&i.Kleinbetragsgrenze,
		&i.BewirtungAbzugPct,
		&i.UstSaetze,
		&i.AufbewahrungJahre,
		&i.Ersatzlaender,
		&i.FlugZwischentageLand,
		&i.SchiffLand,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const listAuslandssaetze = `-- name: ListAuslandssaetze :many
SELECT id, jahr, land_iso, land_name_de, satzort, ort_name, vma_24h, vma_8h, uebernachtung FROM auslandssatz WHERE jahr = ?1 ORDER BY land_name_de, satzort, id
`

func (q *Queries) ListAuslandssaetze(ctx context.Context, jahr int64) ([]Auslandssatz, error) {
	rows, err := q.db.QueryContext(ctx, listAuslandssaetze, jahr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auslandssatz
	for rows.Next() {
		var i Auslandssatz
		if err := rows.Scan(
			&i.ID,
			&i.Jahr,
			&i.LandIso,
			&i.LandNameDe,
			&i.Satzort,
			&i.OrtName,
			&i.Vma24h,
			&i.Vma8h,
			&i.Uebernachtung,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLaender = `-- name: ListLaender :many
SELECT DISTINCT land_iso, land_name_de FROM auslandssatz
WHERE jahr = ?1
ORDER BY land_name_de, land_iso
`

type ListLaenderRow struct {
	LandIso    string
	LandNameDe string
}

func (q *Queries) ListLaender(ctx context.Context, jahr int64) ([]ListLaenderRow, error) {
	rows, err := q.db.QueryContext(ctx, listLaender, jahr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLaenderRow
	for rows.Next() {
		var i ListLaenderRow
		if err := rows.Scan(&i.LandIso, &i.LandNameDe); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSatzOverrides = `-- name: ListSatzOverrides :many
SELECT id, jahr, land_iso, satzort, feld, alter_wert, neuer_wert, grund, admin_id, zeitpunkt FROM satz_override WHERE jahr = ?1 ORDER BY zeitpunkt, id
`

func (q *Queries) ListSatzOverrides(ctx context.Context, jahr int64) ([]SatzOverride, error) {
	rows, err := q.db.QueryContext(ctx, listSatzOverrides, jahr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SatzOverride
	for rows.Next() {
		var i SatzOverride
		if err := rows.Scan(
			&i.ID,
			&i.Jahr,
			&i.LandIso,
			&i.Satzort,
			&i.Feld,
			&i.AlterWert,
			&i.NeuerWert,
			&i.Grund,
			&i.AdminID,
			&i.Zeitpunkt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSatztabellen = `-- name: ListSatztabellen :many
SELECT jahr, status, quelle, vma_inland_24h, vma_inland_8h, kuerzung_fruehstueck_pct, kuerzung_hauptmahlzeit_pct, uebernachtung_inland_pauschale, km_kraftwagen, km_anderes_motorfahrzeug, sachbezug_fruehstueck, sachbezug_hauptmahlzeit, uebliche_mahlzeit_grenze, kleinbetragsgrenze, bewirtung_abzug_pct, ust_saetze, aufbewahrung_jahre, ersatzlaender, flug_zwischentage_land, schiff_land, erstellt_am, geaendert_am, version FROM satztabelle ORDER BY jahr
`

func (q *Queries) ListSatztabellen(ctx context.Context) ([]Satztabelle, error) {
	rows, err := q.db.QueryContext(ctx, listSatztabellen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Satztabelle
	for rows.Next() {
		var i Satztabelle
		if err := rows.Scan(
			&i.Jahr,
			&i.Status,
			&i.Quelle,
			&i.VmaInland24h,
			&i.VmaInland8h,
			&i.KuerzungFruehstueckPct,
			&i.KuerzungHauptmahlzeitPct,
			&i.UebernachtungInlandPauschale,
			&i.KmKraftwagen,
			&i.KmAnderesMotorfahrzeug,
			&i.SachbezugFruehstueck,
			&i.SachbezugHauptmahlzeit,
			&i.UeblicheMahlzeitGrenze,
			&i.Kleinbetragsgrenze,
			&i.BewirtungAbzugPct,
			&i.UstSaetze,
			&i.AufbewahrungJahre,
			&i.Ersatzlaender,
			&i.FlugZwischentageLand,
			&i.SchiffLand,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSatztabelle = `-- name: TouchSatztabelle :one
UPDATE satztabelle SET
  status = ?1,
  geaendert_am = ?2,
  version = version + 1
WHERE jahr = ?3 AND version = ?4
RETURNING jahr, status, quelle, vma_inland_24h, vma_inland_8h, kuerzung_fruehstueck_pct, kuerzung_hauptmahlzeit_pct, uebernachtung_inland_pauschale, km_kraftwagen, km_anderes_motorfahrzeug, sachbezug_fruehstueck, sachbezug_hauptmahlzeit, uebliche_mahlzeit_grenze, kleinbetragsgrenze, bewirtung_abzug_pct, ust_saetze, aufbewahrung_jahre, ersatzlaender, flug_zwischentage_land, schiff_land, erstellt_am, geaendert_am, version
`

type TouchSatztabelleParams struct {
	Status      string
	GeaendertAm time.Time
	Jahr        int64
	Version     int64
}

func (q *Queries) TouchSatztabelle(ctx context.Context, arg TouchSatztabelleParams) (Satztabelle, error) {
	row := q.db.QueryRowContext(ctx, touchSatztabelle,
		arg.Status,
		arg.GeaendertAm,
		arg.Jahr,
		arg.Version,
	)
	var i Satztabelle
	err := row.Scan(
		&i.Jahr,
		&i.Status,
		&i.Quelle,
		&i.VmaInland24h,
		&i.VmaInland8h,
		&i.KuerzungFruehstueckPct,
		&i.KuerzungHauptmahlzeitPct,
		&i.UebernachtungInlandPauschale,
		&i.KmKraftwagen,
		&i.KmAnderesMotorfahrzeug,
		&i.SachbezugFruehstueck,
		&i.SachbezugHauptmahlzeit,
		&i.UeblicheMahlzeitGrenze,
		&i.Kleinbetragsgrenze,
		&i.BewirtungAbzugPct,
		&i.UstSaetze,
		&i.AufbewahrungJahre,
		&i.Ersatzlaender,
		&i.FlugZwischentageLand,
		&i.SchiffLand,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}
