// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionByPublicID = `-- name: DeleteSessionByPublicID :exec
DELETE FROM session WHERE oeffentlich_id = ?1 AND nutzer_id = ?2
`

type DeleteSessionByPublicIDParams struct {
	OeffentlichID string
	NutzerID      *string
}

func (q *Queries) DeleteSessionByPublicID(ctx context.Context, arg DeleteSessionByPublicIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByPublicID, arg.OeffentlichID, arg.NutzerID)
	return err
}

const deleteSessionsForNutzer = `-- name: DeleteSessionsForNutzer :exec
DELETE FROM session WHERE nutzer_id = ?1
`

func (q *Queries) DeleteSessionsForNutzer(ctx context.Context, nutzerID *string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForNutzer, nutzerID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token, data, expiry, nutzer_id, user_agent, ip, oeffentlich_id, erstellt_am, letzte_nutzung FROM session WHERE token = ?1
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.Data,
		&i.Expiry,
		&i.NutzerID,
		&i.UserAgent,
		&i.Ip,
		&i.OeffentlichID,
		&i.ErstelltAm,
		&i.LetzteNutzung,
	)
	return i, err
}

const listSessionsByNutzer = `-- name: ListSessionsByNutzer :many
SELECT token, data, expiry, nutzer_id, user_agent, ip, oeffentlich_id, erstellt_am, letzte_nutzung FROM session
WHERE nutzer_id = ?1 AND expiry > ?2
ORDER BY letzte_nutzung DESC
`

type ListSessionsByNutzerParams struct {
	NutzerID *string
	Now      time.Time
}

func (q *Queries) ListSessionsByNutzer(ctx context.Context, arg ListSessionsByNutzerParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByNutzer, arg.NutzerID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Token,
			&i.Data,
			&i.Expiry,
			&i.NutzerID,
			&i.UserAgent,
			&i.Ip,
			&i.OeffentlichID,
			&i.ErstelltAm,
			&i.LetzteNutzung,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO session (
  token, data, expiry, nutzer_id, user_agent, ip, oeffentlich_id, erstellt_am, letzte_nutzung
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9
)
ON CONFLICT (token) DO UPDATE SET
  data = excluded.data,
  expiry = excluded.expiry,
  nutzer_id = COALESCE(excluded.nutzer_id, session.nutzer_id),
  user_agent = COALESCE(excluded.user_agent, session.user_agent),
  ip = COALESCE(excluded.ip, session.ip),
  letzte_nutzung = excluded.letzte_nutzung
`

type UpsertSessionParams struct {
	Token         string
	Data          string
	Expiry        time.Time
	NutzerID      *string
	UserAgent     *string
	Ip            *string
	OeffentlichID string
	ErstelltAm    time.Time
	LetzteNutzung time.Time
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.Token,
		arg.Data,
		arg.Expiry,
		arg.NutzerID,
		arg.UserAgent,
		arg.Ip,
		arg.OeffentlichID,
		arg.ErstelltAm,
		arg.LetzteNutzung,
	)
	return err
}
