// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taetigkeitsstaette.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteTaetigkeitsstaette = `-- name: DeleteTaetigkeitsstaette :exec
DELETE FROM taetigkeitsstaette
WHERE id = ?1 AND nutzer_id = ?2
`

type DeleteTaetigkeitsstaetteParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) DeleteTaetigkeitsstaette(ctx context.Context, arg DeleteTaetigkeitsstaetteParams) error {
	_, err := q.db.ExecContext(ctx, deleteTaetigkeitsstaette, arg.ID, arg.NutzerID)
	return err
}

const getTaetigkeitsstaette = `-- name: GetTaetigkeitsstaette :one
SELECT id, nutzer_id, bezeichnung, anschrift, land_iso, satzort, kunde, erstellt_am, geaendert_am, version FROM taetigkeitsstaette
WHERE id = ?1 AND nutzer_id = ?2
`

type GetTaetigkeitsstaetteParams struct {
	ID       string
	NutzerID string
}

func (q *Queries) GetTaetigkeitsstaette(ctx context.Context, arg GetTaetigkeitsstaetteParams) (Taetigkeitsstaette, error) {
	row := q.db.QueryRowContext(ctx, getTaetigkeitsstaette, arg.ID, arg.NutzerID)
	var i Taetigkeitsstaette
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Bezeichnung,
		&i.Anschrift,
		&i.LandIso,
		&i.Satzort,
		&i.Kunde,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const insertTaetigkeitsstaette = `-- name: InsertTaetigkeitsstaette :one
INSERT INTO taetigkeitsstaette (
  id, nutzer_id, bezeichnung, anschrift, land_iso, satzort, kunde,
  erstellt_am, geaendert_am, version
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, 1
)
RETURNING id, nutzer_id, bezeichnung, anschrift, land_iso, satzort, kunde, erstellt_am, geaendert_am, version
`

type InsertTaetigkeitsstaetteParams struct {
	ID          string
	NutzerID    string
	Bezeichnung string
	Anschrift   string
	LandIso     string
	Satzort     string
	Kunde       *string
	ErstelltAm  time.Time
	GeaendertAm time.Time
}

func (q *Queries) InsertTaetigkeitsstaette(ctx context.Context, arg InsertTaetigkeitsstaetteParams) (Taetigkeitsstaette, error) {
	row := q.db.QueryRowContext(ctx, insertTaetigkeitsstaette,
		arg.ID,
		arg.NutzerID,
		arg.Bezeichnung,
		arg.Anschrift,
		arg.LandIso,
		arg.Satzort,
		arg.Kunde,
		arg.ErstelltAm,
		arg.GeaendertAm,
	)
	var i Taetigkeitsstaette
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Bezeichnung,
		&i.Anschrift,
		&i.LandIso,
		&i.Satzort,
		&i.Kunde,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}

const listTaetigkeitsstaetten = `-- name: ListTaetigkeitsstaetten :many
SELECT id, nutzer_id, bezeichnung, anschrift, land_iso, satzort, kunde, erstellt_am, geaendert_am, version FROM taetigkeitsstaette
WHERE nutzer_id = ?1
  AND (?2 IS NULL OR id > ?2)
ORDER BY id
LIMIT ?3
`

type ListTaetigkeitsstaettenParams struct {
	NutzerID string
	Cursor   interface{}
	LimitN   int64
}

func (q *Queries) ListTaetigkeitsstaetten(ctx context.Context, arg ListTaetigkeitsstaettenParams) ([]Taetigkeitsstaette, error) {
	rows, err := q.db.QueryContext(ctx, listTaetigkeitsstaetten, arg.NutzerID, arg.Cursor, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Taetigkeitsstaette
	for rows.Next() {
		var i Taetigkeitsstaette
		if err := rows.Scan(
			&i.ID,
			&i.NutzerID,
			&i.Bezeichnung,
			&i.Anschrift,
			&i.LandIso,
			&i.Satzort,
			&i.Kunde,
			&i.ErstelltAm,
			&i.GeaendertAm,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaetigkeitsstaette = `-- name: UpdateTaetigkeitsstaette :one
UPDATE taetigkeitsstaette SET
  bezeichnung = ?1,
  anschrift = ?2,
  land_iso = ?3,
  satzort = ?4,
  kunde = ?5,
  geaendert_am = ?6,
  version = version + 1
WHERE id = ?7 AND nutzer_id = ?8 AND version = ?9
RETURNING id, nutzer_id, bezeichnung, anschrift, land_iso, satzort, kunde, erstellt_am, geaendert_am, version
`

type UpdateTaetigkeitsstaetteParams struct {
	Bezeichnung string
	Anschrift   string
	LandIso     string
	Satzort     string
	Kunde       *string
	GeaendertAm time.Time
	ID          string
	NutzerID    string
	Version     int64
}

func (q *Queries) UpdateTaetigkeitsstaette(ctx context.Context, arg UpdateTaetigkeitsstaetteParams) (Taetigkeitsstaette, error) {
	row := q.db.QueryRowContext(ctx, updateTaetigkeitsstaette,
		arg.Bezeichnung,
		arg.Anschrift,
		arg.LandIso,
		arg.Satzort,
		arg.Kunde,
		arg.GeaendertAm,
		arg.ID,
		arg.NutzerID,
		arg.Version,
	)
	var i Taetigkeitsstaette
	err := row.Scan(
		&i.ID,
		&i.NutzerID,
		&i.Bezeichnung,
		&i.Anschrift,
		&i.LandIso,
		&i.Satzort,
		&i.Kunde,
		&i.ErstelltAm,
		&i.GeaendertAm,
		&i.Version,
	)
	return i, err
}
